// Every word the portal shows, in English and Arabic. Placeholders are {name}; t() fills them.
// Arabic is written for venue owners in Saudi Arabia: plain, polite, and with Western digits
// (the numbers themselves are formatted elsewhere with -nu-latn).

const en = {
  appName: "MicroMobility Partners",
  appTagline: "Breakfast partners for the Saturday social ride",
  langSwitch: "العربية",
  langSwitchLabel: "Switch to Arabic",
  signOut: "Sign out",
  loading: "Loading…",
  retry: "Try again",
  close: "Close",
  back: "Back",
  save: "Save",
  saved: "Saved.",

  // Sign in
  signInTitle: "Sign in",
  signInIntro: "Reserve the Saturdays our riders come to you for breakfast.",
  loginLabel: "Email or mobile number",
  passwordLabel: "Password",
  signInButton: "Sign in",
  signingIn: "Signing in…",
  showPassword: "Show password",
  hidePassword: "Hide password",
  noAccount: "Accounts are created by MicroMobility. To get one, contact us.",
  errBadLogin: "That email, mobile number or password is not right.",
  errLocked: "Too many tries. For your safety, sign-in is paused; try again in 15 minutes.",
  errRateLimit: "Too many tries from this connection. Wait a minute and try again.",
  errNetwork: "We could not reach the server. Check your connection and try again.",
  errServer: "Something went wrong on our side. Try again in a moment.",
  errInput: "Some of the details are not valid. Check them and try again.",
  errSession: "Your session has ended. Please sign in again.",

  // Passwords
  forceTitle: "Choose your own password",
  forceIntro: "You signed in with a temporary password. Choose a new one to continue.",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  currentPassword: "Current password",
  pwRules: "At least 8 characters, with one capital letter and one number.",
  pwRuleLength: "At least 8 characters",
  pwRuleCapital: "One capital letter (A-Z)",
  pwRuleNumber: "One number (0-9)",
  pwMismatch: "The two passwords do not match.",
  errWeak: "This password is too weak. Follow the rules below.",
  errSame: "The new password must be different from the current one.",
  errBadPassword: "The current password is not right.",
  pwSaveButton: "Save password",
  pwChanged: "Password changed. Other devices have been signed out.",
  changePasswordTitle: "Change password",

  // Navigation
  navCalendar: "Calendar",
  navBookings: "My bookings",
  navVenue: "Venue",
  mainNav: "Main",

  // Calendar
  calendarTitle: "Breakfast calendar",
  calendarIntro: "Saturdays open for breakfast after the social ride. Tap an available date to request it.",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  today: "Today",
  bookButton: "Request dates",
  legend: "Key",
  stAvailable: "Available",
  stRequested: "Requested",
  stConfirmed: "Confirmed",
  stTaken: "Taken",
  stClosed: "Closed",
  stNotOpen: "Not open",
  stPast: "Past",
  stSoon: "Too soon",
  stFar: "Too far ahead",
  requestThis: "Request",
  ridersBooked: "{n} riders booked",
  oneRiderBooked: "1 rider booked",
  closedReason: "Closed: {reason}",
  noDatesMonth: "No dates are open for breakfast this month.",
  weekdaysShort: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",

  // Booking dialog
  bookTitle: "Request breakfast dates",
  modeLabel: "How would you like to book?",
  modeSingle: "One date",
  modeMulti: "Several dates",
  modeRecurring: "Repeat monthly",
  modeOffSingle: "Your plan does not include single dates.",
  modeOffMulti: "Your plan books one date at a time.",
  modeOffRecurring: "Your plan does not include monthly repeats.",
  pickDate: "Date",
  pickDates: "Tap the available dates you want",
  chosenDates: "Chosen dates",
  noneChosen: "No dates chosen yet.",
  removeDate: "Remove {date}",
  noAvailable: "There are no available dates in your booking window right now.",
  every: "Every",
  saturdayOf: "Saturday,",
  everyN: "every",
  monthsUnit: "month(s),",
  from: "from",
  until: "until",
  ord1: "first",
  ord2: "second",
  ord3: "third",
  ord4: "fourth",
  ordLast: "last",
  noteLabel: "Note for MicroMobility (optional)",
  noteHint: "{n} characters left",
  previewButton: "Check dates",
  checking: "Checking…",
  previewTitle: "Before you send",
  previewSummary: "{ok} of {all} dates can be requested.",
  previewNone: "None of these dates can be requested.",
  previewEmpty: "This pattern has no Saturdays in your booking window.",
  sendButton: "Send request",
  sending: "Sending…",
  editChoice: "Change",
  resultTitle: "Request sent",
  resultBody: "Requested {n} dates. MicroMobility will confirm; several venues may ask for the same date and we choose one.",
  resultBodyOne: "Requested 1 date. MicroMobility will confirm; several venues may ask for the same date and we choose one.",
  resultNone: "No dates were requested: none of them were free any more.",
  done: "Done",
  vOk: "Free",
  vTaken: "Another venue has this date",
  vClosed: "Closed: {reason}",
  vClosedNoReason: "Closed",
  rsRamadan: "Ramadan",
  rsEid: "Eid",
  rsWeather: "Weather",
  rsHoliday: "Holiday",
  vNotOpen: "Not open for breakfast",
  vTooSoon: "Needs {n} days' notice",
  vTooFar: "Too far ahead",
  vMine: "You already asked for this date",
  vOverQuota: "Over your plan's monthly limit ({n})",
  vNotAllowed: "Not in your plan",
  errOneDate: "Choose one date.",
  errChooseDates: "Choose at least one date.",
  errTooMany: "That is too many dates at once (60 at most).",
  errPattern: "Complete the sentence: which Saturday, how often, from and until.",

  // My bookings
  bookingsTitle: "My bookings",
  upcoming: "Upcoming",
  past: "Past",
  noUpcoming: "No upcoming bookings. Open the calendar to request a date.",
  noPast: "No past bookings yet.",
  bsPending: "Requested",
  bsConfirmed: "Confirmed",
  bsDeclined: "Not chosen",
  bsCancelled: "Cancelled",
  kindSingle: "One date",
  kindMulti: "Several dates",
  kindRecurring: "Monthly pattern",
  anotherVenue: "Another venue was chosen for this date",
  yourNote: "Your note",
  mmNote: "Note from MicroMobility",
  cancel: "Cancel",
  cancelTitle: "Cancel this booking",
  cancelOne: "Cancel this date",
  cancelSeries: "Cancel this and all later dates of the pattern",
  cancelReason: "Reason (optional)",
  lateWarning: "This counts as a late cancellation: the date is less than {n} days away.",
  confirmCancel: "Cancel booking",
  keepIt: "Keep it",
  cancelled: "Cancelled {n} date(s).",
  cancelledOne: "Cancelled 1 date.",

  // Venue
  venueTitle: "Venue",
  venueName: "Venue name",
  planLabel: "Plan",
  profileTitle: "Venue details",
  mapUrl: "Map link",
  mapUrlHint: "A Google Maps or Apple Maps link starting with https://",
  errMapUrl: "The map link must start with https://",
  seats: "Seats",
  errSeats: "Seats must be a whole number between 1 and 2000.",
  contactName: "Contact name",
  contactPhone: "Contact mobile",
  contactEmail: "Contact email",
  offerEn: "Offer for riders (English)",
  offerAr: "Offer for riders (Arabic)",
  offerHint: "What riders get, for example a discount on breakfast.",
  tierTitle: "Your plan",
  tierRules: "How booking works",
  ruleModes: "Booking types: {list}",
  ruleMonthly: "Up to {n} dates a month",
  ruleMonthlyNone: "No monthly limit",
  ruleHorizon: "Book up to {n} days ahead",
  ruleLead: "Requests need {n} days' notice",
  ruleCutoff: "Cancelling a confirmed date less than {n} days before counts as late",
  benefitsTitle: "Benefits",
  benefitsSoon: "Benefits will be announced soon.",
  listSep: ", ",
};

export type Key = keyof typeof en;

const ar: Record<Key, string> = {
  appName: "شركاء مايكروموبيليتي",
  appTagline: "شركاء الفطور لجولة السبت الاجتماعية",
  langSwitch: "English",
  langSwitchLabel: "التبديل إلى الإنجليزية",
  signOut: "تسجيل الخروج",
  loading: "جارٍ التحميل…",
  retry: "حاول مرة أخرى",
  close: "إغلاق",
  back: "رجوع",
  save: "حفظ",
  saved: "تم الحفظ.",

  signInTitle: "تسجيل الدخول",
  signInIntro: "احجز أيام السبت التي يأتيك فيها الدرّاجون للفطور.",
  loginLabel: "البريد الإلكتروني أو رقم الجوال",
  passwordLabel: "كلمة المرور",
  signInButton: "دخول",
  signingIn: "جارٍ الدخول…",
  showPassword: "إظهار كلمة المرور",
  hidePassword: "إخفاء كلمة المرور",
  noAccount: "تنشئ مايكروموبيليتي حسابات الشركاء. للحصول على حساب، تواصل معنا.",
  errBadLogin: "البريد الإلكتروني أو رقم الجوال أو كلمة المرور غير صحيحة.",
  errLocked: "محاولات كثيرة. أوقفنا الدخول مؤقتًا لحمايتك؛ حاول مرة أخرى بعد 15 دقيقة.",
  errRateLimit: "محاولات كثيرة من هذا الاتصال. انتظر دقيقة ثم حاول مرة أخرى.",
  errNetwork: "تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى.",
  errServer: "حدث خطأ من جهتنا. حاول مرة أخرى بعد قليل.",
  errInput: "بعض البيانات غير صحيحة. راجعها وحاول مرة أخرى.",
  errSession: "انتهت جلستك. سجّل الدخول مرة أخرى.",

  forceTitle: "اختر كلمة مرور خاصة بك",
  forceIntro: "دخلت بكلمة مرور مؤقتة. اختر كلمة مرور جديدة للمتابعة.",
  newPassword: "كلمة المرور الجديدة",
  confirmPassword: "تأكيد كلمة المرور الجديدة",
  currentPassword: "كلمة المرور الحالية",
  pwRules: "8 أحرف على الأقل، منها حرف إنجليزي كبير ورقم.",
  pwRuleLength: "8 أحرف على الأقل",
  pwRuleCapital: "حرف إنجليزي كبير (A-Z)",
  pwRuleNumber: "رقم واحد (0-9)",
  pwMismatch: "كلمتا المرور غير متطابقتين.",
  errWeak: "كلمة المرور ضعيفة. اتبع الشروط أدناه.",
  errSame: "يجب أن تختلف كلمة المرور الجديدة عن الحالية.",
  errBadPassword: "كلمة المرور الحالية غير صحيحة.",
  pwSaveButton: "حفظ كلمة المرور",
  pwChanged: "تم تغيير كلمة المرور، وسُجّل الخروج من الأجهزة الأخرى.",
  changePasswordTitle: "تغيير كلمة المرور",

  navCalendar: "التقويم",
  navBookings: "حجوزاتي",
  navVenue: "المنشأة",
  mainNav: "القائمة الرئيسية",

  calendarTitle: "تقويم الفطور",
  calendarIntro: "أيام السبت المتاحة للفطور بعد الجولة الاجتماعية. اضغط على تاريخ متاح لطلبه.",
  prevMonth: "الشهر السابق",
  nextMonth: "الشهر التالي",
  today: "اليوم",
  bookButton: "طلب تواريخ",
  legend: "دليل الألوان",
  stAvailable: "متاح",
  stRequested: "مطلوب",
  stConfirmed: "مؤكد",
  stTaken: "محجوز",
  stClosed: "مغلق",
  stNotOpen: "غير متاح",
  stPast: "انتهى",
  stSoon: "قريب جدًا",
  stFar: "بعيد جدًا",
  requestThis: "اطلبه",
  ridersBooked: "{n} درّاج مسجّل",
  oneRiderBooked: "درّاج واحد مسجّل",
  closedReason: "مغلق: {reason}",
  noDatesMonth: "لا توجد تواريخ متاحة للفطور في هذا الشهر.",
  weekdaysShort: "أحد,إثنين,ثلاثاء,أربعاء,خميس,جمعة,سبت",

  bookTitle: "طلب تواريخ الفطور",
  modeLabel: "كيف تريد الحجز؟",
  modeSingle: "تاريخ واحد",
  modeMulti: "عدة تواريخ",
  modeRecurring: "تكرار شهري",
  modeOffSingle: "باقتك لا تشمل حجز تاريخ واحد.",
  modeOffMulti: "باقتك تتيح حجز تاريخ واحد في كل مرة.",
  modeOffRecurring: "باقتك لا تشمل التكرار الشهري.",
  pickDate: "التاريخ",
  pickDates: "اضغط على التواريخ المتاحة التي تريدها",
  chosenDates: "التواريخ المختارة",
  noneChosen: "لم تختر أي تاريخ بعد.",
  removeDate: "إزالة {date}",
  noAvailable: "لا توجد تواريخ متاحة ضمن فترة الحجز حاليًا.",
  every: "كل",
  saturdayOf: "سبت من الشهر،",
  everyN: "كل",
  monthsUnit: "شهر،",
  from: "من",
  until: "حتى",
  ord1: "أول",
  ord2: "ثاني",
  ord3: "ثالث",
  ord4: "رابع",
  ordLast: "آخر",
  noteLabel: "ملاحظة لمايكروموبيليتي (اختياري)",
  noteHint: "متبقٍ {n} حرفًا",
  previewButton: "تحقق من التواريخ",
  checking: "جارٍ التحقق…",
  previewTitle: "قبل الإرسال",
  previewSummary: "يمكن طلب {ok} من أصل {all} تواريخ.",
  previewNone: "لا يمكن طلب أي من هذه التواريخ.",
  previewEmpty: "لا يوجد سبت ضمن فترة الحجز لهذا التكرار.",
  sendButton: "إرسال الطلب",
  sending: "جارٍ الإرسال…",
  editChoice: "تعديل",
  resultTitle: "تم إرسال الطلب",
  resultBody: "طلبت {n} تواريخ. ستؤكد مايكروموبيليتي الحجز؛ قد تطلب عدة منشآت التاريخ نفسه ونختار إحداها.",
  resultBodyOne: "طلبت تاريخًا واحدًا. ستؤكد مايكروموبيليتي الحجز؛ قد تطلب عدة منشآت التاريخ نفسه ونختار إحداها.",
  resultNone: "لم يُطلب أي تاريخ: لم يعد أيٌّ منها متاحًا.",
  done: "تم",
  vOk: "متاح",
  vTaken: "حجزته منشأة أخرى",
  vClosed: "مغلق: {reason}",
  vClosedNoReason: "مغلق",
  rsRamadan: "رمضان",
  rsEid: "العيد",
  rsWeather: "الطقس",
  rsHoliday: "إجازة رسمية",
  vNotOpen: "غير متاح للفطور",
  vTooSoon: "يحتاج إشعارًا مسبقًا بـ {n} أيام",
  vTooFar: "بعيد جدًا",
  vMine: "سبق أن طلبت هذا التاريخ",
  vOverQuota: "يتجاوز الحد الشهري لباقتك ({n})",
  vNotAllowed: "غير مشمول في باقتك",
  errOneDate: "اختر تاريخًا واحدًا.",
  errChooseDates: "اختر تاريخًا واحدًا على الأقل.",
  errTooMany: "عدد التواريخ كبير جدًا (60 كحد أقصى).",
  errPattern: "أكمل الجملة: أي سبت، وكل كم شهر، ومن متى وحتى متى.",

  bookingsTitle: "حجوزاتي",
  upcoming: "القادمة",
  past: "السابقة",
  noUpcoming: "لا توجد حجوزات قادمة. افتح التقويم لطلب تاريخ.",
  noPast: "لا توجد حجوزات سابقة بعد.",
  bsPending: "مطلوب",
  bsConfirmed: "مؤكد",
  bsDeclined: "لم يتم اختياره",
  bsCancelled: "ملغى",
  kindSingle: "تاريخ واحد",
  kindMulti: "عدة تواريخ",
  kindRecurring: "تكرار شهري",
  anotherVenue: "اختيرت منشأة أخرى لهذا التاريخ",
  yourNote: "ملاحظتك",
  mmNote: "ملاحظة من مايكروموبيليتي",
  cancel: "إلغاء",
  cancelTitle: "إلغاء الحجز",
  cancelOne: "إلغاء هذا التاريخ",
  cancelSeries: "إلغاء هذا التاريخ وكل التواريخ اللاحقة من التكرار",
  cancelReason: "السبب (اختياري)",
  lateWarning: "يُحتسب هذا إلغاءً متأخرًا: بقي على التاريخ أقل من {n} أيام.",
  confirmCancel: "إلغاء الحجز",
  keepIt: "الإبقاء عليه",
  cancelled: "أُلغي {n} تاريخ.",
  cancelledOne: "أُلغي تاريخ واحد.",

  venueTitle: "المنشأة",
  venueName: "اسم المنشأة",
  planLabel: "الباقة",
  profileTitle: "بيانات المنشأة",
  mapUrl: "رابط الموقع",
  mapUrlHint: "رابط من خرائط Google أو Apple يبدأ بـ \u2066https://\u2069",
  errMapUrl: "يجب أن يبدأ رابط الموقع بـ \u2066https://\u2069",
  seats: "عدد المقاعد",
  errSeats: "عدد المقاعد رقم صحيح بين 1 و2000.",
  contactName: "اسم المسؤول",
  contactPhone: "جوال المسؤول",
  contactEmail: "بريد المسؤول",
  offerEn: "العرض للدرّاجين (بالإنجليزية)",
  offerAr: "العرض للدرّاجين (بالعربية)",
  offerHint: "ما يحصل عليه الدرّاجون، مثل خصم على الفطور.",
  tierTitle: "باقتك",
  tierRules: "طريقة الحجز",
  ruleModes: "أنواع الحجز: {list}",
  ruleMonthly: "حتى {n} تواريخ في الشهر",
  ruleMonthlyNone: "بلا حد شهري",
  ruleHorizon: "الحجز مسبقًا حتى {n} يومًا",
  ruleLead: "يحتاج الطلب إشعارًا مسبقًا بـ {n} أيام",
  ruleCutoff: "إلغاء تاريخ مؤكد قبل أقل من {n} أيام يُحتسب متأخرًا",
  benefitsTitle: "المزايا",
  benefitsSoon: "سيُعلن عن المزايا قريبًا.",
  listSep: "، ",
};

export type Lang = "en" | "ar";
export const STRINGS: Record<Lang, Record<Key, string>> = { en, ar };

/** The text for key in lang, with {name} placeholders filled. */
export function fmt(lang: Lang, key: Key, vars?: Record<string, string | number>): string {
  let s = STRINGS[lang][key];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}
