// The ticket's words, in English and Arabic, exactly as the booking app writes them (its LANG en/ar
// keys named beside each); every other language translates the English (src/i18n/tx).
// queueNumber queueNumLabel · waitlist waitlistLabel · qrHold ticketQrHold · next youreNext ·
// inQueue inQueueMsg · onBike onBikeNow · underReview/confirmed/confirmedSub/pending/waitlistCue
// commCue* · riders/participants reviewRidersLabel/reviewPartLabel · paid/pendingPay/onTheHouse ·
// total reviewTotalLabel · complimentary freeLabel · calendar addToCalendarBtn · directions
// ticketDirections · meetingPoint meetPointLbl · edit/reschedule/cancel · available availLabel ·
// wlPos/wlPosNoNum wlPos(NoNum)Msg · gatherAt ticketGatherAt · collectFrom ticketCollectAt.
export const T = {
  en: {
    queueNumber: "Queue Number",
    waitlist: "Waitlist",
    qrHold: "Your code appears here once your place is confirmed.",
    next: "You're next!",
    inQueue: "You're in the queue",
    onBike: "On the bike now",
    underReview: "Reserved - the rider list is being finalised",
    confirmed: "Your spot is confirmed!",
    confirmedSub: "Show this code at the gathering point when you arrive.",
    pending: "Reserved - awaiting confirmation",
    waitlistCue: "On the waitlist - we will notify you if a spot opens",
    riders: "Riders",
    participants: "Participants",
    paid: "Paid",
    pendingPay: "Pending",
    onTheHouse: "On the house",
    total: "Total",
    complimentary: "Complimentary",
    calendar: "Add to Calendar",
    directions: "Get Directions",
    meetingPoint: "Meeting point",
    edit: "Edit",
    reschedule: "Reschedule",
    cancel: "Cancel",
    available: "Available",
    wlPosNoNum: "You are in line for a spot. We will let you know if one frees up — you can still come and ask at the booth.",
    wlPos: (n: string) => `You are W${n} in line for a spot. We will let you know if one frees up — you can still come and ask at the booth.`,
    gatherAt: (n: string) => `Gathering at ${n}`,
    collectFrom: (n: string) => `Collect bikes from ${n}`,
    route: "Route",
  },
  ar: {
    queueNumber: "رقم الطابور",
    waitlist: "قائمة الانتظار",
    qrHold: "يظهر رمزك هنا بعد تأكيد مقعدك.",
    next: "أنت التالي!",
    inQueue: "أنت في قائمة الانتظار",
    onBike: "على الدراجة الآن",
    underReview: "تم الحجز - يجري إعداد قائمة المشاركين",
    confirmed: "تم تأكيد مقعدك!",
    confirmedSub: "اعرض هذا الرمز عند الوصول إلى نقطة التجمع.",
    pending: "تم الحجز - بانتظار التأكيد",
    waitlistCue: "في قائمة الانتظار - سنعلمك إذا توفر مقعد",
    riders: "الركّاب",
    participants: "المشاركون",
    paid: "مدفوع",
    pendingPay: "معلق",
    onTheHouse: "على حساب المحل",
    total: "الإجمالي",
    complimentary: "ضيافة",
    calendar: "أضف إلى التقويم",
    directions: "الاتجاهات",
    meetingPoint: "نقطة التجمع",
    edit: "تعديل",
    reschedule: "إعادة جدولة",
    cancel: "إلغاء",
    available: "متاح",
    wlPosNoNum: "أنت في انتظار مقعد. سنخبرك إذا توفّر مقعد، ويمكنك أيضاً السؤال في الكشك.",
    wlPos: (n: string) => `أنت رقم W${n} في انتظار مقعد. سنخبرك إذا توفّر مقعد، ويمكنك أيضاً السؤال في الكشك.`,
    gatherAt: (n: string) => `التجمع في ${n}`,
    collectFrom: (n: string) => `استلام الدراجات من ${n}`,
    route: "المسار",
  },
};
