// The ticket's words, in English and Arabic, exactly as the booking app writes them (its LANG en/ar
// keys named beside each); every other language translates the English (src/i18n/tx).
// queueNumber queueNumLabel · waitlist waitlistLabel · qrHold ticketQrHold · next youreNext ·
// inQueue inQueueMsg · onBike onBikeNow · underReview/confirmed/confirmedSub/pending/waitlistCue
// commCue* · riders/participants reviewRidersLabel/reviewPartLabel · paid/pendingPay/onTheHouse ·
// total reviewTotalLabel · calendar addToCalendarBtn · directions
// ticketDirections · meetingPoint meetPointLbl · edit/reschedule/cancel · available availLabel ·
// wlPos/wlPosNoNum wlPos(NoNum)Msg · gatherAt ticketGatherAt · collectFrom ticketCollectAt ·
// wlOnList/wlLinePos/wlRowPos · payDue payDueLabel · payAtBooth payAtBoothLine · helmetLine/helmetBring
// tkHelmetLine/tkHelmetBring · venueCircuit evJccName · today/tomorrow mrToday/mrTomorrow ·
// bikes2/bikesN · free freeLabel (as of the booking app's 2026-09-30 card, bb37ba1 and 9a03c12).
export const T = {
  en: {
    queueNumber: "Queue number",
    waitlist: "Waitlist",
    wlOnList: "On the waitlist",
    wlLinePos: (n: string) => `number ${n} in line`,
    wlRowPos: (n: string) => `In line: ${n}`,
    bikes2: "2 bikes",
    bikesN: (n: string) => `${n} bikes`,
    qrHold: "Your code appears here once your place is confirmed.",
    next: "You’re next",
    inQueue: "You're in the queue",
    onBike: "On the bike now",
    underReview: "Reserved - the rider list is being finalised",
    confirmed: "Your place is confirmed",
    confirmedSub: "Show this code at the gathering point when you arrive.",
    pending: "Reserved. Waiting for staff to confirm.",
    waitlistCue: "On the waitlist. If a place opens and staff pick you, this card turns into your ticket.",
    riders: "Riders",
    participants: "Participants",
    paid: "Paid",
    payDue: "Pay at the booth",
    onTheHouse: "On the house",
    total: "Total",
    free: "Free",
    payAtBooth: "You pay at the booth when you arrive.",
    helmetLine: "Helmets are required. One comes with every bike.",
    helmetBring: "Helmets are required: bring your own.",
    venueCircuit: "Jeddah Corniche Circuit",
    today: "Today",
    tomorrow: "Tomorrow",
    calendar: "Add to calendar",
    directions: "Get directions",
    meetingPoint: "Meeting point",
    edit: "Edit",
    reschedule: "Reschedule",
    cancel: "Cancel",
    available: "Available",
    wlPosNoNum: "You’re in line for a place. Nothing is held for you yet: if a place opens, staff check you in at the booth with this code, and they may message you on WhatsApp first.",
    wlPos: (n: string) => `You’re number ${n} in line. Nothing is held for you yet: if a place opens, staff check you in at the booth with this code, and they may message you on WhatsApp first.`,
    gatherAt: (n: string) => `Gathering at ${n}`,
    collectFrom: (n: string) => `Collect bikes from ${n}`,
    route: "Route",
    liveMap: "Live map",
    // the ride night (91816da): tkSt*, tkCue*, tkCd*, rt*
    stBooked: "Booked",
    stIn: "Checked in",
    stBike: "On the bike",
    stDone: "Done",
    cueNoBike: "Checked in. Your bike is being handed over.",
    cueBike: (n: string) => `On the bike: ${n}`,
    cueDone: (n: string) => `Ride done: ${n} on the bike.`,
    cueDoneNoDur: "Ride done.",
    cdCollect: "Bike collection in {0}",
    cdGather: "Gathering in {0}",
    cdStart: "Starts in {0}",
    durH: "{h} h",
    durHM: "{h} h {m} min",
    durM: "{m} min",
    rtLap: (n: string) => `${n} km a lap`,
    rtKm: (n: string) => `${n} km`,
    rtCircuitNote: "Flat, smooth tarmac, floodlit at night",
    rtRidden: "Ridden",
    rtMapLink: "Open the map",
    rtOsm: "Track: © OpenStreetMap contributors",
    // the breakfast stop (the booking app's breakfastSpotLbl, vndRiderOffer)
    breakfastSpot: "Breakfast spot",
    riderOffer: (n: string) => `Offer for riders: ${n}`,
  },
  ar: {
    queueNumber: "رقم الدور",
    waitlist: "قائمة الانتظار",
    wlOnList: "على قائمة الانتظار",
    wlLinePos: (n: string) => `رقم ${n} في الانتظار`,
    wlRowPos: (n: string) => `في الانتظار: ${n}`,
    bikes2: "دراجتان",
    bikesN: (n: string) => `${n} دراجات`,
    qrHold: "يظهر رمزك هنا بعد تأكيد مقعدك.",
    next: "دورك التالي",
    inQueue: "أنت في الطابور",
    onBike: "على الدراجة الآن",
    underReview: "تم الحجز - يجري إعداد قائمة المشاركين",
    confirmed: "تم تأكيد مقعدك",
    confirmedSub: "اعرض هذا الرمز عند الوصول إلى نقطة التجمع.",
    pending: "تم الحجز، بانتظار تأكيد الفريق.",
    waitlistCue: "على قائمة الانتظار. إذا توفر مقعد واختارك الفريق تتحول هذه البطاقة إلى تذكرتك.",
    riders: "الركّاب",
    participants: "المشاركون",
    paid: "مدفوع",
    payDue: "الدفع عند الكشك",
    onTheHouse: "على حسابنا",
    total: "الإجمالي",
    free: "مجاني",
    payAtBooth: "تدفع عند الكشك حين تصل.",
    helmetLine: "الخوذة إلزامية، وتأتي خوذة مع كل دراجة.",
    helmetBring: "الخوذة إلزامية: أحضر خوذتك.",
    venueCircuit: "حلبة كورنيش جدة",
    today: "اليوم",
    tomorrow: "غداً",
    calendar: "أضف إلى التقويم",
    directions: "الاتجاهات",
    meetingPoint: "نقطة التجمع",
    edit: "تعديل",
    reschedule: "إعادة جدولة",
    cancel: "إلغاء",
    available: "متاح",
    wlPosNoNum: "أنت في قائمة الانتظار. لم يُحجز لك مقعد بعد: إذا توفر مقعد يسجّل الفريق دخولك بهذا الرمز عند الكشك، وقد يراسلك عبر واتساب قبل ذلك.",
    wlPos: (n: string) => `أنت رقم ${n} في قائمة الانتظار. لم يُحجز لك مقعد بعد: إذا توفر مقعد يسجّل الفريق دخولك بهذا الرمز عند الكشك، وقد يراسلك عبر واتساب قبل ذلك.`,
    gatherAt: (n: string) => `التجمع في ${n}`,
    collectFrom: (n: string) => `استلام الدراجات من ${n}`,
    route: "المسار",
    liveMap: "الخريطة الحية",
    stBooked: "محجوز",
    stIn: "الحضور",
    stBike: "على الدراجة",
    stDone: "انتهت",
    cueNoBike: "تم تسجيل حضورك. يجري تسليمك الدراجة.",
    cueBike: (n: string) => `على الدراجة: ${n}`,
    cueDone: (n: string) => `انتهت رحلتك: ${n} على الدراجة.`,
    cueDoneNoDur: "انتهت رحلتك.",
    cdCollect: "استلام الدراجة بعد {0}",
    cdGather: "التجمع بعد {0}",
    cdStart: "تبدأ بعد {0}",
    durH: "{h} س",
    durHM: "{h} س {m} د",
    durM: "{m} د",
    rtLap: (n: string) => `${n} كم للفة`,
    rtKm: (n: string) => `${n} كم`,
    rtCircuitNote: "مسطّح وإسفلت ناعم وإضاءة ليلية",
    rtRidden: "أنجزته",
    rtMapLink: "افتح الخريطة",
    rtOsm: "الحلبة: © مساهمو OpenStreetMap",
    breakfastSpot: "موقع الفطور",
    riderOffer: (n: string) => `عرض للراكبين: ${n}`,
  },
};
