// GENERATED by scripts/sync-privacy-notice.mjs from the booking app's Privacy Notice
// (MicromobilityRentalsSystem app.src.html). Do not edit here: change it in the booking app and
// run the script again, so the two never disagree.
export type NoticeBlock = { h?: string; p?: string; ul?: string[]; table?: { head: string[]; rows: string[][] } };
export const PRIVACY_VERSION = "2026-10-07";
// The last version riders must confirm: an account that confirmed it or any later one is not asked again.
export const PRIVACY_ASK_FROM = "2026-10-07";
export const PRIVACY_NOTICE: { en: NoticeBlock[]; ar: NoticeBlock[] } = {
 "en": [
  {
   "h": "Who we are"
  },
  {
   "p": "<strong>شركة التنقل الدقيق المحدودة</strong> (Micromobility Company Ltd.), a single-person limited liability company. Unified number 7041881512 (Commercial Registration 1009107240). Building 7933, Ibn Anuq Al Fedha Street, Al Mansurah District, Riyadh 12692 (additional no. 2987), Saudi Arabia."
  },
  {
   "p": "We run bicycle rentals, group rides and events at micromobility.sa. For anything about your data, contact <a href=\"mailto:info@micromobility.sa\">info@micromobility.sa</a>."
  },
  {
   "h": "What we collect, and whether you must give it"
  },
  {
   "table": {
    "head": [
     "Data",
     "Required?",
     "What we use it for"
    ],
    "rows": [
     [
      "First and last name, mobile number, email",
      "Required",
      "Your account, your bookings, signing you in, contacting you about your rides"
     ],
     [
      "Password",
      "Required",
      "Protecting your account. It is stored scrambled and we can never read it."
     ],
     [
      "Gender",
      "Required",
      "Our rides, sessions and events can be for women only or arranged separately for men and women. We need your gender to show you which ones you can book, and to arrange suitable staff and facilities. We also count participation as anonymised totals."
     ],
     [
      "Height",
      "Required",
      "Giving you a bike that fits"
     ],
     [
      "Preferred bike type",
      "Optional",
      "Suggesting the right bike"
     ],
     [
      "Date of birth",
      "Optional for your first eight bookings, then required. Community members: required before booking, and on a membership application. On a learn-to-ride sign-up: required from the person signing up",
      "Age rules and safety, including making sure under-18s are booked by a parent or guardian; age categories for events, races and leaderboards; age-group totals; a birthday greeting from our team"
     ],
     [
      "Nationality",
      "Optional for your first eight bookings, then required. Community members: required before booking, and on a membership application. On a learn-to-ride sign-up: required from the person signing up",
      "Participation totals only, for example Saudi and non-Saudi riders. <strong>Never shared per person. Which nationality you give never decides who can book.</strong>"
     ],
     [
      "Country and city",
      "Optional",
      "Totals of where our riders come from"
     ],
     [
      "Social media handles, and the follower count of the Instagram account you give",
      "Optional; required on a community membership application, and asked on a learn-to-ride sign-up. Seen only by our staff.",
      "So our staff can get to know riders who may be invited to join our riding community. The follower count is read from Instagram, or noted by our staff, from your public profile. We never post, tag or share them."
     ],
     [
      "Profession and company",
      "Asked on a community membership application and a learn-to-ride sign-up; optional on your account page. Seen only by our staff.",
      "So our staff can get to know the riders who apply to join our riding community or sign up for a riding lesson. We never share them."
     ],
     [
      "Learn-to-ride sign-up: each learner’s name (for a child or another adult), age, gender, height and riding experience",
      "Asked only on a learn-to-ride sign-up. Seen only by our staff.",
      "Arranging the lesson, having a bike of the right size ready and teaching at the right level"
     ],
     [
      "How you heard about us",
      "Asked on a community membership application and a learn-to-ride sign-up; optional on your account page",
      "Knowing how riders find us, in totals only"
     ],
     [
      "Emergency contacts: the name, mobile number and relationship to you of someone we can call, and of a second person if you add one",
      "One is required to take part in some events, such as Run for Her; optional on your account page. A second is always optional. Seen only by our staff, and the first also by the hosts of an event you agree to share it with. Please tell each person you gave us their details.",
      "Calling someone for you if you need help during an event, and the second person if we cannot reach the first. We never contact them for anything else. We share only your first contact’s details, and only with the hosts of an event you agree to share them with."
     ],
     [
      "Bookings and rides: rides booked, when you booked, your party, check-in and return times, bike used, payments, add-ons, waiver agreement, ratings",
      "Created as you use the service",
      "Running your rides, safety, payments and records"
     ],
     [
      "Your choice about ride news, and when you made it",
      "Recorded when you choose",
      "Knowing whether we may send you ride news"
     ]
    ]
   }
  },
  {
   "h": "How we collect it"
  },
  {
   "ul": [
    "<strong>From you,</strong> when you sign up, edit your profile, book or give feedback.",
    "<strong>From the person who booked you,</strong> if someone booked you as part of their party. They give us your name and height.",
    "<strong>From our community membership application</strong> at micromobility.sa/community/registration, if you apply to join our riding community. Our staff read it and reply. If you are accepted and have no account yet, we create one from those details with a temporary password, which you must change the first time you sign in.",
    "<strong>From our learn-to-ride sign-up</strong> at micromobility.sa/experiences/learn, if you sign up for a riding lesson for yourself, your children or other adults. Our staff contact you to arrange the lesson. If you have no account yet, we create one from your details with a temporary password, which you must change the first time you sign in. If you sign up another adult, tell them first and make sure they agree.",
    "<strong>From Apple or Google,</strong> if you sign in with them. They give us your name and email address, or an Apple relay address.",
    "<strong>From your device:</strong> a short technical report if the website hits an error (the error, the page and your browser type), and anonymous visit counts through Cloudflare Web Analytics, which uses no cookies."
   ]
  },
  {
   "h": "Why we use it, and on what legal basis"
  },
  {
   "ul": [
    "<strong>To provide the service you asked for</strong> (bookings, check-in, bike fitting, the ride waiver, contacting you about your rides): this is needed to carry out our agreement with you.",
    "<strong>To keep financial records:</strong> the law requires it.",
    "<strong>For anonymised totals and to improve our service:</strong> our legitimate interest. Totals never identify anyone.",
    "<strong>For optional details and ride news:</strong> your consent. You give it by filling in those fields or choosing ride news, and you can withdraw it at any time.",
    "<strong>To share a runner’s details with the hosts of Run for Her:</strong> your consent, which we ask for before you can take part in the race."
   ]
  },
  {
   "p": "<strong>We use your data only for the purposes above.</strong> If we ever want to use it for something else, we will ask you first, unless the law allows otherwise."
  },
  {
   "h": "If you don’t give us your data"
  },
  {
   "ul": [
    "<strong>Without the required details,</strong> we can’t create your account or give you a bike that fits.",
    "<strong>Without your date of birth and nationality,</strong> you can make up to eight bookings. Community members can’t book until they add them.",
    "<strong>Without the other optional details,</strong> nothing changes."
   ]
  },
  {
   "h": "Ride news and announcements"
  },
  {
   "p": "We send ride news (new rides, schedules, offers and community news) only if you choose it, when you sign up or in your profile. You can stop any time:"
  },
  {
   "ul": [
    "switch it off in your profile, or",
    "reply STOP to any WhatsApp message, or use the unsubscribe link in any email."
   ]
  },
  {
   "p": "Messages about a booking you made, such as a confirmation or a change to your ride, are part of the service and are not ride news."
  },
  {
   "h": "Who we share it with, and where it goes"
  },
  {
   "table": {
    "head": [
     "Who",
     "What they receive, and why",
     "Location"
    ],
    "rows": [
     [
      "Our staff",
      "What they need to run rides",
      "Saudi Arabia"
     ],
     [
      "Petromin",
      "The names of riders on rides we run for Petromin, and nothing else",
      "Saudi Arabia"
     ],
     [
      "Sela and Jeddah Yacht Club (JYC)",
      "For Run for Her, and only if you agree: your full name, email address, birth date, the distance you chose and your emergency contact, so you can take part in the race. Nothing else about you.",
      "Saudi Arabia"
     ],
     [
      "The restaurant or café hosting a Saturday ride breakfast",
      "Your breakfast ratings and the reasons you gave for them, only when our staff choose to share them, and never your name or anything else about you",
      "Saudi Arabia"
     ],
     [
      "Supabase",
      "Hosts our database",
      "Frankfurt, Germany (European Union)"
     ],
     [
      "Cloudflare",
      "Hosts the website and counts visits",
      "Worldwide network"
     ],
     [
      "Apple, Google",
      "Sign-in, only if you use it",
      "Outside Saudi Arabia"
     ],
     [
      "WhatsApp",
      "When we message you there",
      "Outside Saudi Arabia"
     ],
     [
      "Instagram (Meta)",
      "The Instagram handle you gave, to read that account’s public follower count, and nothing else about you",
      "Outside Saudi Arabia"
     ],
     [
      "Our error-alert service (Discord)",
      "The technical error reports",
      "Outside Saudi Arabia"
     ],
     [
      "Authorities",
      "Only when Saudi law requires it",
      "Saudi Arabia"
     ]
    ]
   }
  },
  {
   "p": "<strong>Our database is hosted in Frankfurt, Germany, in the European Union.</strong> We transfer your data there only to provide our service to you, and only the data that service needs. <strong>We do not sell your data.</strong>"
  },
  {
   "h": "How we store and protect it"
  },
  {
   "p": "Your data is kept in an electronic database, and it is encrypted while it travels between your device and our systems. Only our staff can access it, and each role sees only what it needs."
  },
  {
   "h": "How long we keep it, and how we destroy it"
  },
  {
   "ul": [
    "<strong>Account and profile:</strong> kept while you have an account, and destroyed within 30 days of your request to close it.",
    "<strong>Booking and payment records:</strong> kept for 10 years, because the law requires financial records. Then destroyed.",
    "<strong>Technical error reports:</strong> deleted after 90 days."
   ]
  },
  {
   "p": "To destroy data, we either delete it permanently from our database or remove everything that identifies you, so it can only be used in anonymous totals. Deleted data leaves our backups within 7 days."
  },
  {
   "h": "Your rights"
  },
  {
   "p": "You have the right to:"
  },
  {
   "ul": [
    "know the legal basis and purpose for collecting your data (this notice)",
    "see the data we hold about you",
    "get a copy of it in a readable, clear format",
    "have it corrected, completed or updated (most details can be edited in your profile)",
    "have data destroyed once it’s no longer needed. Records the law requires us to keep are held until that period ends.",
    "withdraw your consent at any time"
   ]
  },
  {
   "p": "To use any of these rights, email <a href=\"mailto:info@micromobility.sa\">info@micromobility.sa</a>. We will reply within 30 days. You can also complain to the Saudi Data & AI Authority (SDAIA)."
  },
  {
   "h": "Children"
  },
  {
   "p": "Riders under 18 must be booked by a parent or guardian, who provides their details and agrees to the waiver on their behalf. A child is signed up for a riding lesson by a parent or guardian, who provides the child’s details."
  },
  {
   "h": "Data breaches"
  },
  {
   "p": "If your data is leaked, lost or accessed without permission, we will inform SDAIA. We will also tell you if it could harm you or your rights."
  },
  {
   "h": "Changes"
  },
  {
   "p": "We’ll update the date at the top when this notice changes. If the purposes change, we’ll ask for your consent again."
  }
 ],
 "ar": [
  {
   "h": "من نحن"
  },
  {
   "p": "<strong>شركة التنقل الدقيق المحدودة</strong>، شركة ذات مسؤولية محدودة (شخص واحد). الرقم الموحد 7041881512 (السجل التجاري 1009107240). مبنى 7933، شارع ابن عنق الفضة، حي المنصورة، الرياض 12692 (الرقم الإضافي 2987)، المملكة العربية السعودية."
  },
  {
   "p": "نقدّم تأجير الدراجات والرحلات الجماعية والفعاليات عبر micromobility.sa. لأي استفسار يتعلق ببياناتك، راسلنا على <a href=\"mailto:info@micromobility.sa\">info@micromobility.sa</a>."
  },
  {
   "h": "البيانات التي نجمعها، وهل تقديمها إلزامي"
  },
  {
   "table": {
    "head": [
     "البيانات",
     "إلزامي؟",
     "الغرض من استخدامها"
    ],
    "rows": [
     [
      "الاسم الأول والأخير، ورقم الجوال، والبريد الإلكتروني",
      "إلزامي",
      "إنشاء حسابك وإدارة حجوزاتك وتسجيل دخولك والتواصل معك بشأن رحلاتك"
     ],
     [
      "كلمة المرور",
      "إلزامي",
      "حماية حسابك. تُحفظ بصيغة مشفّرة ولا يمكننا قراءتها إطلاقًا."
     ],
     [
      "الجنس",
      "إلزامي",
      "قد تكون بعض رحلاتنا وجلساتنا وفعالياتنا مخصّصة للنساء فقط أو منظّمة بشكل منفصل للرجال والنساء، لذا نحتاج إلى معرفة جنسك لنعرض لك ما يمكنك حجزه، ولترتيب الطاقم والمرافق المناسبة. كما نحتسب المشاركة في إحصاءات مجمّعة لا تحدد هوية أحد."
     ],
     [
      "الطول",
      "إلزامي",
      "توفير دراجة بمقاس مناسب لك"
     ],
     [
      "نوع الدراجة المفضّل",
      "اختياري",
      "اقتراح الدراجة المناسبة"
     ],
     [
      "تاريخ الميلاد",
      "اختياري في أول ثمانية حجوزات، ثم إلزامي. أعضاء المجتمع: إلزامي قبل الحجز وفي طلب العضوية. في التسجيل في دروس تعلّم الركوب: إلزامي لمن يسجّل",
      "تطبيق قواعد العمر والسلامة، ومنها التأكد من أن حجز من هم دون 18 عامًا يتم عبر أحد الوالدين أو الولي؛ وفئات الأعمار في الفعاليات والسباقات ولوحات الصدارة؛ وإحصاءات الفئات العمرية؛ وتهنئة بعيد ميلادك من فريقنا"
     ],
     [
      "الجنسية",
      "اختياري في أول ثمانية حجوزات، ثم إلزامي. أعضاء المجتمع: إلزامي قبل الحجز وفي طلب العضوية. في التسجيل في دروس تعلّم الركوب: إلزامي لمن يسجّل",
      "إحصاءات مجمّعة للمشاركة فقط، مثل أعداد الراكبين السعوديين وغير السعوديين. <strong>لا تُشارك على مستوى الأفراد إطلاقًا، ولا تحدّد الجنسية التي تذكرها من يحق له الحجز.</strong>"
     ],
     [
      "الدولة والمدينة",
      "اختياري",
      "إحصاءات مجمّعة عن أماكن قدوم راكبينا"
     ],
     [
      "حسابات التواصل الاجتماعي، وعدد متابعي حساب إنستغرام الذي تقدّمه",
      "اختياري؛ وإلزامي في طلب عضوية المجتمع، ونسأل عنها في التسجيل في دروس تعلّم الركوب. لا يطّلع عليها إلا موظفونا.",
      "ليتعرّف موظفونا على الراكبين الذين قد تتم دعوتهم للانضمام إلى مجتمع الركوب لدينا. نأخذ عدد المتابعين من إنستغرام، أو يدوّنه موظفونا، من ملفك العام. لا ننشرها ولا نشير إليها ولا نشاركها إطلاقًا."
     ],
     [
      "المهنة والشركة",
      "تُطلبان في طلب عضوية المجتمع وفي التسجيل في دروس تعلّم الركوب، وهما اختياريتان في صفحة حسابك، ولا يطّلع عليهما إلا موظفونا.",
      "ليتعرّف موظفونا على الراكبين المتقدّمين للانضمام إلى مجتمع الركوب لدينا أو المسجّلين في دروس تعلّم الركوب. لا نشاركهما إطلاقًا."
     ],
     [
      "التسجيل في دروس تعلّم الركوب: اسم كل متعلّم (للطفل أو لشخص بالغ آخر) وعمره وجنسه وطوله وخبرته في الركوب",
      "يُطلب في التسجيل في دروس تعلّم الركوب فقط، ولا يطّلع عليه إلا موظفونا.",
      "ترتيب الدرس، وتجهيز دراجة بالمقاس المناسب، والتعليم بالمستوى المناسب"
     ],
     [
      "كيف عرفت عنا",
      "يُسأل في طلب عضوية المجتمع وفي التسجيل في دروس تعلّم الركوب، وهو اختياري في صفحة حسابك",
      "معرفة كيف يصل إلينا الراكبون، في صورة أعداد إجمالية فقط"
     ],
     [
      "جهات اتصال الطوارئ: اسم شخص يمكننا الاتصال به ورقم جواله وصلة قرابته بك، وكذلك لشخص ثانٍ إن أضفته",
      "جهة واحدة مطلوبة للمشاركة في بعض الفعاليات مثل سباق نركض لأجلها، واختيارية في صفحة حسابك. والجهة الثانية اختيارية دائمًا. لا يراهما إلا موظفونا، والجهات المنظِّمة لفعالية توافق على مشاركة الأولى معها. يُرجى إبلاغ كل شخص منهما بأنك أعطيتنا بياناته.",
      "الاتصال بشخص نيابةً عنك إن احتجت إلى مساعدة أثناء إحدى الفعاليات، وبالشخص الثاني إن تعذّر الوصول إلى الأول. لا نتواصل معهما لأي غرض آخر، ولا نشارك إلا بيانات جهة الاتصال الأولى، ومع الجهات المنظِّمة لفعالية توافق على مشاركتها معها فقط."
     ],
     [
      "الحجوزات والرحلات: الرحلات المحجوزة، ووقت الحجز، ومرافقوك، وأوقات تسجيل الوصول والإرجاع، والدراجة المستخدمة، والمدفوعات، والإضافات، والموافقة على الإقرار، والتقييمات",
      "تُسجَّل أثناء استخدامك للخدمة",
      "تشغيل رحلاتك، والسلامة، والمدفوعات، والسجلات"
     ],
     [
      "اختيارك بشأن أخبار الرحلات ووقت اختيارك",
      "يُسجَّل عند اختيارك",
      "معرفة ما إذا كان يحق لنا إرسال أخبار الرحلات إليك"
     ]
    ]
   }
  },
  {
   "h": "كيف نجمعها"
  },
  {
   "ul": [
    "<strong>منك مباشرة،</strong> عند التسجيل أو تعديل ملفك الشخصي أو الحجز أو تقديم ملاحظاتك.",
    "<strong>من الشخص الذي حجز لك،</strong> إذا حجز لك أحدهم ضمن مجموعته، فيزوّدنا باسمك وطولك.",
    "<strong>من طلب عضوية المجتمع</strong> عبر micromobility.sa/community/registration، إذا تقدّمت للانضمام إلى مجتمع الركوب لدينا. يطّلع موظفونا على طلبك ويردّون عليك. وإذا قُبلت ولم يكن لديك حساب، ننشئ لك حسابًا من تلك البيانات بكلمة مرور مؤقتة، يجب عليك تغييرها عند أول تسجيل دخول.",
    "<strong>من التسجيل في دروس تعلّم الركوب</strong> عبر micromobility.sa/experiences/learn، إذا سجّلت في درس ركوب لنفسك أو لأطفالك أو لبالغين آخرين. يتواصل معك موظفونا لترتيب الدرس. وإذا لم يكن لديك حساب، ننشئ لك حسابًا من بياناتك بكلمة مرور مؤقتة يجب تغييرها عند أول تسجيل دخول. وإذا سجّلت شخصًا بالغًا آخر، فأبلغه أولًا وتأكد من موافقته.",
    "<strong>من Apple أو Google،</strong> إذا سجّلت الدخول عبرهما، فيزوّداننا باسمك وبريدك الإلكتروني أو عنوان بريد Apple البديل.",
    "<strong>من جهازك:</strong> تقرير تقني مختصر إذا واجه الموقع خطأً (الخطأ والصفحة ونوع المتصفح)، وأعداد زيارات مجهولة الهوية عبر Cloudflare Web Analytics الذي لا يستخدم ملفات تعريف الارتباط."
   ]
  },
  {
   "h": "لماذا نستخدمها، وما المسوّغ النظامي"
  },
  {
   "ul": [
    "<strong>لتقديم الخدمة التي طلبتها</strong> (الحجوزات، وتسجيل الوصول، واختيار مقاس الدراجة، وإقرار الركوب، والتواصل معك بشأن رحلاتك): وهذا لازم لتنفيذ الاتفاق بيننا وبينك.",
    "<strong>لحفظ السجلات المالية:</strong> لأن النظام يُلزمنا بذلك.",
    "<strong>للإحصاءات المجمّعة وتحسين خدماتنا:</strong> مصلحتنا المشروعة، ولا تحدد الإحصاءات هوية أحد.",
    "<strong>للبيانات الاختيارية وأخبار الرحلات:</strong> موافقتك، وتمنحها بتعبئة تلك الحقول أو باختيار أخبار الرحلات، ويمكنك سحبها في أي وقت.",
    "<strong>لمشاركة بيانات العدّاء مع الجهات المنظِّمة لسباق نركض لأجلها:</strong> موافقتك، ونطلبها منك قبل أن تتمكن من المشاركة في السباق."
   ]
  },
  {
   "p": "<strong>لا نستخدم بياناتك إلا للأغراض المذكورة أعلاه.</strong> وإذا أردنا استخدامها لغرض آخر، فسنطلب موافقتك أولًا، ما لم يُجز النظام غير ذلك."
  },
  {
   "h": "إذا لم تزوّدنا ببياناتك"
  },
  {
   "ul": [
    "<strong>دون البيانات الإلزامية</strong> لا يمكننا إنشاء حسابك أو توفير دراجة بمقاس مناسب لك.",
    "<strong>دون تاريخ الميلاد والجنسية</strong> يمكنك إجراء ثمانية حجوزات كحد أقصى، ولا يستطيع أعضاء المجتمع الحجز حتى يضيفوهما.",
    "<strong>دون البيانات الاختيارية الأخرى</strong> لا يتغيّر شيء."
   ]
  },
  {
   "h": "أخبار الرحلات والإعلانات"
  },
  {
   "p": "لا نرسل أخبار الرحلات (الرحلات الجديدة والجداول والعروض وأخبار المجتمع) إلا إذا اخترتها عند التسجيل أو من ملفك الشخصي. ويمكنك إيقافها في أي وقت:"
  },
  {
   "ul": [
    "بإيقافها من ملفك الشخصي، أو",
    "بالرد بكلمة STOP على أي رسالة واتساب، أو عبر رابط إلغاء الاشتراك في أي بريد إلكتروني."
   ]
  },
  {
   "p": "الرسائل المتعلقة بحجز قمت به، مثل التأكيد أو تغيير موعد رحلتك، جزء من الخدمة وليست من أخبار الرحلات."
  },
  {
   "h": "مع من نشاركها، وإلى أين تُنقل"
  },
  {
   "table": {
    "head": [
     "الجهة",
     "ما تتلقاه ولماذا",
     "الموقع"
    ],
    "rows": [
     [
      "موظفونا",
      "ما يحتاجونه لتشغيل الرحلات",
      "المملكة العربية السعودية"
     ],
     [
      "بترومين",
      "أسماء الراكبين في الرحلات التي ننظّمها لبترومين فقط، ولا شيء غير ذلك",
      "المملكة العربية السعودية"
     ],
     [
      "صلة ونادي جدة لليخوت (JYC)",
      "لسباق نركض لأجلها، وفقط إذا وافقت: اسمك الكامل وبريدك الإلكتروني وتاريخ ميلادك والمسافة التي اخترتها وجهة اتصالك للطوارئ، لتتمكن من المشاركة في السباق. ولا شيء غير ذلك عنك.",
      "المملكة العربية السعودية"
     ],
     [
      "المطعم أو المقهى الذي يستضيف إفطار جولة السبت",
      "تقييماتك للإفطار والأسباب التي ذكرتها لها، فقط عندما يختار موظفونا مشاركتها، ودون اسمك أو أي شيء آخر عنك",
      "المملكة العربية السعودية"
     ],
     [
      "Supabase",
      "استضافة قاعدة بياناتنا",
      "فرانكفورت، ألمانيا (الاتحاد الأوروبي)"
     ],
     [
      "Cloudflare",
      "استضافة الموقع وإحصاء الزيارات",
      "شبكة عالمية"
     ],
     [
      "Apple وGoogle",
      "تسجيل الدخول، فقط إذا استخدمته",
      "خارج المملكة العربية السعودية"
     ],
     [
      "واتساب",
      "عند مراسلتك عبره",
      "خارج المملكة العربية السعودية"
     ],
     [
      "إنستغرام (Meta)",
      "حساب إنستغرام الذي قدّمته، لقراءة عدد متابعيه العام، ولا شيء آخر عنك",
      "خارج المملكة العربية السعودية"
     ],
     [
      "خدمة تنبيهات الأخطاء لدينا (Discord)",
      "تقارير الأخطاء التقنية",
      "خارج المملكة العربية السعودية"
     ],
     [
      "الجهات الرسمية",
      "فقط عندما يوجب النظام السعودي ذلك",
      "المملكة العربية السعودية"
     ]
    ]
   }
  },
  {
   "p": "<strong>تُستضاف قاعدة بياناتنا في فرانكفورت بألمانيا، في الاتحاد الأوروبي.</strong> ولا ننقل بياناتك إليها إلا لتقديم خدمتنا لك، وبالقدر الذي تحتاجه تلك الخدمة فقط. <strong>لا نبيع بياناتك.</strong>"
  },
  {
   "h": "كيف نحفظها ونحميها"
  },
  {
   "p": "تُحفظ بياناتك في قاعدة بيانات إلكترونية، وتُشفَّر أثناء انتقالها بين جهازك وأنظمتنا. ولا يطّلع عليها إلا موظفونا، ولا يرى كل منهم إلا ما يحتاجه لعمله."
  },
  {
   "h": "مدة الاحتفاظ بها وكيفية إتلافها"
  },
  {
   "ul": [
    "<strong>الحساب والملف الشخصي:</strong> نحتفظ بهما ما دام حسابك قائمًا، ونتلفهما خلال 30 يومًا من طلبك إغلاق الحساب.",
    "<strong>سجلات الحجز والدفع:</strong> نحتفظ بها 10 سنوات لأن النظام يُلزم بحفظ السجلات المالية، ثم نتلفها.",
    "<strong>تقارير الأخطاء التقنية:</strong> تُحذف بعد 90 يومًا."
   ]
  },
  {
   "p": "لإتلاف البيانات، إما أن نحذفها نهائيًا من قاعدة بياناتنا، أو نزيل كل ما يحدد هويتك بحيث لا تُستخدم إلا في إحصاءات مجهولة الهوية. وتُزال البيانات المحذوفة من نسخنا الاحتياطية خلال 7 أيام."
  },
  {
   "h": "حقوقك"
  },
  {
   "p": "يحق لك:"
  },
  {
   "ul": [
    "العلم بالمسوّغ النظامي لجمع بياناتك والغرض منه (هذا الإشعار)",
    "الاطلاع على بياناتك المتوافرة لدينا",
    "الحصول على نسخة منها بصيغة مقروءة وواضحة",
    "طلب تصحيحها أو إكمالها أو تحديثها (ويمكنك تعديل معظمها من ملفك الشخصي)",
    "طلب إتلاف البيانات التي انتهت الحاجة إليها، مع الاحتفاظ بالسجلات التي يوجب النظام حفظها حتى انتهاء مدتها",
    "سحب موافقتك في أي وقت"
   ]
  },
  {
   "p": "لممارسة أي من هذه الحقوق، راسلنا على <a href=\"mailto:info@micromobility.sa\">info@micromobility.sa</a>، وسنرد خلال 30 يومًا. ويحق لك أيضًا تقديم شكوى إلى الهيئة السعودية للبيانات والذكاء الاصطناعي (سدايا)."
  },
  {
   "h": "الأطفال"
  },
  {
   "p": "يجب أن يتم حجز الراكبين دون 18 عامًا عبر أحد الوالدين أو الولي، الذي يقدّم بياناتهم ويوافق على الإقرار نيابةً عنهم. ويسجّل الطفلَ في درس الركوب أحدُ والديه أو وليّ أمره، ويقدّم بيانات الطفل."
  },
  {
   "h": "تسرّب البيانات"
  },
  {
   "p": "إذا تسرّبت بياناتك أو فُقدت أو تم الوصول إليها دون إذن، فسنُبلغ سدايا، وسنُبلغك أيضًا إذا كان ذلك قد يضر بك أو بحقوقك."
  },
  {
   "h": "التعديلات"
  },
  {
   "p": "سنحدّث التاريخ في أعلى الإشعار عند تعديله، وإذا تغيّرت الأغراض فسنطلب موافقتك مجددًا."
  }
 ]
};
