// Every word the portal shows, in English and Arabic. Placeholders are {name}; t() fills them.
// Arabic is written for venue owners in Saudi Arabia: plain, polite, and with Western digits
// (the numbers themselves are formatted elsewhere with -nu-latn).

const en = {
  appName: "MicroMobility Vendors",
  appTagline: "Breakfast vendors for the Saturday social ride",
  langSwitch: "العربية",
  langSwitchLabel: "Switch to Arabic",
  portalName: "Vendor portal",
  homeLink: "MicroMobility Vendors, home",
  footerEmail: "Email",
  footerWebsite: "Website",
  footerRights: "All Rights Reserved",
  signOut: "Sign out",
  loading: "Loading…",
  retry: "Try again",
  close: "Close",
  back: "Back",
  save: "Save",
  saved: "Saved.",

  // Sign in
  signInTitle: "Sign in",
  signInIntro: "Reserve the Saturdays our riders come to you for breakfast.",
  loginLabel: "Email or mobile number",
  passwordLabel: "Password",
  signInButton: "Sign in",
  signingIn: "Signing in…",
  showPassword: "Show password",
  hidePassword: "Hide password",
  noAccount: "Accounts are created by MicroMobility. To get one, contact us.",
  errBadLogin: "That email, mobile number or password is not right.",
  errLocked: "Too many tries. For your safety, sign-in is paused; try again in 15 minutes.",
  errRateLimit: "Too many tries from this connection. Wait a minute and try again.",
  errNetwork: "We could not reach the server. Check your connection and try again.",
  errServer: "Something went wrong on our side. Try again in a moment.",
  errInput: "Some of the details are not valid. Check them and try again.",
  errSession: "Your session has ended. Please sign in again.",

  // Passwords
  forceTitle: "Choose your own password",
  forceIntro: "You signed in with a temporary password. Choose a new one to continue.",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  currentPassword: "Current password",
  pwRules: "At least 10 characters. A short sentence you will remember works well; no symbols needed.",
  pwRuleLength: "At least 10 characters",
  pwMismatch: "The two passwords do not match.",
  errWeak: "This password is too short: use at least 10 characters.",
  errSame: "The new password must be different from the current one.",
  errBadPassword: "The current password is not right.",
  pwSaveButton: "Save password",
  pwChanged: "Password changed. Other devices have been signed out.",
  changePasswordTitle: "Change password",

  // Navigation
  navCalendar: "Calendar",
  navBookings: "My bookings",
  navVenue: "Venue",
  mainNav: "Main",

  // Calendar
  calendarTitle: "Breakfast calendar",
  calendarIntro: "Saturdays open for breakfast after the social ride. Tap an available date to request it.",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  today: "Today",
  bookButton: "Request dates",
  legend: "Key",
  stAvailable: "Available",
  stRequested: "Requested",
  stConfirmed: "Confirmed",
  stTaken: "Taken",
  stClosed: "Closed",
  stNotOpen: "Not open",
  stPast: "Past",
  stSoon: "Too soon",
  stFar: "Too far ahead",
  requestThis: "Request",
  closedReason: "Closed: {reason}",
  noDatesMonth: "No dates are open for breakfast this month.",
  weekdaysShort: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",

  // Booking dialog
  bookTitle: "Request breakfast dates",
  modeLabel: "How would you like to book?",
  modeSingle: "One date",
  modeMulti: "Several dates",
  modeRecurring: "Repeat monthly",
  modeOffSingle: "Your plan does not include single dates.",
  modeOffMulti: "Your plan books one date at a time.",
  modeOffRecurring: "Your plan does not include monthly repeats.",
  pickDate: "Date",
  pickDates: "Tap the available dates you want",
  chosenDates: "Chosen dates",
  noneChosen: "No dates chosen yet.",
  removeDate: "Remove {date}",
  noAvailable: "There are no available dates in your booking window right now.",
  every: "Every",
  saturdayOf: "Saturday,",
  everyN: "every",
  monthsUnit: "month(s),",
  from: "from",
  until: "until",
  ord1: "first",
  ord2: "second",
  ord3: "third",
  ord4: "fourth",
  ordLast: "last",
  noteLabel: "Note for MicroMobility (optional)",
  previewButton: "Check dates",
  checking: "Checking…",
  previewTitle: "Before you send",
  previewNone: "None of these dates can be requested.",
  previewEmpty: "This pattern has no Saturdays in your booking window.",
  sendButton: "Send request",
  sending: "Sending…",
  editChoice: "Change",
  resultTitle: "Request sent",
  resultNone: "No dates were requested: none of them were free any more.",
  done: "Done",
  vOk: "Free",
  vTaken: "Another venue has this date",
  vClosed: "Closed: {reason}",
  vClosedNoReason: "Closed",
  rsRamadan: "Ramadan",
  rsEid: "Eid",
  rsWeather: "Weather",
  rsHoliday: "Holiday",
  vNotOpen: "Not open for breakfast",
  vTooSoon: "Notice needed: {days}",
  vTooFar: "Too far ahead",
  vMine: "You already asked for this date",
  vOverQuota: "Over your plan's monthly limit ({n})",
  vNotAllowed: "Not in your plan",
  errOneDate: "Choose one date.",
  errChooseDates: "Choose at least one date.",
  errTooMany: "That is too many dates at once (60 at most).",
  errPattern: "Complete the sentence: which Saturday, how often, from and until.",

  // My bookings
  bookingsTitle: "My bookings",
  upcoming: "Upcoming",
  past: "Past",
  noUpcoming: "No upcoming bookings. Open the calendar to request a date.",
  noPast: "No past bookings yet.",
  bsPending: "Requested",
  bsConfirmed: "Confirmed",
  bsDeclined: "Not chosen",
  bsCancelled: "Cancelled",
  kindSingle: "One date",
  kindMulti: "Several dates",
  kindRecurring: "Monthly pattern",
  anotherVenue: "Another venue was chosen for this date",
  yourNote: "Your note",
  mmNote: "Note from MicroMobility",
  cancel: "Cancel",
  cancelTitle: "Cancel this booking",
  cancelOne: "Cancel this date",
  cancelSeries: "Cancel this and all later dates of the pattern",
  cancelReason: "Reason (optional)",
  lateWarning: "This counts as a late cancellation: the date is less than {days} away.",
  confirmCancel: "Cancel booking",
  keepIt: "Keep it",

  // Feedback after a breakfast
  fbHowDidItGo: "How did it go?",
  fbEdit: "Edit feedback",
  fbTitle: "Breakfast feedback",
  fbRatingLabel: "Overall, how did it go?",
  fbRate1: "1 – Poor",
  fbRate2: "2 – Fair",
  fbRate3: "3 – Good",
  fbRate4: "4 – Very good",
  fbRate5: "5 – Excellent",
  fbNoRating: "No rating chosen yet.",
  fbTurnout: "How many riders came?",
  fbOptional: "Optional.",
  fbWentWell: "What went well?",
  fbImprove: "What could we do better?",
  fbEditWindow: "You can edit your feedback for 14 days after the breakfast.",
  fbSend: "Send feedback",
  fbSaveChanges: "Save changes",
  fbThanks: "Thank you. Your feedback goes to the MicroMobility team.",
  fbYourRating: "Your rating: {rating}",
  fbRidersCame: "Riders who came: {n}",
  fbMarker: "Feedback",
  fbWaiting: "waiting for your feedback",
  srTitle: "What riders said",
  srScore: "{label} {score} / 10",
  srBreakfast: "Breakfast overall",
  srRestaurant: "Restaurant",
  srAtmosphere: "Atmosphere",
  srFood: "Food",
  srService: "Service",
  srOther: "Other comments",
  srAnonymous: "Shared by MicroMobility, without riders' names.",
  errRating: "Choose a rating from 1 to 5.",
  errTurnout: "Enter a whole number from 0 to 1000, or leave it empty.",
  errTooLate: "Feedback for this breakfast has closed.",
  errTooEarly: "Feedback opens on the day of the breakfast.",
  errNotConfirmed: "Feedback is only for confirmed breakfasts.",
  errNotFound: "We could not find this booking. Refresh the page and try again.",

  // Venue
  venueTitle: "Venue",
  venueName: "Venue name",
  planLabel: "Plan",
  profileTitle: "Venue details",
  mapUrl: "Map link",
  mapUrlHint: "A Google Maps or Apple Maps link starting with https://",
  errMapUrl: "The map link must start with https://",
  seats: "Seats",
  errSeats: "Seats must be a whole number between 1 and 2000.",
  contactName: "Contact name",
  contactPhone: "Contact mobile",
  contactEmail: "Contact email",
  offerEn: "Offer for riders (English)",
  offerAr: "Offer for riders (Arabic)",
  offerHint: "What riders get, for example a discount on breakfast.",
  tierTitle: "Your plan",
  tierRules: "How booking works",
  ruleModes: "Booking types: {list}",
  ruleMonthlyNone: "No monthly limit",
  ruleHorizon: "Book up to {days} ahead",
  ruleLead: "Notice needed for a request: {days}",
  ruleCutoff: "Cancelling a confirmed date less than {days} before counts as late",
  benefitsTitle: "Benefits",
  benefitsSoon: "Benefits will be announced soon.",
  // 2026-10-04 audit
  forgotPassword: "Forgot your password?",
  forgotIntro: "Ask MicroMobility for a new temporary password:",
  forgotWhatsApp: "WhatsApp",
  forgotEmail: "Email",
  forgotSubject: "Vendor portal: a new password",
  forgotBody: "Hello MicroMobility,\n\nPlease send me a new temporary password for the vendor portal.\nMy login: {login}\n\nThank you.",
  errMustChange: "Choose your own password first: the temporary one only lets you change it.",
  errTempExpired: "This temporary password has expired (they last 72 hours). Ask MicroMobility for a new one.",
  errForbidden: "Your login cannot do this. Ask the venue's owner.",
  errLateReason: "This breakfast is less than 48 hours away: tell us why you are cancelling.",
  errCommon: "This password is too common. Try a short sentence or a few unrelated words.",
  errPersonal: "Don't use your login, mobile number or the venue's name in your password.",
  errPhone: "Enter a mobile number, for example 05XXXXXXXX or +966 5X XXX XXXX.",
  errEmail: "Enter an email address such as name@example.com.",
  errTooLong: "That is too long. Shorten it and try again.",
  errContactName: "The contact name can be up to 120 characters.",
  pwRuleCommon: "Not a common password",
  pwRulePersonal: "Not your login, mobile or the venue's name",
  securityTitle: "Signed-in devices",
  securityIntro: "Sign out every other phone or computer using this login, for example after a staff change.",
  signedInOn: "Devices signed in now: {n}",
  signOutOthers: "Sign out other devices",
  signedOutOthers: "Other devices signed out: {n}.",
  navInsights: "Insights",
  navTeam: "Team",
  stDeclined: "Not chosen",
  stCancelled: "Cancelled",
  nextOpen: "Next open Saturdays",
  resultAfter: "MicroMobility will confirm; several venues may ask for the same date and we choose one.",
  preselectGone: "The date you picked ({date}) is no longer available. Choose another date.",
  decideBy: "MicroMobility answers by {date}.",
  briefTitle: "Breakfast brief",
  briefTimes: "Riders gather at {gather}; the ride starts at {start}.",
  briefArrive: "Expected at your venue: about {from} to {to}.",
  briefNoTime: "The ride times are not set yet. We will tell you.",
  briefContact: "MicroMobility on the day:",
  briefOffer: "Your offer for riders:",
  briefNoOffer: "No offer yet. Riders see it when you add one on the Venue page.",
  callLabel: "Call",
  lateMark: "Late cancellation",
  cancelledByMm: "Cancelled by MicroMobility",
  cancelReasonRequired: "Reason (required)",
  late48: "This breakfast is less than 48 hours away. You can still cancel, but tell us why: late cancellations are recorded, because riders are already planning to come.",
  cancelPolicy: "Cancellation policy: cancel a confirmed breakfast at least 48 hours before the day whenever you can. Inside 48 hours a reason is required and the cancellation is recorded as late.",
  readOnlyNote: "Your login can view the bookings. Ask the venue's owner or manager to request or cancel dates.",
  insightsTitle: "Insights",
  insIntro: "Your last year with MicroMobility's Saturday riders.",
  insHosted: "Breakfasts hosted",
  insUpcoming: "Confirmed and coming up",
  insShared: "Riders' breakfast score",
  insSharedSub: "Average of the last {n} shared by MicroMobility",
  insSharedNone: "No ratings shared yet",
  insOwn: "Your own ratings",
  insOwnSub: "Average of your feedback ({n})",
  insOwnNone: "No feedback given yet",
  insRecentTitle: "Riders booked and riders who came",
  insRecentNone: "No breakfasts hosted yet.",
  insBooked: "Booked",
  insCame: "Came",
  insNotSaid: "Not given",
  insDate: "Date",
  insOutOf10: "{score} / 10",
  insOutOf5: "{score} / 5",
  teamTitle: "Team",
  teamIntro: "Everyone who can sign in for {venue}. MicroMobility adds and removes logins: contact us for a change.",
  teamLogin: "Login",
  teamName: "Name",
  teamRole: "Role",
  teamStatus: "Status",
  teamLast: "Last sign-in",
  teamNever: "Never",
  teamYou: "(you)",
  teamActive: "Active",
  teamOff: "Off",
  roleOwner: "Owner",
  roleManager: "Manager",
  roleViewer: "Viewer (read only)",
  roleLine: "Your role: {role}",
  privacyLink: "Privacy notice",
  profileReadOnly: "Only the venue's owner can change these details.",
  listSep: ", ",
};

export type Key = keyof typeof en;

const ar: Record<Key, string> = {
  appName: "موردو مايكروموبيليتي",
  appTagline: "موردو الفطور لجولة السبت الاجتماعية",
  langSwitch: "English",
  langSwitchLabel: "التبديل إلى الإنجليزية",
  portalName: "بوابة الموردين",
  homeLink: "موردو مايكروموبيليتي، الرئيسية",
  footerEmail: "البريد",
  footerWebsite: "الموقع",
  footerRights: "جميع الحقوق محفوظة.",
  signOut: "تسجيل الخروج",
  loading: "جارٍ التحميل…",
  retry: "حاول مرة أخرى",
  close: "إغلاق",
  back: "رجوع",
  save: "حفظ",
  saved: "تم الحفظ.",

  signInTitle: "تسجيل الدخول",
  signInIntro: "احجز أيام السبت التي يأتيك فيها الدرّاجون للفطور.",
  loginLabel: "البريد الإلكتروني أو رقم الجوال",
  passwordLabel: "كلمة المرور",
  signInButton: "دخول",
  signingIn: "جارٍ الدخول…",
  showPassword: "إظهار كلمة المرور",
  hidePassword: "إخفاء كلمة المرور",
  noAccount: "تنشئ مايكروموبيليتي حسابات الموردين. للحصول على حساب، تواصل معنا.",
  errBadLogin: "البريد الإلكتروني أو رقم الجوال أو كلمة المرور غير صحيحة.",
  errLocked: "محاولات كثيرة. أوقفنا الدخول مؤقتًا لحمايتك؛ حاول مرة أخرى بعد 15 دقيقة.",
  errRateLimit: "محاولات كثيرة من هذا الاتصال. انتظر دقيقة ثم حاول مرة أخرى.",
  errNetwork: "تعذّر الوصول إلى الخادم. تحقق من اتصالك وحاول مرة أخرى.",
  errServer: "حدث خطأ من جهتنا. حاول مرة أخرى بعد قليل.",
  errInput: "بعض البيانات غير صحيحة. راجعها وحاول مرة أخرى.",
  errSession: "انتهت جلستك. سجّل الدخول مرة أخرى.",

  forceTitle: "اختر كلمة مرور خاصة بك",
  forceIntro: "دخلت بكلمة مرور مؤقتة. اختر كلمة مرور جديدة للمتابعة.",
  newPassword: "كلمة المرور الجديدة",
  confirmPassword: "تأكيد كلمة المرور الجديدة",
  currentPassword: "كلمة المرور الحالية",
  pwRules: "10 أحرف على الأقل. تصلح جملة قصيرة تتذكرها؛ لا حاجة إلى رموز.",
  pwRuleLength: "10 أحرف على الأقل",
  pwMismatch: "كلمتا المرور غير متطابقتين.",
  errWeak: "كلمة المرور قصيرة: استخدم 10 أحرف على الأقل.",
  errSame: "يجب أن تختلف كلمة المرور الجديدة عن الحالية.",
  errBadPassword: "كلمة المرور الحالية غير صحيحة.",
  pwSaveButton: "حفظ كلمة المرور",
  pwChanged: "تم تغيير كلمة المرور، وسُجّل الخروج من الأجهزة الأخرى.",
  changePasswordTitle: "تغيير كلمة المرور",

  navCalendar: "التقويم",
  navBookings: "حجوزاتي",
  navVenue: "المنشأة",
  mainNav: "القائمة الرئيسية",

  calendarTitle: "تقويم الفطور",
  calendarIntro: "أيام السبت المتاحة للفطور بعد الجولة الاجتماعية. اضغط على تاريخ متاح لطلبه.",
  prevMonth: "الشهر السابق",
  nextMonth: "الشهر التالي",
  today: "اليوم",
  bookButton: "طلب تواريخ",
  legend: "دليل الألوان",
  stAvailable: "متاح",
  stRequested: "مطلوب",
  stConfirmed: "مؤكد",
  stTaken: "محجوز",
  stClosed: "مغلق",
  stNotOpen: "غير متاح",
  stPast: "انتهى",
  stSoon: "قريب جدًا",
  stFar: "بعيد جدًا",
  requestThis: "اطلبه",
  closedReason: "مغلق: {reason}",
  noDatesMonth: "لا توجد تواريخ متاحة للفطور في هذا الشهر.",
  weekdaysShort: "أحد,إثنين,ثلاثاء,أربعاء,خميس,جمعة,سبت",

  bookTitle: "طلب تواريخ الفطور",
  modeLabel: "كيف تريد الحجز؟",
  modeSingle: "تاريخ واحد",
  modeMulti: "عدة تواريخ",
  modeRecurring: "تكرار شهري",
  modeOffSingle: "باقتك لا تشمل حجز تاريخ واحد.",
  modeOffMulti: "باقتك تتيح حجز تاريخ واحد في كل مرة.",
  modeOffRecurring: "باقتك لا تشمل التكرار الشهري.",
  pickDate: "التاريخ",
  pickDates: "اضغط على التواريخ المتاحة التي تريدها",
  chosenDates: "التواريخ المختارة",
  noneChosen: "لم تختر أي تاريخ بعد.",
  removeDate: "إزالة {date}",
  noAvailable: "لا توجد تواريخ متاحة ضمن فترة الحجز حاليًا.",
  every: "كل",
  saturdayOf: "سبت من الشهر،",
  everyN: "كل",
  monthsUnit: "شهر،",
  from: "من",
  until: "حتى",
  ord1: "أول",
  ord2: "ثاني",
  ord3: "ثالث",
  ord4: "رابع",
  ordLast: "آخر",
  noteLabel: "ملاحظة لمايكروموبيليتي (اختياري)",
  previewButton: "تحقق من التواريخ",
  checking: "جارٍ التحقق…",
  previewTitle: "قبل الإرسال",
  previewNone: "لا يمكن طلب أي من هذه التواريخ.",
  previewEmpty: "لا يوجد سبت ضمن فترة الحجز لهذا التكرار.",
  sendButton: "إرسال الطلب",
  sending: "جارٍ الإرسال…",
  editChoice: "تعديل",
  resultTitle: "تم إرسال الطلب",
  resultNone: "لم يُطلب أي تاريخ: لم يعد أيٌّ منها متاحًا.",
  done: "تم",
  vOk: "متاح",
  vTaken: "حجزته منشأة أخرى",
  vClosed: "مغلق: {reason}",
  vClosedNoReason: "مغلق",
  rsRamadan: "رمضان",
  rsEid: "العيد",
  rsWeather: "الطقس",
  rsHoliday: "إجازة رسمية",
  vNotOpen: "غير متاح للفطور",
  vTooSoon: "المهلة المطلوبة: {days}",
  vTooFar: "بعيد جدًا",
  vMine: "سبق أن طلبت هذا التاريخ",
  vOverQuota: "يتجاوز الحد الشهري لباقتك ({n})",
  vNotAllowed: "غير مشمول في باقتك",
  errOneDate: "اختر تاريخًا واحدًا.",
  errChooseDates: "اختر تاريخًا واحدًا على الأقل.",
  errTooMany: "عدد التواريخ كبير جدًا (60 كحد أقصى).",
  errPattern: "أكمل الجملة: أي سبت، وكل كم شهر، ومن متى وحتى متى.",

  bookingsTitle: "حجوزاتي",
  upcoming: "القادمة",
  past: "السابقة",
  noUpcoming: "لا توجد حجوزات قادمة. افتح التقويم لطلب تاريخ.",
  noPast: "لا توجد حجوزات سابقة بعد.",
  bsPending: "مطلوب",
  bsConfirmed: "مؤكد",
  bsDeclined: "لم يتم اختياره",
  bsCancelled: "ملغى",
  kindSingle: "تاريخ واحد",
  kindMulti: "عدة تواريخ",
  kindRecurring: "تكرار شهري",
  anotherVenue: "اختيرت منشأة أخرى لهذا التاريخ",
  yourNote: "ملاحظتك",
  mmNote: "ملاحظة من مايكروموبيليتي",
  cancel: "إلغاء",
  cancelTitle: "إلغاء الحجز",
  cancelOne: "إلغاء هذا التاريخ",
  cancelSeries: "إلغاء هذا التاريخ وكل التواريخ اللاحقة من التكرار",
  cancelReason: "السبب (اختياري)",
  lateWarning: "يُحتسب هذا إلغاءً متأخرًا: المدة المتبقية على التاريخ أقل من: {days}.",
  confirmCancel: "إلغاء الحجز",
  keepIt: "الإبقاء عليه",

  fbHowDidItGo: "كيف كانت التجربة؟",
  fbEdit: "تعديل الملاحظات",
  fbTitle: "ملاحظاتك عن الفطور",
  fbRatingLabel: "بشكل عام، كيف كانت التجربة؟",
  fbRate1: "1 – ضعيف",
  fbRate2: "2 – مقبول",
  fbRate3: "3 – جيد",
  fbRate4: "4 – جيد جدًا",
  fbRate5: "5 – ممتاز",
  fbNoRating: "لم تختر تقييمًا بعد.",
  fbTurnout: "كم عدد الدرّاجين الذين حضروا؟",
  fbOptional: "اختياري.",
  fbWentWell: "ما الذي كان جيدًا؟",
  fbImprove: "ما الذي يمكننا تحسينه؟",
  fbEditWindow: "يمكنك تعديل ملاحظاتك خلال 14 يومًا من موعد الفطور.",
  fbSend: "إرسال الملاحظات",
  fbSaveChanges: "حفظ التعديلات",
  fbThanks: "شكرًا لك. تصل ملاحظاتك إلى فريق مايكروموبيليتي.",
  fbYourRating: "تقييمك: {rating}",
  fbRidersCame: "عدد الدرّاجين الحاضرين: {n}",
  fbMarker: "ملاحظات",
  fbWaiting: "بانتظار ملاحظاتك",
  srTitle: "ماذا قال الدرّاجون",
  srScore: "{label} {score} / 10",
  srBreakfast: "الفطور بشكل عام",
  srRestaurant: "المطعم",
  srAtmosphere: "الأجواء",
  srFood: "الطعام",
  srService: "الخدمة",
  srOther: "تعليقات أخرى",
  srAnonymous: "شاركتها مايكروموبيليتي دون أسماء الدرّاجين.",
  errRating: "اختر تقييمًا من 1 إلى 5.",
  errTurnout: "أدخل رقمًا صحيحًا من 0 إلى 1000، أو اترك الحقل فارغًا.",
  errTooLate: "انتهت مدة إرسال الملاحظات لهذا الفطور.",
  errTooEarly: "تُتاح الملاحظات ابتداءً من يوم الفطور.",
  errNotConfirmed: "الملاحظات متاحة للحجوزات المؤكدة فقط.",
  errNotFound: "تعذّر العثور على هذا الحجز. حدّث الصفحة وحاول مرة أخرى.",

  venueTitle: "المنشأة",
  venueName: "اسم المنشأة",
  planLabel: "الباقة",
  profileTitle: "بيانات المنشأة",
  mapUrl: "رابط الموقع",
  mapUrlHint: "رابط من خرائط Google أو Apple يبدأ بـ \u2066https://\u2069",
  errMapUrl: "يجب أن يبدأ رابط الموقع بـ \u2066https://\u2069",
  seats: "عدد المقاعد",
  errSeats: "عدد المقاعد رقم صحيح بين 1 و2000.",
  contactName: "اسم المسؤول",
  contactPhone: "جوال المسؤول",
  contactEmail: "بريد المسؤول",
  offerEn: "العرض للدرّاجين (بالإنجليزية)",
  offerAr: "العرض للدرّاجين (بالعربية)",
  offerHint: "ما يحصل عليه الدرّاجون، مثل خصم على الفطور.",
  tierTitle: "باقتك",
  tierRules: "طريقة الحجز",
  ruleModes: "أنواع الحجز: {list}",
  ruleMonthlyNone: "بلا حد شهري",
  ruleHorizon: "الحجز مسبقًا حتى: {days}",
  ruleLead: "المهلة المطلوبة للطلب: {days}",
  ruleCutoff: "يُحتسب إلغاء التاريخ المؤكد متأخرًا إذا كانت المدة المتبقية أقل من: {days}",
  benefitsTitle: "المزايا",
  benefitsSoon: "سيُعلن عن المزايا قريبًا.",
  // 2026-10-04 audit
  forgotPassword: "نسيت كلمة المرور؟",
  forgotIntro: "اطلب من مايكروموبيليتي كلمة مرور مؤقتة جديدة:",
  forgotWhatsApp: "واتساب",
  forgotEmail: "البريد الإلكتروني",
  forgotSubject: "بوابة الموردين: كلمة مرور جديدة",
  forgotBody: "مرحبًا مايكروموبيليتي،\n\nأرجو إرسال كلمة مرور مؤقتة جديدة لبوابة الموردين.\nاسم الدخول: {login}\n\nشكرًا لكم.",
  errMustChange: "اختر كلمة مرورك أولًا: كلمة المرور المؤقتة تتيح لك تغييرها فقط.",
  errTempExpired: "انتهت صلاحية كلمة المرور المؤقتة (تصلح 72 ساعة). اطلب واحدة جديدة من مايكروموبيليتي.",
  errForbidden: "لا يتيح لك حسابك القيام بذلك. تواصل مع مالك المنشأة.",
  errLateReason: "بقي على هذا الفطور أقل من 48 ساعة: أخبرنا بسبب الإلغاء.",
  errCommon: "كلمة المرور هذه شائعة جدًا. جرّب جملة قصيرة أو عدة كلمات لا رابط بينها.",
  errPersonal: "لا تستخدم اسم الدخول أو رقم الجوال أو اسم المنشأة في كلمة المرور.",
  errPhone: "أدخل رقم جوال، مثل 05XXXXXXXX أو ‎+966 5X XXX XXXX.",
  errEmail: "أدخل بريدًا إلكترونيًا مثل name@example.com.",
  errTooLong: "النص أطول من المسموح. اختصره وحاول مرة أخرى.",
  errContactName: "اسم المسؤول حتى 120 حرفًا.",
  pwRuleCommon: "ليست كلمة مرور شائعة",
  pwRulePersonal: "لا تتضمن اسم الدخول أو الجوال أو اسم المنشأة",
  securityTitle: "الأجهزة المسجّل دخولها",
  securityIntro: "سجّل الخروج من كل هاتف أو حاسوب آخر يستخدم هذا الحساب، مثلًا بعد تغيّر الموظفين.",
  signedInOn: "الأجهزة المسجّل دخولها الآن: {n}",
  signOutOthers: "تسجيل الخروج من الأجهزة الأخرى",
  signedOutOthers: "الأجهزة الأخرى التي سُجّل خروجها: {n}.",
  navInsights: "الإحصاءات",
  navTeam: "الفريق",
  stDeclined: "لم يُختر",
  stCancelled: "ملغى",
  nextOpen: "أيام السبت المتاحة التالية",
  resultAfter: "ستؤكد مايكروموبيليتي الحجز؛ قد تطلب عدة منشآت التاريخ نفسه ونختار إحداها.",
  preselectGone: "التاريخ الذي اخترته ({date}) لم يعد متاحًا. اختر تاريخًا آخر.",
  decideBy: "ترد مايكروموبيليتي قبل {date}.",
  briefTitle: "ملخص الفطور",
  briefTimes: "يتجمع الدرّاجون الساعة {gather} وتنطلق الجولة الساعة {start}.",
  briefArrive: "الوصول المتوقع إليكم: تقريبًا من {from} إلى {to}.",
  briefNoTime: "لم تُحدَّد مواعيد الجولة بعد، وسنبلغكم بها.",
  briefContact: "للتواصل مع مايكروموبيليتي يوم الفطور:",
  briefOffer: "عرضك للدرّاجين:",
  briefNoOffer: "لا يوجد عرض بعد. يراه الدرّاجون عند إضافته من صفحة المنشأة.",
  callLabel: "اتصال",
  lateMark: "إلغاء متأخر",
  cancelledByMm: "ألغته مايكروموبيليتي",
  cancelReasonRequired: "السبب (مطلوب)",
  late48: "بقي على هذا الفطور أقل من 48 ساعة. يمكنك الإلغاء، لكن أخبرنا بالسبب: تُسجَّل الإلغاءات المتأخرة لأن الدرّاجين يخططون للحضور.",
  cancelPolicy: "سياسة الإلغاء: ألغِ الفطور المؤكد قبل يومه بـ 48 ساعة على الأقل متى أمكن. خلال آخر 48 ساعة يلزم ذكر السبب ويُسجَّل الإلغاء متأخرًا.",
  readOnlyNote: "يتيح لك حسابك عرض الحجوزات فقط. اطلب من مالك المنشأة أو مديرها طلب التواريخ أو إلغاءها.",
  insightsTitle: "الإحصاءات",
  insIntro: "عامكم الأخير مع درّاجي جولة السبت من مايكروموبيليتي.",
  insHosted: "مواعيد الفطور المستضافة",
  insUpcoming: "المؤكدة والقادمة",
  insShared: "تقييم الدرّاجين للفطور",
  insSharedSub: "متوسط آخر {n} شاركتها مايكروموبيليتي",
  insSharedNone: "لم تُشارَك تقييمات بعد",
  insOwn: "تقييماتكم",
  insOwnSub: "متوسط ملاحظاتكم ({n})",
  insOwnNone: "لم تُرسلوا ملاحظات بعد",
  insRecentTitle: "الدرّاجون المسجّلون والحاضرون",
  insRecentNone: "لم تستضيفوا أي فطور بعد.",
  insBooked: "المسجّلون",
  insCame: "الحاضرون",
  insNotSaid: "لم يُذكر",
  insDate: "التاريخ",
  insOutOf10: "{score} / 10",
  insOutOf5: "{score} / 5",
  teamTitle: "الفريق",
  teamIntro: "كل من يمكنه تسجيل الدخول باسم {venue}. تضيف مايكروموبيليتي الحسابات وتزيلها: تواصل معنا لأي تغيير.",
  teamLogin: "اسم الدخول",
  teamName: "الاسم",
  teamRole: "الدور",
  teamStatus: "الحالة",
  teamLast: "آخر دخول",
  teamNever: "لم يدخل بعد",
  teamYou: "(أنت)",
  teamActive: "نشط",
  teamOff: "موقوف",
  roleOwner: "المالك",
  roleManager: "المدير",
  roleViewer: "مُطّلع (قراءة فقط)",
  roleLine: "دورك: {role}",
  privacyLink: "إشعار الخصوصية",
  profileReadOnly: "يستطيع مالك المنشأة فقط تعديل هذه البيانات.",
  listSep: "، ",
};

export type Lang = "en" | "ar";
export const STRINGS: Record<Lang, Record<Key, string>> = { en, ar };

/** The text for key in lang, with {name} placeholders filled. */
export function fmt(lang: Lang, key: Key, vars?: Record<string, string | number>): string {
  let s = STRINGS[lang][key];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}
