// LearnForm's own words, in English and Arabic; every other language translates the English
// (src/i18n/tx), a sentence with values in it as its template. The Arabic of the choices reads
// the same whoever is learning - the visitor, their child or another adult.
export const T = {
  en: {
    who: "Who is learning?", self: "Me", child: "My child", other: "Someone else",
    // Each learner's card, by its place in the list; the button under the list adds one.
    learner: (n: number) => `Learner ${n}`, remove: (n: number) => `Remove learner ${n}`, add: "Add another learner",
    childName: "Child's name", childNameHint: "First name is enough.", otherName: "Their full name",
    age: "Age", gender: "Gender", male: "Male", female: "Female",
    height: "Height (cm)", heightHint: "It helps us bring the right bike size.",
    level: "Riding so far", never: "Never ridden a bike", tried: "Tried, but can't ride yet", refresh: "Rode before - needs a refresher",
    // A "Me" card asks only the riding so far: the rest is the person's own, from their details.
    selfNote: "Your age comes from your date of birth below, and your gender and height from your account.",
    details: "Your details", parentHint: "As the parent: your own details, not your child's.",
    phone: "Mobile number", email: "Email", notes: "Anything we should know? (optional)",
    // Two steps (the owner, 2026-09-30): the account - made here with the booking app's sign-up, or
    // signed in to - then the lesson.
    stepsLabel: "Steps", step1: "Your account", step2: "The lesson",
    haveQ: "Do you already have a Micromobility account?", haveYes: "Yes, I have an account", haveNo: "No, I'm new", back: "Back",
    loading: "Loading…",
    signinTitle: "Sign in to your account", identifier: "Email or mobile number", password: "Password",
    signin: "Sign in", signingIn: "Signing in…",
    oauthAsk: "Signed up with Google or Apple?", oauthLink: "Sign in through the booking app",
    createTitle: "Create your account",
    createSub: "This is the account you book rides with. You sign in with your email or mobile number and your password.",
    accountFor: "Signing up your child? The account is yours.",
    first: "First name", last: "Last name", password2: "Confirm password",
    pwdHint: "At least 8 characters, with an uppercase letter and a number.",
    create: "Create account", creating: "Creating your account…",
    madeTitle: "Your account has been created",
    madeText: "You can now sign in and book rides with your email or mobile number and your password. Next, tell us about the lesson.",
    signedAs: (name: string) => `Signed in as ${name}`,
    // What the community form asks (the owner, 2026-09-28: for the account the sign-up makes), in
    // its words. Instagram and LinkedIn may be left empty, and the form does not say so.
    birth: "Date of birth", day: "Day", month: "Month", year: "Year",
    nationality: "Nationality", natPick: "Choose your nationality",
    // Its name on the nationality list in every language (lib/nationality.ts): the browser's names
    // say "Palestinian Territories" in most.
    palestine: "Palestine",
    profession: "Profession", professionPh: "e.g. Engineer",
    // Their company (the owner, 2026-09-29; sent as workplace), in the community form's words.
    workplace: "Company", workplaceHint: "The company you work for",
    instagram: "Instagram", instagramHint: "Your Instagram username, or a link to your profile",
    linkedin: "LinkedIn", linkedinHint: "The link to your LinkedIn profile",
    // The booking app's own ride news box (rideNewsOpt).
    news: "Send me ride news and announcements by WhatsApp and email. I can stop at any time.",
    // How they heard of us: the booking app's answers, in its English (its heard_* texts).
    heard: "How did you hear about us?", heardPick: "Choose one",
    heardOpts: {
      instagram: "Instagram", tiktok: "TikTok", snapchat: "Snapchat", x: "X (Twitter)", facebook: "Facebook", youtube: "YouTube",
      whatsapp: "WhatsApp", google: "Google search", friend: "A friend or family", invited: "Invited by MicroMobility",
      passed_by: "Passed by the circuit", event: "An event or exhibition", hotel: "Hotel or tour", school: "School or university",
      work: "Work or my company", community: "A community ride", other: "Other",
    } as Record<string, string>,
    // The Privacy Notice's name is a link in the sentence: its place comes from the template.
    privacy: (link: string) => `I have read the ${link}`, privacyLink: "Privacy Notice",
    use: "We use these details to arrange the lesson.",
    send: "Sign up", sending: "Sending…", again: "Sign up more learners",
    // Under the thank-you (the owner, 2026-10-07): replies are slow while sign-ups are many.
    surge: "We're getting more sign-ups than usual right now, so it may take us a while to get back to you. Thank you for your patience. We'll be in touch as soon as we've reviewed yours.",
    // A learner's message names their card: "Learner 2: Enter the child's age, from 3 to 17."
    learnerError: (n: number, message: string) => `Learner ${n}: ${message}`,
    // WhatsApp (the owner, 2026-10-07): is the account's mobile their WhatsApp too, or which number is.
    waAsk: (phone: string) => `Is ${phone} your WhatsApp number too?`, waYes: "Yes", waNo: "No", waLabel: "WhatsApp number",
    errors: {
      whatsapp: "Enter your WhatsApp number, or answer whether your mobile is it.",
      learner_who: "Choose who is learning.", learner_name: "Enter the child's name - letters only.", learner_name_other: "Enter their full name - letters only.",
      learner_age: "Enter an age up to 99.", learner_age_child: "Enter the child's age, up to 99.", learner_age_other: "Enter their age, up to 99.",
      learner_twice: "This learner is already on the list.", learners: "Check the list of learners: from 1 to 5, each one only once.",
      // A second sign-up joins the first one still waiting: the two together hold 5 at most.
      learners_total: "You can sign up at most 5 learners in all, including the ones you have already signed up.",
      learner_gender: "Choose male or female.", learner_height: "Enter a height between 80 and 250 cm.", level: "Choose how much riding so far.",
      first: "Enter your first name - letters, spaces and periods only.", last: "Enter your last name - letters, spaces and periods only.",
      phone: "Check the mobile number, e.g. 05XXXXXXXX.",
      password: "Password must be at least 8 characters and include an uppercase letter and a number.", password2: "Passwords do not match.",
      acct_height: "Enter your height in cm (100 to 250).",
      email_taken: "An account with this email already exists. Go back and choose “Yes, I have an account” to sign in.",
      phone_taken: "An account with this mobile number already exists. Go back and choose “Yes, I have an account” to sign in.",
      signin_empty: "Enter your email or mobile number and your password.", signin_bad: "The email, mobile number or password is not right.",
      signin_locked: "Too many tries. Please wait a few minutes and try again.",
      rate_limited: "Too many tries from this network. Please wait a few minutes and try again.",
      // The site's sign-in (api/account) and its check, in the sign-in card's words.
      slow: "Too many tries from this connection - wait a minute and try again.", check: "Please complete the check below, then try again.",
      signed_out: "You were signed out. Sign in again to send the sign-up.",
      consents: "Your account was created, but your Privacy Notice and ride news answers could not be saved. Check the connection and press Create account again.",
      account: "Your account's email or mobile number needs updating in the booking app before you can sign up here.",
      account_name: "Your account's name needs a first and a last name. Update it in the booking app before you sign up here.",
      expired: "That sign-in link has expired. Sign in again.",
      email: "Check the email address.", heard_from: "Please tell us how you heard about us.",
      birth_date: "Choose your date of birth.", birth_young: "Riders must be at least 5 years old. Check the birth date.", gender: "Choose your gender.", nationality: "Choose your nationality.",
      height: "Enter your height in cm (80 to 250).", profession: "Enter your profession.", workplace: "Enter your company.",
      instagram: "An Instagram username has only letters, numbers, dots and underscores.", linkedin: "Paste the link to your own profile (linkedin.com/in/…).",
      notes: "Keep the note to 600 characters.", privacy: "Please confirm you have read the Privacy Notice.",
      throttled: "Too many sign-ups from this network - try again in a few minutes.",
      generic: "It could not be sent. Check the connection and try again.",
    } as Record<string, string>,
  },
  ar: {
    who: "مَن سيتعلّم؟", self: "أنا", child: "طفلي", other: "شخص آخر",
    learner: (n: number) => `المتعلّم ${n}`, remove: (n: number) => `إزالة المتعلّم ${n}`, add: "إضافة متعلّم آخر",
    childName: "اسم الطفل", childNameHint: "يكفي الاسم الأول.", otherName: "الاسم الكامل",
    age: "العمر", gender: "الجنس", male: "ذكر", female: "أنثى",
    height: "الطول (سم)", heightHint: "يساعدنا على تجهيز دراجة بالمقاس المناسب.",
    level: "الخبرة في الركوب حتى الآن", never: "لا خبرة سابقة في ركوب الدراجة", tried: "محاولات سابقة دون إتقان الركوب بعد", refresh: "خبرة سابقة تحتاج إلى تنشيط",
    selfNote: "عمرك من تاريخ ميلادك أدناه، وجنسك وطولك من حسابك.",
    details: "بياناتك", parentHint: "بصفتك وليّ الأمر: بياناتك أنت، لا بيانات طفلك.",
    phone: "رقم الجوال", email: "البريد الإلكتروني", notes: "أي تفاصيل تهمنا؟ (اختياري)",
    stepsLabel: "الخطوات", step1: "حسابك", step2: "الدرس",
    haveQ: "هل لديك حساب في مايكروموبيليتي؟", haveYes: "نعم، لديّ حساب", haveNo: "لا، أنا جديد", back: "رجوع",
    loading: "جارٍ التحميل…",
    signinTitle: "سجّل الدخول إلى حسابك", identifier: "البريد الإلكتروني أو رقم الجوال", password: "كلمة المرور",
    signin: "تسجيل الدخول", signingIn: "جارٍ تسجيل الدخول…",
    oauthAsk: "سجّلت عبر Google أو Apple؟", oauthLink: "سجّل الدخول عبر تطبيق الحجز",
    createTitle: "أنشئ حسابك",
    createSub: "بهذا الحساب تحجز جولاتك. تسجّل الدخول ببريدك الإلكتروني أو رقم جوالك وكلمة مرورك.",
    accountFor: "تسجّل طفلك؟ الحساب باسمك أنت.",
    first: "الاسم الأول", last: "اسم العائلة", password2: "تأكيد كلمة المرور",
    pwdHint: "8 أحرف على الأقل، وتحتوي على حرف كبير ورقم.",
    create: "إنشاء حساب", creating: "جارٍ إنشاء حسابك…",
    madeTitle: "تم إنشاء حسابك",
    madeText: "يمكنك الآن تسجيل الدخول وحجز الجولات ببريدك الإلكتروني أو رقم جوالك وكلمة مرورك. والآن، أخبرنا عن الدرس.",
    signedAs: (name: string) => `مسجّل الدخول باسم ${name}`,
    birth: "تاريخ الميلاد", day: "اليوم", month: "الشهر", year: "السنة",
    nationality: "الجنسية", natPick: "اختر جنسيتك",
    palestine: "فلسطين",
    profession: "المهنة", professionPh: "مثال: مهندس",
    workplace: "الشركة", workplaceHint: "الشركة التي تعمل فيها",
    instagram: "Instagram", instagramHint: "اسم المستخدم في Instagram، أو رابط حسابك",
    linkedin: "LinkedIn", linkedinHint: "رابط ملفك الشخصي على LinkedIn",
    news: "أرسلوا لي أخبار الرحلات والإعلانات عبر واتساب والبريد الإلكتروني، ويمكنني إيقافها في أي وقت.",
    heard: "كيف عرفت عنا؟", heardPick: "اختر واحداً",
    heardOpts: {
      instagram: "Instagram", tiktok: "TikTok", snapchat: "Snapchat", x: "X (Twitter)", facebook: "Facebook", youtube: "YouTube",
      whatsapp: "WhatsApp", google: "بحث جوجل", friend: "صديق أو أحد الأقارب", invited: "بدعوة من مايكروموبيليتي",
      passed_by: "مررت بالحلبة", event: "فعالية أو معرض", hotel: "فندق أو جولة سياحية", school: "مدرسة أو جامعة",
      work: "العمل أو شركتي", community: "جولة مجتمعية", other: "غير ذلك",
    } as Record<string, string>,
    privacy: (link: string) => `قرأت ${link}`, privacyLink: "إشعار الخصوصية",
    use: "نستخدم هذه البيانات لترتيب الدرس.",
    send: "سجّل الآن", sending: "جارٍ الإرسال…", again: "سجّل متعلّمين آخرين",
    surge: "نستقبل حاليًا عددًا من طلبات التسجيل أكبر من المعتاد، لذا قد يستغرق ردّنا عليك بعض الوقت. شكرًا لصبرك، وسنتواصل معك فور مراجعة طلبك.",
    learnerError: (n: number, message: string) => `المتعلّم ${n}: ${message}`,
    waAsk: (phone: string) => `هل ${phone} هو رقمك على WhatsApp أيضًا؟`, waYes: "نعم", waNo: "لا", waLabel: "رقم WhatsApp",
    errors: {
      whatsapp: "أدخل رقمك على WhatsApp، أو أجب إن كان جوالك هو رقمك عليه.",
      learner_who: "اختر مَن سيتعلّم.", learner_name: "أدخل اسم الطفل - حروف فقط.", learner_name_other: "أدخل الاسم الكامل - حروف فقط.",
      learner_age: "أدخل عمراً حتى 99 عاماً.", learner_age_child: "أدخل عمر الطفل، حتى 99 عاماً.", learner_age_other: "أدخل العمر، حتى 99 عاماً.",
      learner_twice: "هذا المتعلّم مُضاف إلى القائمة من قبل.", learners: "راجع قائمة المتعلّمين: من 1 إلى 5، وكلٌّ منهم مرة واحدة فقط.",
      learners_total: "يمكنك تسجيل 5 متعلّمين على الأكثر في المجموع، بمن فيهم من سجّلتهم من قبل.",
      learner_gender: "حدّد الجنس: ذكر أو أنثى.", learner_height: "أدخل طولاً بين 80 و250 سم.", level: "اختر مستوى الخبرة في الركوب.",
      first: "أدخل اسمك الأول - حروف ومسافات ونقاط فقط.", last: "أدخل اسم العائلة - حروف ومسافات ونقاط فقط.",
      phone: "تحقق من رقم الجوال، مثل 05XXXXXXXX.",
      password: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير ورقم.", password2: "كلمتا المرور غير متطابقتين.",
      acct_height: "أدخل طولك بالسنتيمتر (من 100 إلى 250).",
      email_taken: "يوجد حساب بهذا البريد الإلكتروني بالفعل. ارجع واختر «نعم، لديّ حساب» لتسجيل الدخول.",
      phone_taken: "يوجد حساب برقم الجوال هذا بالفعل. ارجع واختر «نعم، لديّ حساب» لتسجيل الدخول.",
      signin_empty: "أدخل بريدك الإلكتروني أو رقم جوالك وكلمة المرور.", signin_bad: "البريد الإلكتروني أو رقم الجوال أو كلمة المرور غير صحيحة.",
      signin_locked: "محاولات كثيرة. انتظر بضع دقائق ثم حاول مجددًا.",
      rate_limited: "محاولات كثيرة من هذه الشبكة. انتظر بضع دقائق ثم حاول مجددًا.",
      slow: "محاولات كثيرة من هذا الاتصال - انتظر دقيقة وحاول مجدداً.", check: "يرجى إكمال التحقق أدناه ثم المحاولة مجدداً.",
      signed_out: "تم تسجيل خروجك. سجّل الدخول مرة أخرى لإرسال التسجيل.",
      consents: "تم إنشاء حسابك، لكن تعذّر حفظ إقرارك بإشعار الخصوصية واختيارك لأخبار الرحلات. تحقق من الاتصال واضغط «إنشاء حساب» مرة أخرى.",
      account: "يحتاج البريد الإلكتروني أو رقم الجوال في حسابك إلى تحديث في تطبيق الحجز قبل التسجيل هنا.",
      account_name: "يجب أن يتضمن اسم حسابك الاسم الأول واسم العائلة. حدّثه في تطبيق الحجز قبل التسجيل هنا.",
      expired: "انتهت صلاحية رابط تسجيل الدخول هذا. سجّل الدخول مرة أخرى.",
      email: "تحقق من البريد الإلكتروني.", heard_from: "أخبرنا من فضلك كيف عرفت عنا.",
      birth_date: "اختر تاريخ ميلادك.", birth_young: "يجب ألا يقل عمر الراكب عن 5 سنوات. تحقّق من تاريخ الميلاد.", gender: "اختر جنسك.", nationality: "اختر جنسيتك.",
      height: "أدخل طولك بالسنتيمتر (من 80 إلى 250).", profession: "أدخل مهنتك.", workplace: "أدخل اسم شركتك.",
      instagram: "يتكوّن اسم المستخدم في Instagram من حروف وأرقام ونقاط وشرطات سفلية فقط.", linkedin: "الصق رابط ملفك الشخصي الخاص بك (linkedin.com/in/…).",
      notes: "اجعل الملاحظة في حدود 600 حرف.", privacy: "يرجى تأكيد قراءتك لإشعار الخصوصية.",
      throttled: "تسجيلات كثيرة من هذه الشبكة - حاول بعد دقائق.",
      generic: "تعذّر الإرسال. تحقق من الاتصال وحاول مجدداً.",
    } as Record<string, string>,
  },
};
