// My Account's details, settings and cards (the owner, 2026-10-03: everything the booking app's
// My Account has), in English and Arabic - the booking app's own words where it has them (its
// profile*, acc*, rideNews*, del*, fix*, ambMine* and mr* LANG keys); every other language
// translates the English (src/i18n/tx), a sentence with values in it as its template.
export const T = {
  en: {
    // The season (_seasonDashboard) and the profile meter
    seasonTitle: "Your season",
    rideOne: "completed ride",
    rideMany: "completed rides",
    tiers: { newcomer: "Newcomer", regular: "Regular", pro: "Pro", elite: "Elite", legend: "Legend" } as Record<string, string>,
    toNextOne: (t: string) => `1 more ride to ${t}`,
    toNext: (n: string, t: string) => `${n} more rides to ${t}`,
    topTier: "Top tier",
    streak: (n: string) => `${n} weeks in a row`,
    nextRide: (d: string, w: string) => `Next ride: ${d} (${w})`,
    today: "Today",
    tomorrow: "Tomorrow",
    inDays: (n: string) => `in ${n} days`,
    bookNext: "Book your next ride",
    profilePct: (n: string) => `Profile ${n}% complete`,
    // The details
    details: "Your details",
    photo: "Profile photo",
    upload: "Upload photo",
    uploading: "Uploading…",
    remove: "Remove",
    photoSaved: "Photo updated.",
    photoRead: "Could not read that image.",
    photoFail: "The photo could not be saved. Please try again.",
    first: "First name",
    middle: "Middle name",
    last: "Last name",
    optional: "optional",
    email: "Email address",
    phone: "Mobile number",
    cc: "Country code",
    height: "Height (cm)",
    heightHint: "Sets the frame size",
    birth: "Date of birth",
    day: "Day",
    month: "Month",
    year: "Year",
    country: "Country of residence",
    countryPick: "Select country of residence",
    city: "City of residence",
    cityPick: "Select city of residence",
    cityFirst: "Select a country first",
    nationality: "Nationality",
    natPick: "Choose your nationality",
    gender: "Gender",
    male: "Male",
    female: "Female",
    profession: "Profession",
    professionPh: "e.g. Engineer",
    workplace: "Company",
    workplacePh: "The company you work for",
    socials: "Social accounts",
    socialPh: "Username or profile link",
    bikeType: "Bike type preference",
    typeHint: "We'll pre-select this each time you book.",
    bikeOwner: "Bike owner",
    heard: "How did you hear about us?",
    heardPick: "Choose one",
    heardOpts: {
      instagram: "Instagram", tiktok: "TikTok", snapchat: "Snapchat", x: "X (Twitter)", facebook: "Facebook", youtube: "YouTube",
      whatsapp: "WhatsApp", google: "Google search", friend: "A friend or family", invited: "Invited by MicroMobility",
      passed_by: "Passed by the circuit", event: "An event or exhibition", hotel: "Hotel or tour", school: "School or university",
      work: "Work or my company", community: "A community ride", other: "Other",
    } as Record<string, string>,
    signsInWith: "Signs in with",
    google: "Google sign-in",
    apple: "Apple sign-in",
    save: "Save changes",
    saving: "Saving…",
    saved: "Your details are saved.",
    errors: {
      name_chars: "Names can only contain letters, spaces and periods.",
      name_short: "Write each name in full: every name needs at least two letters.",
      name_missing: "Please enter your full name (first and last name).",
      email: "Please enter a valid email address.",
      phone: "Please enter a valid phone number (at least 8 digits).",
      contact: "Keep an email address or a mobile number on your account.",
      phone_taken: "An account with this phone number already exists.",
      email_taken: "An account with this email already exists.",
      rate: "Too many tries from this network. Please wait a few minutes and try again.",
      height: "Enter your height in cm, between 100 and 250.",
      birth_future: "A birth date can't be in the future.",
      birth_young: "Riders must be at least 5 years old. Check the birth date.",
      birth_old: "Check the birth date: it is more than 100 years ago.",
      birth_part: "Choose the day, the month and the year.",
      birth_missing: "Enter your birth date to continue.",
      country: "Choose a country from the list.",
      city: "Choose a city from the list.",
      nationality: "Choose your nationality.",
      type: "Choose a bike type.",
      gender: "Choose male or female.",
      profession: "Enter your profession: 2 to 80 characters.",
      workplace: "Enter your company: 2 to 120 characters.",
      heard: "Please tell us how you heard about us.",
      pick: "Choose one to continue.",
      photo: "Upload a photo to continue.",
      relay: "Enter the email address you use, not Apple's hidden one.",
      weak: "Password must be at least 8 characters and include an uppercase letter and a number.",
      signin: "Your session has ended - sign in again.",
      generic: "Your changes weren't saved. Please try again.",
    } as Record<string, string>,
    socialErr: (net: string) => `Check the ${net} handle - letters, numbers, dots and underscores only.`,
    // Ride news and the Privacy Notice
    rnTitle: "Ride news",
    rnSub: "New rides, schedules, offers and community news, by WhatsApp and email. Switch it off at any time.",
    rnOn: "You're getting ride news.",
    rnOff: "You're not getting ride news.",
    rnStop: "Stop ride news",
    rnStart: "Send me ride news",
    privacy: "Privacy Notice",
    connection: "It could not be saved. Check the connection and try again.",
    askTitle: "Before you continue",
    askNewsTitle: "Ride news?",
    askNotice: "We've published our {0}. It explains what we collect and your rights.",
    ack: "I have read the {0}.",
    ackRequired: "Please confirm you've read the Privacy Notice.",
    yes: "Yes, send me ride news",
    no: "No ride news, thanks",
    continue: "Continue",
    // Deleting the account
    delTitle: "Delete my account",
    delSub: "We delete your account and personal details within 30 days of your request. Booking and payment records the law requires us to keep stay for that period.",
    delBtn: "Request account deletion",
    delRequested: (d: string) => `Deletion requested on ${d}. We'll delete your account within 30 days.`,
    delWithdraw: "Withdraw the request",
    delConfirmTitle: "Delete your account?",
    delConfirmBody: "We'll delete your account within 30 days. Until then you can still sign in, and withdraw the request here.",
    delConfirmBtn: "Request deletion",
    cancel: "Cancel",
    // Passwords
    pwTitle: "Password",
    pwSub: "Change the password you sign in with. Your other devices will be signed out.",
    pwSetSub: "Your account signs in with Google or Apple. Set a password to sign in with your email or mobile number too.",
    pwCurrent: "Current password",
    pwCurrentHint: "Leave it empty if you have only ever signed in with Google or Apple.",
    pwNew: "New password",
    pwNew2: "Confirm new password",
    pwRule: "At least 8 characters, with an uppercase letter and a number.",
    pwChange: "Change password",
    pwSet: "Set password",
    pwDone: "Your password is changed. Your other devices are signed out.",
    show: "Show",
    hide: "Hide",
    forcedTitle: "Choose a new password",
    forcedSub: "Your password was set by our team. Choose your own to continue.",
    pwErrors: {
      current: "Enter your current password.",
      bad: "That current password isn't right.",
      weak: "Password must be at least 8 characters and include an uppercase letter and a number.",
      mismatch: "Passwords do not match.",
      same: "Choose a password different from your current one.",
      locked: "Too many wrong tries - wait 15 minutes and try again.",
      notdue: "Your password is already up to date.",
      signin: "Your session has ended - sign in again.",
      generic: "It could not be saved. Check the connection and try again.",
    } as Record<string, string>,
    // Purchases
    purchTitle: "Purchases",
    total: "Total",
    voided: "Voided",
    refunded: "Refunded",
    // Corrections staff asked for
    fixKicker: "Quick check",
    fixTitle: "Let's get your details right",
    fixSub: "Our team noticed that some details on your account may not be right. Please update them below - it takes a minute, and it keeps your bookings and check-in running smoothly.",
    fixOwnTitle: "Complete your account",
    fixOwnSub: "A few details are still missing from your account. Please add them below.",
    fixNote: "You can book as soon as these are saved.",
    fixHead: "Needs your attention",
    fixWas: (v: string) => `On your account: ${v}`,
    fixWasEmpty: "Nothing on your account yet",
    fixSave: "Save",
    fixThanks: "Thank you. Your details are up to date.",
    fixCheck: "That didn't look right. Please check it and try again.",
    fixLabels: { name: "Full name", email: "Email address", phone: "Mobile number", birth_date: "Date of birth", gender: "Gender", nationality: "Nationality", residence: "Country and city of residence", height: "Height (cm)", photo: "Profile photo", password: "Password" } as Record<string, string>,
    // The ambassador card
    ambTitle: "Your ambassador card",
    ambPaused: "Paused",
    ambCode: "Your code",
    ambShare: "Share code",
    copy: "Copy",
    copied: "Copied ✓",
    ambPoints: "Points earned",
    ambBalance: "To spend",
    ambUses: "Friends who used it",
    ambRecent: "Latest",
    ambCtx: { rental: "Ride booking", event: "Community ride", workshop: "Workshop service" } as Record<string, string>,
    ambSt: { confirmed: "Confirmed", pending: "Pending", void: "Voided" } as Record<string, string>,
    // A badge just earned
    newBadge: "New badge!",
    close: "Close",
    // Settings
    language: "Language",
    signOut: "Sign out",
  },
  ar: {
    seasonTitle: "موسمك",
    rideOne: "رحلة مكتملة",
    rideMany: "رحلات مكتملة",
    tiers: { newcomer: "مبتدئ", regular: "منتظم", pro: "محترف", elite: "نخبة", legend: "أسطورة" } as Record<string, string>,
    toNextOne: (t: string) => `رحلة واحدة للوصول إلى ${t}`,
    toNext: (n: string, t: string) => `${n} رحلات للوصول إلى ${t}`,
    topTier: "أعلى مستوى",
    streak: (n: string) => `${n} أسابيع متتالية`,
    nextRide: (d: string, w: string) => `رحلتك القادمة: ${d} (${w})`,
    today: "اليوم",
    tomorrow: "غداً",
    inDays: (n: string) => `بعد ${n} أيام`,
    bookNext: "احجز رحلتك القادمة",
    profilePct: (n: string) => `اكتمال الملف ${n}%`,
    details: "بياناتك",
    photo: "صورة الملف",
    upload: "رفع صورة",
    uploading: "جارٍ الرفع…",
    remove: "إزالة",
    photoSaved: "تم تحديث الصورة.",
    photoRead: "تعذّرت قراءة الصورة.",
    photoFail: "تعذّر حفظ الصورة. حاول مرة أخرى.",
    first: "الاسم الأول",
    middle: "الاسم الأوسط",
    last: "اسم العائلة",
    optional: "اختياري",
    email: "البريد الإلكتروني",
    phone: "رقم الجوال",
    cc: "رمز الدولة",
    height: "الطول (سم)",
    heightHint: "لتحديد مقاس الإطار",
    birth: "تاريخ الميلاد",
    day: "اليوم",
    month: "الشهر",
    year: "السنة",
    country: "بلد الإقامة",
    countryPick: "اختر بلد الإقامة",
    city: "مدينة الإقامة",
    cityPick: "اختر مدينة الإقامة",
    cityFirst: "اختر الدولة أولاً",
    nationality: "الجنسية",
    natPick: "اختر جنسيتك",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    profession: "المهنة",
    professionPh: "مثال: مهندس",
    workplace: "الشركة",
    workplacePh: "الشركة التي تعمل فيها",
    socials: "حسابات التواصل",
    socialPh: "اسم المستخدم أو رابط الحساب",
    bikeType: "تفضيل نوع الدراجة",
    typeHint: "نختاره لك تلقائياً في كل حجز.",
    bikeOwner: "مالك دراجة",
    heard: "كيف عرفت عنا؟",
    heardPick: "اختر واحداً",
    heardOpts: {
      instagram: "Instagram", tiktok: "TikTok", snapchat: "Snapchat", x: "X (Twitter)", facebook: "Facebook", youtube: "YouTube",
      whatsapp: "WhatsApp", google: "بحث جوجل", friend: "صديق أو أحد الأقارب", invited: "بدعوة من مايكروموبيليتي",
      passed_by: "مررت بالحلبة", event: "فعالية أو معرض", hotel: "فندق أو جولة سياحية", school: "مدرسة أو جامعة",
      work: "العمل أو شركتي", community: "جولة مجتمعية", other: "غير ذلك",
    } as Record<string, string>,
    signsInWith: "تسجيل الدخول عبر",
    google: "تسجيل الدخول عبر Google",
    apple: "تسجيل الدخول عبر Apple",
    save: "حفظ التغييرات",
    saving: "جارٍ الحفظ…",
    saved: "تم حفظ بياناتك.",
    errors: {
      name_chars: "يمكن أن يحتوي الاسم على حروف ومسافات ونقاط فقط.",
      name_short: "اكتب كل اسم كاملًا: يجب أن يتكون كل اسم من حرفين على الأقل.",
      name_missing: "الرجاء إدخال اسمك الكامل (الاسم الأول والأخير).",
      email: "الرجاء إدخال بريد إلكتروني صحيح.",
      phone: "الرجاء إدخال رقم هاتف صحيح (8 أرقام على الأقل).",
      contact: "احتفظ ببريد إلكتروني أو رقم جوال في حسابك.",
      phone_taken: "يوجد حساب بهذا الرقم مسبقاً.",
      email_taken: "يوجد حساب بهذا البريد الإلكتروني مسبقاً.",
      rate: "محاولات كثيرة من هذه الشبكة. انتظر بضع دقائق ثم حاول مجدداً.",
      height: "أدخل طولك بالسنتيمتر، بين 100 و250.",
      birth_future: "لا يمكن أن يكون تاريخ الميلاد في المستقبل.",
      birth_young: "يجب ألا يقل عمر الراكب عن 5 سنوات. تحقّق من تاريخ الميلاد.",
      birth_old: "تحقّق من تاريخ الميلاد: يعود إلى أكثر من 100 عام.",
      birth_part: "اختر اليوم والشهر والسنة.",
      birth_missing: "أدخل تاريخ ميلادك للمتابعة.",
      country: "اختر دولة من القائمة.",
      city: "اختر مدينة من القائمة.",
      nationality: "اختر جنسيتك.",
      type: "اختر نوع الدراجة.",
      gender: "اختر ذكر أو أنثى.",
      profession: "أدخل مهنتك: من 2 إلى 80 حرفاً.",
      workplace: "أدخل اسم شركتك: من 2 إلى 120 حرفاً.",
      heard: "أخبرنا من فضلك كيف عرفت عنا.",
      pick: "اختر أحد الخيارات للمتابعة.",
      photo: "حمّل صورة للمتابعة.",
      relay: "أدخل بريدك الإلكتروني الذي تستخدمه، لا البريد المخفي من Apple.",
      weak: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير ورقم.",
      signin: "انتهت جلستك - سجّل الدخول مجدداً.",
      generic: "لم تُحفظ تغييراتك. حاول مرة أخرى من فضلك.",
    } as Record<string, string>,
    socialErr: (net: string) => `تحقق من معرّف ${net} - أحرف وأرقام ونقاط وشرطات سفلية فقط.`,
    rnTitle: "أخبار الرحلات",
    rnSub: "رحلات جديدة وجداول ومواعيد وعروض وأخبار المجتمع عبر واتساب والبريد الإلكتروني. يمكنك إيقافها في أي وقت.",
    rnOn: "أنت مشترك في أخبار الرحلات.",
    rnOff: "أنت غير مشترك في أخبار الرحلات.",
    rnStop: "إيقاف أخبار الرحلات",
    rnStart: "أرسلوا لي أخبار الرحلات",
    privacy: "إشعار الخصوصية",
    connection: "تعذّر الحفظ. تحقق من الاتصال وحاول مجدداً.",
    askTitle: "قبل المتابعة",
    askNewsTitle: "هل ترغب في أخبار الرحلات؟",
    askNotice: "نشرنا {0} الذي يوضح البيانات التي نجمعها وحقوقك.",
    ack: "قرأت {0}.",
    ackRequired: "يرجى تأكيد قراءتك لإشعار الخصوصية.",
    yes: "نعم، أرسلوا لي أخبار الرحلات",
    no: "لا أرغب في أخبار الرحلات",
    continue: "متابعة",
    delTitle: "حذف حسابي",
    delSub: "نحذف حسابك وبياناتك الشخصية خلال 30 يومًا من طلبك، ونحتفظ بسجلات الحجز والدفع التي يوجب النظام حفظها طوال مدتها.",
    delBtn: "طلب حذف الحساب",
    delRequested: (d: string) => `طُلب الحذف في ${d}. سنحذف حسابك خلال 30 يومًا.`,
    delWithdraw: "سحب الطلب",
    delConfirmTitle: "حذف حسابك؟",
    delConfirmBody: "سنحذف حسابك خلال 30 يومًا. وحتى ذلك الحين يمكنك تسجيل الدخول وسحب الطلب من هنا.",
    delConfirmBtn: "طلب الحذف",
    cancel: "إلغاء",
    pwTitle: "كلمة المرور",
    pwSub: "غيّر كلمة المرور التي تسجّل الدخول بها. سيُسجَّل خروجك من أجهزتك الأخرى.",
    pwSetSub: "يسجّل حسابك الدخول عبر Google أو Apple. عيّن كلمة مرور لتسجّل الدخول ببريدك الإلكتروني أو رقم جوالك أيضاً.",
    pwCurrent: "كلمة المرور الحالية",
    pwCurrentHint: "اتركها فارغة إن كنت تسجّل الدخول عبر Google أو Apple فقط.",
    pwNew: "كلمة المرور الجديدة",
    pwNew2: "تأكيد كلمة المرور الجديدة",
    pwRule: "8 أحرف على الأقل، وتحتوي على حرف كبير ورقم.",
    pwChange: "تغيير كلمة المرور",
    pwSet: "تعيين كلمة المرور",
    pwDone: "تم تغيير كلمة المرور، وسُجّل خروجك من أجهزتك الأخرى.",
    show: "إظهار",
    hide: "إخفاء",
    forcedTitle: "اختر كلمة مرور جديدة",
    forcedSub: "عيّن فريقنا كلمة المرور الحالية. اختر كلمة مرورك الخاصة للمتابعة.",
    pwErrors: {
      current: "أدخل كلمة المرور الحالية.",
      bad: "كلمة المرور الحالية غير صحيحة.",
      weak: "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير ورقم.",
      mismatch: "كلمتا المرور غير متطابقتين.",
      same: "اختر كلمة مرور مختلفة عن الحالية.",
      locked: "محاولات خاطئة كثيرة - انتظر 15 دقيقة وحاول مجدداً.",
      notdue: "كلمة المرور محدّثة بالفعل.",
      signin: "انتهت جلستك - سجّل الدخول مجدداً.",
      generic: "تعذّر الحفظ. تحقق من الاتصال وحاول مجدداً.",
    } as Record<string, string>,
    purchTitle: "المشتريات",
    total: "المجموع",
    voided: "ملغاة",
    refunded: "مُستردّة",
    fixKicker: "تحقق سريع",
    fixTitle: "لنتأكد من صحة بياناتك",
    fixSub: "لاحظ فريقنا أن بعض المعلومات في حسابك قد لا تكون صحيحة. يُرجى تحديثها أدناه - لن يستغرق ذلك سوى دقيقة، ويساعد على أن تسير حجوزاتك وتسجيل وصولك بسلاسة.",
    fixOwnTitle: "أكمل حسابك",
    fixOwnSub: "ما زالت بعض البيانات ناقصة في حسابك. يُرجى إضافتها أدناه.",
    fixNote: "يمكنك الحجز فور حفظ هذه البيانات.",
    fixHead: "تحتاج إلى مراجعتك",
    fixWas: (v: string) => `في حسابك: ${v}`,
    fixWasEmpty: "لا توجد معلومة في حسابك بعد",
    fixSave: "حفظ",
    fixThanks: "شكرًا لك - بياناتك محدّثة الآن.",
    fixCheck: "يبدو أن هذه المعلومة غير صحيحة. يُرجى التحقق منها والمحاولة مرة أخرى.",
    fixLabels: { name: "الاسم الكامل", email: "البريد الإلكتروني", phone: "رقم الجوال", birth_date: "تاريخ الميلاد", gender: "الجنس", nationality: "الجنسية", residence: "بلد ومدينة الإقامة", height: "الطول (سم)", photo: "صورة الملف", password: "كلمة المرور" } as Record<string, string>,
    ambTitle: "بطاقة السفير",
    ambPaused: "موقوف مؤقتاً",
    ambCode: "رمزك",
    ambShare: "مشاركة الرمز",
    copy: "انسخ",
    copied: "تم النسخ ✓",
    ambPoints: "النقاط المكتسبة",
    ambBalance: "للاستبدال",
    ambUses: "أصدقاء استخدموه",
    ambRecent: "الأحدث",
    ambCtx: { rental: "حجز جولة", event: "جولة مجتمعية", workshop: "خدمة الورشة" } as Record<string, string>,
    ambSt: { confirmed: "مؤكدة", pending: "قيد التأكيد", void: "ملغاة" } as Record<string, string>,
    newBadge: "وسام جديد!",
    close: "إغلاق",
    language: "اللغة",
    signOut: "تسجيل الخروج",
  },
};
export type AccountText = (typeof T)["en"];
