// The emergency contact's words in every language the site speaks (EmergencyFields.tsx, the learn
// form and the account's check-up, EmergencyGate.tsx). Kept apart from the site's translation
// dictionaries (src/i18n/tx), as the rating's are (RatingForm.words.ts): the ten languages the booking
// app speaks take its own wording word for word (its emTitle, emSubAcc, emName, emPhone, emRelation,
// emPick, emRel_*, em2Title, em2Sub, em2Add, optionalLabel, errEmName, errEmPhone, errEmRelation,
// errEmSelf, errEmSame, errNameChars, errNameShort, emReqTitle, emReqSub, saveBtn and a11yDialCode:
// English and Arabic in app.src.html, the others in its i18n/<code>.json, 2026-10-07). Indonesian,
// Malay, German, Russian, Chinese and Japanese, which the booking app does not speak, follow
// src/i18n/TRANSLATING.md. Change a text here in every language at once.
import type { Locale } from "@/i18n/locales";
import type { EmRel } from "@/lib/emergency";

export type EmergencyWords = {
  title: string; sub: string; name: string; phone: string; relation: string; pick: string; rel: Record<EmRel, string>;
  title2: string; sub2: string; add2: string; optional: string;
  errName: string; errPhone: string; errRelation: string; errSelf: string; errSame: string; errNameChars: string; errNameShort: string;
  /** The account's check-up (EmergencyGate): its title and why it asks. */
  reqTitle: string; reqSub: string; save: string; dialCode: string;
};

export const EMERGENCY_WORDS: Record<Locale, EmergencyWords> = {
  en: {
    title: "Emergency contact",
    sub: "Someone we can call if you need help at an event.",
    name: "Contact’s name",
    phone: "Contact’s mobile number",
    relation: "Relationship to you",
    pick: "Choose",
    rel: {spouse: "Spouse", parent: "Parent", sibling: "Brother or sister", child: "Son or daughter", relative: "Relative", friend: "Friend", colleague: "Colleague", other: "Other"},
    title2: "Second emergency contact",
    sub2: "Someone else we can call if we can’t reach your first contact.",
    add2: "Add a second contact",
    optional: "optional",
    errName: "Enter your contact’s name.",
    errPhone: "Enter your contact’s mobile number.",
    errRelation: "Choose how they are related to you.",
    errSelf: "Your contact’s number can’t be your own.",
    errSame: "The two emergency contacts can’t have the same number.",
    errNameChars: "Names can only contain letters, spaces and periods.",
    errNameShort: "Write each name in full: every name needs at least two letters.",
    reqTitle: "Add your emergency contact",
    reqSub: "We now ask every rider for someone we can call if you need help at a ride or event. Add them once and you can book.",
    save: "Save",
    dialCode: "Country code",
  },
  ar: {
    title: "جهة اتصال للطوارئ",
    sub: "شخص نتصل به إن احتجت إلى مساعدة في إحدى الفعاليات.",
    name: "اسم جهة الاتصال",
    phone: "رقم جوال جهة الاتصال",
    relation: "صلة القرابة بك",
    pick: "اختر",
    rel: {spouse: "الزوج أو الزوجة", parent: "الأب أو الأم", sibling: "الأخ أو الأخت", child: "الابن أو الابنة", relative: "قريب", friend: "صديق", colleague: "زميل عمل", other: "أخرى"},
    title2: "جهة اتصال ثانية للطوارئ",
    sub2: "شخص آخر نتصل به إن تعذّر علينا الوصول إلى جهة الاتصال الأولى.",
    add2: "إضافة جهة اتصال ثانية",
    optional: "اختياري",
    errName: "أدخل اسم جهة الاتصال.",
    errPhone: "أدخل رقم جوال جهة الاتصال.",
    errRelation: "اختر صلة القرابة.",
    errSelf: "لا يمكن أن يكون رقم جهة الاتصال هو رقمك.",
    errSame: "لا يمكن أن يكون لجهتَي اتصال الطوارئ الرقم نفسه.",
    errNameChars: "يمكن أن يحتوي الاسم على حروف ومسافات ونقاط فقط.",
    errNameShort: "اكتب كل اسم كاملًا: يجب أن يتكون كل اسم من حرفين على الأقل.",
    reqTitle: "أضف جهة اتصال للطوارئ",
    reqSub: "نطلب الآن من كل راكب شخصًا نتصل به إن احتجت إلى مساعدة في رحلة أو فعالية. أضفه مرة واحدة وتستطيع الحجز.",
    save: "حفظ",
    dialCode: "رمز الدولة",
  },
  id: {
    title: "Kontak darurat",
    sub: "Seseorang yang bisa kami hubungi jika Anda butuh bantuan di sebuah acara.",
    name: "Nama kontak",
    phone: "Nomor ponsel kontak",
    relation: "Hubungan dengan Anda",
    pick: "Pilih",
    rel: {spouse: "Suami atau istri", parent: "Ayah atau ibu", sibling: "Saudara kandung", child: "Anak", relative: "Kerabat", friend: "Teman", colleague: "Rekan kerja", other: "Lainnya"},
    title2: "Kontak darurat kedua",
    sub2: "Orang lain yang bisa kami hubungi jika kontak pertama Anda tidak dapat dihubungi.",
    add2: "Tambah kontak kedua",
    optional: "opsional",
    errName: "Masukkan nama kontak Anda.",
    errPhone: "Masukkan nomor ponsel kontak Anda.",
    errRelation: "Pilih hubungan mereka dengan Anda.",
    errSelf: "Nomor kontak tidak boleh nomor Anda sendiri.",
    errSame: "Kedua kontak darurat tidak boleh memiliki nomor yang sama.",
    errNameChars: "Nama hanya boleh berisi huruf, spasi, dan titik.",
    errNameShort: "Tulis setiap nama secara lengkap: setiap nama minimal dua huruf.",
    reqTitle: "Tambahkan kontak darurat Anda",
    reqSub: "Kini kami meminta setiap pesepeda mencantumkan seseorang yang bisa kami hubungi jika Anda butuh bantuan saat bersepeda atau di sebuah acara. Cukup tambahkan sekali, lalu Anda bisa memesan.",
    save: "Simpan",
    dialCode: "Kode negara",
  },
  ms: {
    title: "Kenalan kecemasan",
    sub: "Seseorang yang boleh kami hubungi jika anda memerlukan bantuan di sesuatu acara.",
    name: "Nama kenalan",
    phone: "Nombor telefon bimbit kenalan",
    relation: "Hubungan dengan anda",
    pick: "Pilih",
    rel: {spouse: "Suami atau isteri", parent: "Ibu atau bapa", sibling: "Adik-beradik", child: "Anak", relative: "Saudara-mara", friend: "Kawan", colleague: "Rakan sekerja", other: "Lain-lain"},
    title2: "Kenalan kecemasan kedua",
    sub2: "Seorang lagi yang boleh kami hubungi jika kami tidak dapat menghubungi kenalan pertama anda.",
    add2: "Tambah kenalan kedua",
    optional: "pilihan",
    errName: "Masukkan nama kenalan anda.",
    errPhone: "Masukkan nombor telefon bimbit kenalan anda.",
    errRelation: "Pilih hubungan mereka dengan anda.",
    errSelf: "Nombor kenalan tidak boleh nombor anda sendiri.",
    errSame: "Kedua-dua kenalan kecemasan tidak boleh mempunyai nombor yang sama.",
    errNameChars: "Nama hanya boleh mengandungi huruf, ruang dan noktah.",
    errNameShort: "Tulis setiap nama dengan penuh: setiap nama perlu sekurang-kurangnya dua huruf.",
    reqTitle: "Tambah kenalan kecemasan anda",
    reqSub: "Kini kami meminta setiap penunggang memberikan seseorang yang boleh kami hubungi jika anda memerlukan bantuan semasa tunggangan atau acara. Tambah sekali sahaja dan anda boleh membuat tempahan.",
    save: "Simpan",
    dialCode: "Kod negara",
  },
  de: {
    title: "Notfallkontakt",
    sub: "Jemand, den wir anrufen können, falls du bei einem Event Hilfe brauchst.",
    name: "Name des Kontakts",
    phone: "Handynummer des Kontakts",
    relation: "Beziehung zu dir",
    pick: "Auswählen",
    rel: {spouse: "Ehepartner(in)", parent: "Mutter oder Vater", sibling: "Bruder oder Schwester", child: "Sohn oder Tochter", relative: "Verwandte(r)", friend: "Freund(in)", colleague: "Kollege oder Kollegin", other: "Andere"},
    title2: "Zweiter Notfallkontakt",
    sub2: "Eine weitere Person, die wir anrufen können, falls wir deinen ersten Kontakt nicht erreichen.",
    add2: "Zweiten Kontakt hinzufügen",
    optional: "optional",
    errName: "Gib den Namen deines Kontakts ein.",
    errPhone: "Gib die Handynummer deines Kontakts ein.",
    errRelation: "Wähle aus, in welcher Beziehung ihr zueinander steht.",
    errSelf: "Die Nummer deines Kontakts darf nicht deine eigene sein.",
    errSame: "Die beiden Notfallkontakte dürfen nicht dieselbe Nummer haben.",
    errNameChars: "Namen dürfen nur Buchstaben, Leerzeichen und Punkte enthalten.",
    errNameShort: "Schreibe jeden Namen aus: Jeder Name braucht mindestens zwei Buchstaben.",
    reqTitle: "Füge deinen Notfallkontakt hinzu",
    reqSub: "Wir bitten jetzt alle Fahrer um eine Person, die wir anrufen können, falls du bei einer Fahrt oder einem Event Hilfe brauchst. Einmal hinzufügen, dann kannst du buchen.",
    save: "Speichern",
    dialCode: "Ländervorwahl",
  },
  es: {
    title: "Contacto de emergencia",
    sub: "Alguien a quien podamos llamar si necesitas ayuda en un evento.",
    name: "Nombre del contacto",
    phone: "Móvil del contacto",
    relation: "Relación contigo",
    pick: "Elegir",
    rel: {spouse: "Cónyuge", parent: "Padre o madre", sibling: "Hermano o hermana", child: "Hijo o hija", relative: "Familiar", friend: "Amigo o amiga", colleague: "Compañero de trabajo", other: "Otro"},
    title2: "Segundo contacto de emergencia",
    sub2: "Otra persona a la que podamos llamar si no localizamos a tu primer contacto.",
    add2: "Añadir un segundo contacto",
    optional: "opcional",
    errName: "Escribe el nombre de tu contacto.",
    errPhone: "Escribe el móvil de tu contacto.",
    errRelation: "Elige tu relación con esa persona.",
    errSelf: "El número de tu contacto no puede ser el tuyo.",
    errSame: "Los dos contactos de emergencia no pueden tener el mismo número.",
    errNameChars: "El nombre solo puede contener letras, espacios y puntos.",
    errNameShort: "Escribe cada nombre completo: cada nombre necesita al menos dos letras.",
    reqTitle: "Añade tu contacto de emergencia",
    reqSub: "Ahora pedimos a cada participante una persona a la que llamar si necesita ayuda en una salida o evento. Añádela una vez y podrás reservar.",
    save: "Guardar",
    dialCode: "Código de país",
  },
  fr: {
    title: "Contact d’urgence",
    sub: "Une personne à appeler si vous avez besoin d’aide lors d’un événement.",
    name: "Nom du contact",
    phone: "Mobile du contact",
    relation: "Lien avec vous",
    pick: "Choisir",
    rel: {spouse: "Époux ou épouse", parent: "Parent", sibling: "Frère ou sœur", child: "Fils ou fille", relative: "Membre de la famille", friend: "Ami ou amie", colleague: "Collègue", other: "Autre"},
    title2: "Second contact d’urgence",
    sub2: "Une autre personne à appeler si nous ne parvenons pas à joindre votre premier contact.",
    add2: "Ajouter un second contact",
    optional: "facultatif",
    errName: "Indiquez le nom de votre contact.",
    errPhone: "Indiquez le numéro de mobile de votre contact.",
    errRelation: "Indiquez votre lien avec cette personne.",
    errSelf: "Le numéro de votre contact ne peut pas être le vôtre.",
    errSame: "Les deux contacts d’urgence ne peuvent pas avoir le même numéro.",
    errNameChars: "Le nom ne peut contenir que des lettres, des espaces et des points.",
    errNameShort: "Écrivez chaque nom en entier : chaque nom doit compter au moins deux lettres.",
    reqTitle: "Ajoutez votre contact d’urgence",
    reqSub: "Nous demandons désormais à chaque participant une personne à appeler s’il a besoin d’aide lors d’une sortie ou d’un événement. Ajoutez-la une fois et vous pourrez réserver.",
    save: "Enregistrer",
    dialCode: "Indicatif du pays",
  },
  pt: {
    title: "Contato de emergência",
    sub: "Alguém para quem possamos ligar se você precisar de ajuda em um evento.",
    name: "Nome do contato",
    phone: "Celular do contato",
    relation: "Relação com você",
    pick: "Escolher",
    rel: {spouse: "Cônjuge", parent: "Pai ou mãe", sibling: "Irmão ou irmã", child: "Filho ou filha", relative: "Parente", friend: "Amigo ou amiga", colleague: "Colega de trabalho", other: "Outro"},
    title2: "Segundo contato de emergência",
    sub2: "Outra pessoa para quem podemos ligar se não conseguirmos falar com o seu primeiro contato.",
    add2: "Adicionar um segundo contato",
    optional: "opcional",
    errName: "Informe o nome do seu contato.",
    errPhone: "Informe o celular do seu contato.",
    errRelation: "Escolha a sua relação com essa pessoa.",
    errSelf: "O número do contato não pode ser o seu.",
    errSame: "Os dois contatos de emergência não podem ter o mesmo número.",
    errNameChars: "O nome só pode conter letras, espaços e pontos.",
    errNameShort: "Escreva cada nome por completo: cada nome precisa ter pelo menos duas letras.",
    reqTitle: "Adicione o seu contacto de emergência",
    reqSub: "Agora pedimos a cada participante uma pessoa a quem ligar se precisar de ajuda num passeio ou evento. Adicione-a uma vez e já pode reservar.",
    save: "Salvar",
    dialCode: "Código do país",
  },
  tl: {
    title: "Emergency contact",
    sub: "Isang taong matatawagan namin kung kailangan mo ng tulong sa isang event.",
    name: "Pangalan ng contact",
    phone: "Mobile number ng contact",
    relation: "Kaugnayan sa iyo",
    pick: "Pumili",
    rel: {spouse: "Asawa", parent: "Magulang", sibling: "Kapatid", child: "Anak", relative: "Kamag-anak", friend: "Kaibigan", colleague: "Katrabaho", other: "Iba pa"},
    title2: "Pangalawang emergency contact",
    sub2: "Ibang taong matatawagan namin kung hindi namin makontak ang una mong contact.",
    add2: "Magdagdag ng pangalawang contact",
    optional: "opsyonal",
    errName: "Ilagay ang pangalan ng contact mo.",
    errPhone: "Ilagay ang mobile number ng contact mo.",
    errRelation: "Piliin ang kaugnayan niya sa iyo.",
    errSelf: "Hindi puwedeng sarili mong numero ang numero ng contact.",
    errSame: "Hindi puwedeng iisa ang numero ng dalawang emergency contact.",
    errNameChars: "Mga titik, espasyo at tuldok lamang ang puwede sa pangalan.",
    errNameShort: "Isulat nang buo ang bawat pangalan: kailangang may hindi bababa sa dalawang titik ang bawat pangalan.",
    reqTitle: "Idagdag ang iyong emergency contact",
    reqSub: "Hinihingi na namin sa bawat rider ang isang taong matatawagan namin kung kailangan mo ng tulong sa isang ride o event. Idagdag ito nang isang beses at makakapag-book ka na.",
    save: "I-save",
    dialCode: "Code ng bansa",
  },
  ru: {
    title: "Экстренный контакт",
    sub: "Человек, которому мы сможем позвонить, если вам понадобится помощь на мероприятии.",
    name: "Имя контакта",
    phone: "Мобильный номер контакта",
    relation: "Кем приходится вам",
    pick: "Выберите",
    rel: {spouse: "Супруг или супруга", parent: "Отец или мать", sibling: "Брат или сестра", child: "Сын или дочь", relative: "Родственник", friend: "Друг", colleague: "Коллега", other: "Другое"},
    title2: "Второй экстренный контакт",
    sub2: "Ещё один человек, которому мы позвоним, если не дозвонимся до первого контакта.",
    add2: "Добавить второй контакт",
    optional: "необязательно",
    errName: "Укажите имя контакта.",
    errPhone: "Укажите мобильный номер контакта.",
    errRelation: "Выберите, кем вам приходится этот человек.",
    errSelf: "Номер контакта не может совпадать с вашим.",
    errSame: "У двух экстренных контактов не может быть одного номера.",
    errNameChars: "Имя может содержать только буквы, пробелы и точки.",
    errNameShort: "Пишите каждое имя полностью: в каждом имени не меньше двух букв.",
    reqTitle: "Добавьте экстренный контакт",
    reqSub: "Теперь мы просим каждого райдера указать человека, которому можно позвонить, если вам понадобится помощь на заезде или мероприятии. Добавьте его один раз — и можно бронировать.",
    save: "Сохранить",
    dialCode: "Код страны",
  },
  ur: {
    title: "ہنگامی رابطہ",
    sub: "کوئی ایسا شخص جسے ہم کسی ایونٹ میں آپ کو مدد کی ضرورت ہو تو کال کر سکیں۔",
    name: "رابطے کا نام",
    phone: "رابطے کا موبائل نمبر",
    relation: "آپ سے رشتہ",
    pick: "منتخب کریں",
    rel: {spouse: "شریکِ حیات", parent: "والد یا والدہ", sibling: "بھائی یا بہن", child: "بیٹا یا بیٹی", relative: "رشتہ دار", friend: "دوست", colleague: "ساتھی کارکن", other: "دیگر"},
    title2: "دوسرا ہنگامی رابطہ",
    sub2: "کوئی اور شخص جسے ہم کال کر سکیں اگر آپ کے پہلے رابطے سے بات نہ ہو سکے۔",
    add2: "دوسرا رابطہ شامل کریں",
    optional: "اختیاری",
    errName: "اپنے رابطے کا نام درج کریں۔",
    errPhone: "اپنے رابطے کا موبائل نمبر درج کریں۔",
    errRelation: "منتخب کریں کہ وہ آپ کے کیا لگتے ہیں۔",
    errSelf: "رابطے کا نمبر آپ کا اپنا نمبر نہیں ہو سکتا۔",
    errSame: "دونوں ہنگامی رابطوں کا نمبر ایک نہیں ہو سکتا۔",
    errNameChars: "نام میں صرف حروف، خالی جگہ اور نقطے (.) ہو سکتے ہیں۔",
    errNameShort: "ہر نام پورا لکھیں: ہر نام میں کم از کم دو حروف ہونے چاہییں۔",
    reqTitle: "اپنا ہنگامی رابطہ شامل کریں",
    reqSub: "اب ہم ہر رائیڈر سے کسی ایسے شخص کی معلومات لیتے ہیں جسے رائیڈ یا ایونٹ میں آپ کو مدد کی ضرورت ہو تو ہم کال کر سکیں۔ اسے ایک بار شامل کریں اور آپ بکنگ کر سکیں گے۔",
    save: "محفوظ کریں",
    dialCode: "ملک کا کوڈ",
  },
  hi: {
    title: "आपातकालीन संपर्क",
    sub: "कोई ऐसा व्यक्ति जिसे किसी इवेंट में आपको मदद चाहिए तो हम कॉल कर सकें।",
    name: "संपर्क का नाम",
    phone: "संपर्क का मोबाइल नंबर",
    relation: "आपसे संबंध",
    pick: "चुनें",
    rel: {spouse: "पति या पत्नी", parent: "माता या पिता", sibling: "भाई या बहन", child: "बेटा या बेटी", relative: "रिश्तेदार", friend: "मित्र", colleague: "सहकर्मी", other: "अन्य"},
    title2: "दूसरा आपातकालीन संपर्क",
    sub2: "कोई और व्यक्ति जिसे हम कॉल कर सकें, अगर आपके पहले संपर्क से बात न हो पाए।",
    add2: "दूसरा संपर्क जोड़ें",
    optional: "वैकल्पिक",
    errName: "अपने संपर्क का नाम दर्ज करें।",
    errPhone: "अपने संपर्क का मोबाइल नंबर दर्ज करें।",
    errRelation: "चुनें कि वे आपके क्या लगते हैं।",
    errSelf: "संपर्क का नंबर आपका अपना नंबर नहीं हो सकता।",
    errSame: "दोनों आपातकालीन संपर्कों का नंबर एक नहीं हो सकता।",
    errNameChars: "नाम में केवल अक्षर, रिक्त स्थान और बिंदु (.) हो सकते हैं।",
    errNameShort: "हर नाम पूरा लिखें: हर नाम में कम से कम दो अक्षर होने चाहिए।",
    reqTitle: "अपना आपातकालीन संपर्क जोड़ें",
    reqSub: "अब हम हर राइडर से किसी ऐसे व्यक्ति की जानकारी लेते हैं जिसे राइड या इवेंट में आपको मदद की ज़रूरत होने पर हम कॉल कर सकें। इसे एक बार जोड़ें और आप बुक कर सकेंगे।",
    save: "सहेजें",
    dialCode: "देश कोड",
  },
  ne: {
    title: "आपतकालीन सम्पर्क",
    sub: "कुनै कार्यक्रममा तपाईंलाई सहयोग चाहिएमा हामीले फोन गर्न सक्ने व्यक्ति।",
    name: "सम्पर्क व्यक्तिको नाम",
    phone: "सम्पर्क व्यक्तिको मोबाइल नम्बर",
    relation: "तपाईंसँगको नाता",
    pick: "छान्नुहोस्",
    rel: {spouse: "श्रीमान् वा श्रीमती", parent: "बुबा वा आमा", sibling: "दाजुभाइ वा दिदीबहिनी", child: "छोरा वा छोरी", relative: "आफन्त", friend: "साथी", colleague: "सहकर्मी", other: "अन्य"},
    title2: "दोस्रो आपतकालीन सम्पर्क",
    sub2: "अर्को व्यक्ति जसलाई हामी फोन गर्न सक्छौँ, यदि तपाईंको पहिलो सम्पर्कमा पुग्न सकिएन भने।",
    add2: "दोस्रो सम्पर्क थप्नुहोस्",
    optional: "वैकल्पिक",
    errName: "आफ्नो सम्पर्क व्यक्तिको नाम लेख्नुहोस्।",
    errPhone: "आफ्नो सम्पर्क व्यक्तिको मोबाइल नम्बर लेख्नुहोस्।",
    errRelation: "उहाँ तपाईंको को हुनुहुन्छ, छान्नुहोस्।",
    errSelf: "सम्पर्क व्यक्तिको नम्बर तपाईंको आफ्नै नम्बर हुन सक्दैन।",
    errSame: "दुवै आपतकालीन सम्पर्कको नम्बर एउटै हुन सक्दैन।",
    errNameChars: "नाममा अक्षर, खाली ठाउँ र बिन्दु (.) मात्र हुन सक्छन्।",
    errNameShort: "हरेक नाम पूरा लेख्नुहोस्: हरेक नाममा कम्तीमा दुई अक्षर हुनुपर्छ।",
    reqTitle: "आफ्नो आपतकालीन सम्पर्क थप्नुहोस्",
    reqSub: "अब हामी हरेक राइडरसँग यस्तो व्यक्तिको विवरण माग्छौं जसलाई राइड वा कार्यक्रममा तपाईंलाई सहयोग चाहिएमा हामी फोन गर्न सकौं। एक पटक थप्नुहोस्, अनि बुक गर्न सक्नुहुन्छ।",
    save: "सेभ",
    dialCode: "देश कोड",
  },
  bn: {
    title: "জরুরি যোগাযোগ",
    sub: "কোনো ইভেন্টে আপনার সাহায্য দরকার হলে আমরা যাকে ফোন করতে পারি।",
    name: "যোগাযোগের ব্যক্তির নাম",
    phone: "যোগাযোগের ব্যক্তির মোবাইল নম্বর",
    relation: "আপনার সাথে সম্পর্ক",
    pick: "বেছে নিন",
    rel: {spouse: "স্বামী বা স্ত্রী", parent: "বাবা বা মা", sibling: "ভাই বা বোন", child: "ছেলে বা মেয়ে", relative: "আত্মীয়", friend: "বন্ধু", colleague: "সহকর্মী", other: "অন্যান্য"},
    title2: "দ্বিতীয় জরুরি যোগাযোগ",
    sub2: "আপনার প্রথম যোগাযোগকে না পেলে আমরা যাকে ফোন করতে পারি এমন আরেকজন।",
    add2: "দ্বিতীয় যোগাযোগ যোগ করুন",
    optional: "ঐচ্ছিক",
    errName: "আপনার যোগাযোগের ব্যক্তির নাম লিখুন।",
    errPhone: "আপনার যোগাযোগের ব্যক্তির মোবাইল নম্বর লিখুন।",
    errRelation: "তিনি আপনার কী হন, বেছে নিন।",
    errSelf: "যোগাযোগের নম্বর আপনার নিজের নম্বর হতে পারে না।",
    errSame: "দুটি জরুরি যোগাযোগের নম্বর একই হতে পারে না।",
    errNameChars: "নামে শুধু অক্ষর, ফাঁকা জায়গা ও বিন্দু (.) থাকতে পারে।",
    errNameShort: "প্রতিটি নাম পুরোটা লিখুন: প্রতিটি নামে অন্তত দুটি অক্ষর থাকতে হবে।",
    reqTitle: "আপনার জরুরি যোগাযোগ যোগ করুন",
    reqSub: "এখন আমরা প্রত্যেক রাইডারের কাছে এমন একজনের তথ্য চাই, রাইড বা ইভেন্টে আপনার সাহায্য দরকার হলে যাঁকে আমরা ফোন করতে পারি। একবার যোগ করলেই আপনি বুক করতে পারবেন।",
    save: "সংরক্ষণ করুন",
    dialCode: "দেশের কোড",
  },
  zh: {
    title: "紧急联系人",
    sub: "您在活动中需要帮助时，我们可以联系的人。",
    name: "联系人姓名",
    phone: "联系人手机号码",
    relation: "与您的关系",
    pick: "请选择",
    rel: {spouse: "配偶", parent: "父母", sibling: "兄弟姐妹", child: "子女", relative: "亲属", friend: "朋友", colleague: "同事", other: "其他"},
    title2: "第二紧急联系人",
    sub2: "联系不上您的第一联系人时，我们可以联系的另一个人。",
    add2: "添加第二联系人",
    optional: "选填",
    errName: "请输入联系人的姓名。",
    errPhone: "请输入联系人的手机号码。",
    errRelation: "请选择对方与您的关系。",
    errSelf: "联系人的号码不能是您自己的号码。",
    errSame: "两位紧急联系人的号码不能相同。",
    errNameChars: "姓名只能包含字母、空格和句点。",
    errNameShort: "请写出完整姓名：每个名字至少两个字母。",
    reqTitle: "添加您的紧急联系人",
    reqSub: "现在我们请每位骑手提供一位联系人，以便您在骑行或活动中需要帮助时联系。只需添加一次，即可预订。",
    save: "保存",
    dialCode: "国家/地区代码",
  },
  ja: {
    title: "緊急連絡先",
    sub: "イベント中にお困りの際、こちらから連絡できる方。",
    name: "連絡先の方のお名前",
    phone: "連絡先の方の携帯電話番号",
    relation: "あなたとの関係",
    pick: "選択してください",
    rel: {spouse: "配偶者", parent: "父または母", sibling: "兄弟姉妹", child: "息子または娘", relative: "親族", friend: "友人", colleague: "同僚", other: "その他"},
    title2: "2人目の緊急連絡先",
    sub2: "1人目の連絡先につながらない場合に連絡できる別の方。",
    add2: "2人目の連絡先を追加",
    optional: "任意",
    errName: "連絡先の方のお名前を入力してください。",
    errPhone: "連絡先の方の携帯電話番号を入力してください。",
    errRelation: "あなたとの関係を選択してください。",
    errSelf: "連絡先の番号にご自身の番号は使えません。",
    errSame: "2人の緊急連絡先に同じ番号は使えません。",
    errNameChars: "名前に使えるのは文字、スペース、ピリオドのみです。",
    errNameShort: "名前は省略せずに入力してください。各名前は2文字以上必要です。",
    reqTitle: "緊急連絡先を追加してください",
    reqSub: "ライドやイベントでお困りの際に連絡できる方の登録を、すべてのライダーにお願いしています。一度追加すれば予約できます。",
    save: "保存",
    dialCode: "国番号",
  },
};

export const emergencyWords = (locale: string): EmergencyWords => EMERGENCY_WORDS[locale as Locale] ?? EMERGENCY_WORDS.en;
