// My Account's record (components/account/RideRecord.tsx): Your rides and the closest badges, in
// the booking app's own English and Arabic (myr*, bdNextTitle, and each badge's name and how it is
// earned: BD_SYS keys and their D lines); every other language translates the English.
export const T = {
  en: {
    yourRides: "Your rides",
    weeks: (n: string) => `${n} of the last 26 weeks with a ride`,
    year: "Rides this year",
    fav: "Favourite bike",
    time: "Time on the bike",
    first: "First ride",
    closest: "Closest badges",
    names: {
      firstLap: ["First Lap", "Completed your first circuit ride"],
      regular: ["Grid Regular", "Completed 5 rides"],
      podium: ["Podium Pace", "Completed 10 rides"],
      streak: ["Hot Streak", "Rode 3 weeks in a row"],
      corniche25: ["Corniche 25", "25 rides on the corniche"],
      safetyCar: ["Safety Car", "Rode 6 weeks running (one quiet week in four is forgiven)"],
      endurance: ["Endurance", "Rode 12 weeks running (one quiet week in four is forgiven)"],
      tripleCrown: ["Triple Crown", "Rode three different kinds of ride"],
      cleanSheet: ["Clean Sheet", "10 rides in a row with no missed booking"],
      slipstream: ["Slipstream", "5 community rides"],
      paceline: ["Paceline", "15 community rides"],
      peloton: ["Peloton", "30 community rides"],
      worksTeam: ["Works Team", "3 company rides"],
      perfectWeek: ["Perfect Week", "Every session in one week, Sunday to Saturday"],
      perfectMonth: ["Perfect Month", "A Perfect Week four weeks in a row"],
      winterSeries: ["Winter Series", "6 rides in one winter, December to February"],
      ramadanNights: ["Ramadan Nights", "3 rides during Ramadan"],
      foundingDay: ["Founding Day", "A ride around Founding Day, 18 to 28 February"],
    } as Record<string, [string, string]>,
  },
  ar: {
    yourRides: "رحلاتك",
    weeks: (n: string) => `${n} من آخر 26 أسبوعاً فيها رحلة`,
    year: "رحلات هذا العام",
    fav: "دراجتك المفضلة",
    time: "الوقت على الدراجة",
    first: "أول رحلة",
    closest: "أقرب الأوسمة",
    names: {
      firstLap: ["اللفة الأولى", "أكملت أول رحلة لك في الحلبة"],
      regular: ["منتظم الحلبة", "أكملت 5 رحلات"],
      podium: ["إيقاع المنصة", "أكملت 10 رحلات"],
      streak: ["حماس متواصل", "ركبت 3 أسابيع متتالية"],
      corniche25: ["كورنيش 25", "25 رحلة على الكورنيش"],
      safetyCar: ["سيارة الأمان", "ركبت 6 أسابيع متتالية (يُغفر أسبوع هادئ واحد من كل أربعة)"],
      endurance: ["التحمّل", "ركبت 12 أسبوعاً متتالية (يُغفر أسبوع هادئ واحد من كل أربعة)"],
      tripleCrown: ["التاج الثلاثي", "ركبت ثلاثة أنواع مختلفة من الرحلات"],
      cleanSheet: ["سجل نظيف", "10 رحلات متتالية دون تفويت أي حجز"],
      slipstream: ["التيار الهوائي", "5 رحلات مجتمعية"],
      paceline: ["خط الإيقاع", "15 رحلة مجتمعية"],
      peloton: ["البيلوتون", "30 رحلة مجتمعية"],
      worksTeam: ["فريق الشركة", "3 رحلات للشركات"],
      perfectWeek: ["الأسبوع المثالي", "كل جلسات الأسبوع، من الأحد إلى السبت"],
      perfectMonth: ["الشهر المثالي", "أسبوع مثالي أربعة أسابيع متتالية"],
      winterSeries: ["سلسلة الشتاء", "6 رحلات في شتاء واحد، من ديسمبر إلى فبراير"],
      ramadanNights: ["ليالي رمضان", "3 رحلات خلال رمضان"],
      foundingDay: ["يوم التأسيس", "رحلة في أيام يوم التأسيس، من 18 إلى 28 فبراير"],
    } as Record<string, [string, string]>,
  },
};
