// My Account's record (components/account/RideRecord.tsx, BadgeGrid.tsx): Your rides, the closest
// badges and every badge, in the booking app's own English and Arabic (myr*, bdNextTitle, the badge
// popup's words, and each app badge's name, how it is earned and what it means: BD_SYS keys with
// their D and A lines, by slug). Every other language translates the English.
export const T = {
  en: {
    yourRides: "Your rides",
    weeks: (n: string) => `${n} of the last 26 weeks with a ride`,
    year: "Rides this year",
    fav: "Favourite bike",
    time: "Time on the bike",
    first: "First ride",
    closest: "Closest badges",
    badges: "Badges",
    toEarn: "Badges to earn",
    show: "Show",
    hide: "Hide",
    notEarned: "not earned yet",
    howTo: "How to earn",
    earned: "Earned",
    close: "Close",
    seasonOpen: "On now, until {0}",
    seasonSoon: "Opens {0}",
    givenBy: "Given by the MicroMobility team · {0}",
    names: {
      first_lap: ["First Lap", "Completed your first circuit ride", "Every rider's story starts with one lap: the first ride you finished with us."],
      regular: ["Grid Regular", "Completed 5 rides", "In motor racing, the grid is where the cars line up to start. Five rides make you a regular at the start line."],
      podium: ["Podium Pace", "Completed 10 rides", "The podium is where the top finishers stand. Ten rides put you among our most dedicated riders."],
      front_row: ["Front Row", "Held booking #1 in a session", "The front row of the grid starts ahead of everyone: you were first in the queue for a ride."],
      carbon: ["Carbon Club", "Rode the Road Carbon", "Race bikes are made of carbon: light and fast. For riders who took out our Road Carbon."],
      streak: ["Hot Streak", "Rode 3 weeks in a row", "Riding week after week builds a habit. Three weeks running lights the flame."],
      squad: ["Squad Captain", "Booked for 3+ riders at once", "Riding is better together: for bringing three or more riders to one ride."],
      fuel: ["Fuel Stop", "Added extras to a booking", "Every racer needs a pit stop: for adding a drink or snack to your booking."],
      corniche25: ["Corniche 25", "25 rides on the corniche", "Twenty-five rides along the Jeddah Corniche. You know this road by heart."],
      marshal: ["Marshal", "Led or swept a group ride, or helped run an event", "Marshals keep a race safe and running. Given by the team to riders who lead, sweep or help at events."],
      pit_crew: ["Pit Crew", "Helped another rider out on a ride", "A pit crew gets a car back in the race. Given for stopping to help another rider."],
      green_flag: ["Green Flag", "Rode with care for the people around you", "The green flag means the track is clear. Given for riding with care for walkers and other riders."],
      super_licence: ["Super Licence", "Finished Learn to ride and now rides on your own", "Racing drivers need a super licence to race at the top. Given when a Learn to ride graduate rides alone."],
      scrutineer: ["Scrutineer", "Reported a bike fault the team confirmed", "Scrutineers check every car before a race. Given for spotting a bike fault the team then fixed."],
      champion: ["Champion", "Won a MicroMobility challenge or event", "A champion's badge, given by the team for winning one of our challenges or events."],
      spirit: ["Race Spirit", "Showed great sportsmanship on a ride", "Sportsmanship matters more than speed. Given for cheering others on and lifting the whole ride."],
      complete_profile: ["Race Ready", "Filled in every part of your profile", "A complete profile helps us fit your bike and keep your rides safe. Fill in every part to earn it."],
      national_day_96: ["National Day 96", "Rode in the Saudi National Day 96 Ride", "On 23 September 2026 riders filled the Corniche in green for Saudi National Day 96. A keepsake for everyone who rode in the parade."],
      run_for_her: ["Run for Her", "Finish the Run for Her.", "The pink ribbon, for everyone who ran and finished the Run for Her with the MicroMobility community."],
      back_on_track: ["Back on Track", "Came back for a ride after two months away", "Life gets busy. This one welcomes you back on the bike after two months or more away."],
      safety_car: ["Safety Car", "Rode 6 weeks running (one quiet week in four is forgiven)", "When the safety car is out, the race slows but doesn't stop: a quiet week won't break your run."],
      endurance: ["Endurance", "Rode 12 weeks running (one quiet week in four is forgiven)", "Endurance races reward those who keep going: twelve weeks of riding, one quiet week in four allowed."],
      triple_crown: ["Triple Crown", "Rode three different kinds of ride", "A crown for variety: three kinds of ride, like a regular ride, a community ride and an event."],
      slipstream: ["Slipstream", "5 community rides", "Riding behind others saves effort: that's the slipstream. For riders who join our community rides."],
      paceline: ["Paceline", "15 community rides", "A paceline is a group taking turns at the front. Fifteen community rides make you part of it."],
      peloton: ["Peloton", "30 community rides", "The peloton is the main pack of a race. Thirty community rides put you at its heart."],
      clean_sheet: ["Clean Sheet", "10 rides in a row with no missed booking", "Turning up when you book keeps places fair for everyone: ten rides in a row, none missed."],
      works_team: ["Works Team", "3 company rides", "A works team races for a company: for riders who come to their company's ride nights."],
      perfect_week: ["Perfect Week", "Every session in one week, Sunday to Saturday", "Every ride, swim and workshop the week held, and you were at all of them. A week with fewer than two sessions does not count."],
      perfect_month: ["Perfect Month", "A Perfect Week four weeks in a row", "Four Perfect Weeks back to back. A week with fewer than two sessions is skipped and does not break the run."],
      winter_series: ["Winter Series", "6 rides in one winter, December to February", "Jeddah's winter is the best time to ride. A seasonal badge for riding December to February."],
      ramadan_nights: ["Ramadan Nights", "3 rides during Ramadan", "Ramadan evenings are lovely for a ride. A seasonal badge for riding with us through the month."],
      founding_day: ["Founding Day", "A ride around Founding Day, 18 to 28 February", "Saudi Founding Day is 22 February. A seasonal badge for riding with us around it."],
    } as Record<string, [string, string, string]>,
  },
  ar: {
    yourRides: "رحلاتك",
    weeks: (n: string) => `${n} من آخر 26 أسبوعاً فيها رحلة`,
    year: "رحلات هذا العام",
    fav: "دراجتك المفضلة",
    time: "الوقت على الدراجة",
    first: "أول رحلة",
    closest: "أقرب الأوسمة",
    badges: "الأوسمة",
    toEarn: "أوسمة بانتظارك",
    show: "إظهار",
    hide: "إخفاء",
    notEarned: "لم تُكتسب بعد",
    howTo: "كيف تحصل عليه",
    earned: "حصلت عليه",
    close: "إغلاق",
    seasonOpen: "متاح الآن حتى {0}",
    seasonSoon: "يبدأ {0}",
    givenBy: "مُنح من فريق مايكروموبيليتي · {0}",
    names: {
      first_lap: ["اللفة الأولى", "أكملت أول رحلة لك في الحلبة", "كل قصة راكب تبدأ بلفة واحدة: أول رحلة أكملتها معنا."],
      regular: ["منتظم الحلبة", "أكملت 5 رحلات", "في سباقات السيارات، الغريد هو خط الانطلاق الذي تصطف عنده السيارات. خمس رحلات تجعلك وجهاً مألوفاً عند خط الانطلاق."],
      podium: ["إيقاع المنصة", "أكملت 10 رحلات", "منصة التتويج لأصحاب المراكز الأولى. عشر رحلات تضعك بين أكثر راكبينا التزاماً."],
      front_row: ["الصف الأول", "حصلت على الحجز رقم 1 في جلسة", "الصف الأول ينطلق قبل الجميع: كنت الأول في طابور إحدى الرحلات."],
      carbon: ["نادي الكربون", "ركبت درّاجة الرود كاربون", "دراجات السباق مصنوعة من الكربون: خفيفة وسريعة. للراكبين الذين جرّبوا دراجة الرود كاربون."],
      streak: ["حماس متواصل", "ركبت 3 أسابيع متتالية", "الركوب أسبوعاً بعد أسبوع يبني العادة. ثلاثة أسابيع متتالية تُشعل الشعلة."],
      squad: ["قائد المجموعة", "حجزت لـ3 رُكّاب أو أكثر دفعة واحدة", "الركوب أجمل مع الآخرين: لمن أحضر ثلاثة راكبين أو أكثر إلى رحلة واحدة."],
      fuel: ["محطة تزوّد", "أضفت إضافات إلى حجزك", "كل متسابق يحتاج إلى وقفة تزوّد: لمن أضاف مشروباً أو وجبة خفيفة إلى حجزه."],
      corniche25: ["كورنيش 25", "25 رحلة على الكورنيش", "خمس وعشرون رحلة على كورنيش جدة. صرت تعرف هذا الطريق عن ظهر قلب."],
      marshal: ["المنظّم", "قدت رحلة جماعية أو تابعت مؤخرتها، أو ساعدت في تنظيم فعالية", "المنظّمون يحافظون على سلامة السباق وسيره. يمنحه الفريق لمن يقود الرحلة أو يتابع مؤخرتها أو يساعد في الفعاليات."],
      pit_crew: ["طاقم الصيانة", "ساعدت راكباً آخر خلال رحلة", "طاقم الصيانة يعيد السيارة إلى السباق. يُمنح لمن توقف ليساعد راكباً آخر."],
      green_flag: ["الراية الخضراء", "قدت بعناية واهتمام بمن حولك", "الراية الخضراء تعني أن المسار خالٍ. تُمنح لمن يقود بعناية بالمشاة والراكبين الآخرين."],
      super_licence: ["الرخصة الممتازة", "أنهيت برنامج تعلّم ركوب الدراجة وصرت تقودها وحدك", "يحتاج سائقو السباقات إلى رخصة خاصة للمنافسة في القمة. تُمنح لخريج برنامج تعلّم الركوب حين يقود وحده."],
      scrutineer: ["المُدقِّق", "أبلغت عن عطل في دراجة وأكّده الفريق", "المدقّقون يفحصون كل سيارة قبل السباق. يُمنح لمن لاحظ عطلاً في دراجة ثم أصلحه الفريق."],
      champion: ["البطل", "فزت في تحدٍّ أو فعالية من مايكروموبيليتي", "وسام الأبطال، يمنحه الفريق لمن فاز في أحد تحدياتنا أو فعالياتنا."],
      spirit: ["روح السباق", "أظهرت روحاً رياضية رائعة خلال رحلة", "الروح الرياضية أهم من السرعة. يُمنح لمن يشجّع الآخرين ويجعل الرحلة أجمل للجميع."],
      complete_profile: ["جاهز للسباق", "أكملت كل أجزاء ملفك الشخصي", "الملف المكتمل يساعدنا على اختيار دراجتك والحفاظ على سلامة رحلاتك. أكمل كل أجزائه لتحصل عليه."],
      national_day_96: ["اليوم الوطني 96", "شاركت في جولة اليوم الوطني السعودي 96", "في 23 سبتمبر 2026 ملأ الراكبون الكورنيش بالأخضر احتفالاً باليوم الوطني السعودي 96. تذكار لكل من شارك في المسيرة."],
      run_for_her: ["نركض لأجلها", "أكمل سباق نركض لأجلها.", "الشريط الوردي، لكل من ركض وأكمل سباق نركض لأجلها مع مجتمع مايكروموبيليتي."],
      back_on_track: ["العودة إلى المسار", "عدت للركوب بعد غياب شهرين", "الحياة تنشغل أحياناً. هذا الوسام يرحّب بعودتك إلى الدراجة بعد شهرين أو أكثر."],
      safety_car: ["سيارة الأمان", "ركبت 6 أسابيع متتالية (يُغفر أسبوع هادئ واحد من كل أربعة)", "حين تخرج سيارة الأمان يهدأ السباق ولا يتوقف: أسبوع هادئ لن يكسر سلسلتك."],
      endurance: ["التحمّل", "ركبت 12 أسبوعاً متتالية (يُغفر أسبوع هادئ واحد من كل أربعة)", "سباقات التحمّل تكافئ من يواصل: اثنا عشر أسبوعاً من الركوب مع أسبوع هادئ مسموح من كل أربعة."],
      triple_crown: ["التاج الثلاثي", "ركبت ثلاثة أنواع مختلفة من الرحلات", "تاج للتنويع: ثلاثة أنواع من الرحلات، مثل رحلة عادية ورحلة مجتمعية وفعالية."],
      slipstream: ["التيار الهوائي", "5 رحلات مجتمعية", "الركوب خلف الآخرين يوفّر الجهد، وهذا هو التيار الهوائي. لمن ينضم إلى رحلات المجتمع."],
      paceline: ["خط الإيقاع", "15 رحلة مجتمعية", "خط الإيقاع مجموعة تتناوب على المقدمة. خمس عشرة رحلة مجتمعية تجعلك جزءاً منه."],
      peloton: ["البيلوتون", "30 رحلة مجتمعية", "البيلوتون هو المجموعة الرئيسية في السباق. ثلاثون رحلة مجتمعية تضعك في قلبه."],
      clean_sheet: ["سجل نظيف", "10 رحلات متتالية دون تفويت أي حجز", "الحضور حين تحجز يُبقي الأماكن عادلة للجميع: عشر رحلات متتالية دون تفويت أي منها."],
      works_team: ["فريق الشركة", "3 رحلات للشركات", "فريق المصنع يتسابق باسم شركة: لمن يحضر ليالي الرحلات الخاصة بشركته."],
      perfect_week: ["الأسبوع المثالي", "كل جلسات الأسبوع، من الأحد إلى السبت", "كل رحلة وسباحة وورشة في الأسبوع، وكنت حاضرًا فيها كلها. لا يُحتسب أسبوع فيه أقل من جلستين."],
      perfect_month: ["الشهر المثالي", "أسبوع مثالي أربعة أسابيع متتالية", "أربعة أسابيع مثالية متتالية. الأسبوع الذي فيه أقل من جلستين يُتخطّى ولا يقطع السلسلة."],
      winter_series: ["سلسلة الشتاء", "6 رحلات في شتاء واحد، من ديسمبر إلى فبراير", "شتاء جدة أجمل وقت للركوب. وسام موسمي لمن يركب من ديسمبر إلى فبراير."],
      ramadan_nights: ["ليالي رمضان", "3 رحلات خلال رمضان", "أمسيات رمضان لطيفة للركوب. وسام موسمي لمن يركب معنا خلال الشهر."],
      founding_day: ["يوم التأسيس", "رحلة في أيام يوم التأسيس، من 18 إلى 28 فبراير", "يوم التأسيس السعودي في 22 فبراير. وسام موسمي لمن يركب معنا في أيامه."],
    } as Record<string, [string, string, string]>,
  },
};
