// Builds the one self-contained page the website serves at /community/registration:
//   design/index.html + styles.css + app.js + i18n.js + images, shared/shared.js -> src/page.html
// Usage: npm run build (in forms/community). Never edit src/page.html (or the website's copy) by hand.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const d = (f) => resolve(root, 'design', f);
let html = readFileSync(d('index.html'), 'utf8');
const css = readFileSync(d('styles.css'), 'utf8');
const js = readFileSync(d('app.js'), 'utf8');
const i18n = readFileSync(d('i18n.js'), 'utf8');
const shared = readFileSync(resolve(root, 'shared/shared.js'), 'utf8');

// Every translation carries every string the page shows, with the same {placeholders}.
const FORM_T = new Function(i18n + ';return FORM_T;')();
const SHARED = new Function(shared + ';return SHARED;')();
const keys = new Set();
for (const m of html.matchAll(/data-t(?:-placeholder|-aria)?="([^"]+)"/g)) keys.add(m[1]);
for (const m of js.matchAll(/tr\("([^"]+)"/g)) keys.add(m[1]);
for (const m of js.matchAll(/(?:hard|soft)(?:\["f-[a-z]+"\])?\s*[:=]\s*\["([^"]+)"/g)) keys.add(m[1]);
for (const m of js.matchAll(/"f-[a-z]+", \d, "([^"]+)"/g)) keys.add(m[1]);
for (const m of js.matchAll(/showBanner\("([^"]+)"/g)) keys.add(m[1]);
['dobErrFuture', 'dobErrYoung', 'privacyAckRequired', 'errPasswordLen', 'errPasswordMatch'].forEach((k) => keys.delete(k)); // the site's own strings (shared.js)
const ph = (s) => (s.match(/\{[a-z0-9]+\}/g) || []).sort().join(',');
const problems = [];
for (const { code } of SHARED.LANGS) {
  if (code === 'en') continue;
  const t = FORM_T[code];
  if (!t) { problems.push(`${code}: no translations`); continue; }
  for (const k of keys) {
    if (!t[k]) problems.push(`${code}: missing "${k}"`);
    else if (ph(t[k]) !== ph(k)) problems.push(`${code}: placeholders differ in "${k}"`);
  }
  for (const k of Object.keys(t)) if (!keys.has(k)) problems.push(`${code}: unused "${k}"`);
}
if (problems.length) { console.error(problems.slice(0, 40).join('\n')); process.exit(1); }

const mime = { png: 'image/png', svg: 'image/svg+xml', webp: 'image/webp' };
html = html.replace(/(src|href)="([^"]+\.(png|svg|webp))"/g, (m, attr, file, ext) => {
  if (/^(https?:)?\/\//.test(file)) return m;
  const p = d(file);
  if (!existsSync(p)) { console.error(`design/${file} not found`); process.exit(1); }
  return `${attr}="data:${mime[ext]};base64,${readFileSync(p).toString('base64')}"`;
});
html = html.replace('<link rel="stylesheet" href="styles.css">',
  () => '<meta name="robots" content="noindex">\n<link rel="preconnect" href="https://amyqxovbnlreassrqihr.supabase.co">\n<style>\n' + css + '\n</style>');
html = html.replace('<script src="shared.js"></script>\n<script src="i18n.js"></script>\n<script src="app.js"></script>',
  () => '<script>\n' + shared + '\n' + i18n + '\n</script>\n<script>\n' + js + '\n</script>');
if (/href="styles\.css"|src="(app|i18n|shared)\.js"/.test(html)) { console.error('could not inline the styles or scripts'); process.exit(1); }
new Function(js); new Function(i18n); // syntax
writeFileSync(resolve(root, 'src/page.html'), html);
// The website serves this page (apps/web/src/app/community/registration/route.ts): it bundles this module.
writeFileSync(resolve(root, '../../apps/web/src/forms/community-page.ts'),
  '// GENERATED by forms/community/scripts/build.mjs from src/page.html. Do not edit here:\n' +
  '// change the form in forms/community and run `npm run build` in forms/community.\n' +
  'const page: string = ' + JSON.stringify(html) + ';\nexport default page;\n');
console.log(`src/page.html and apps/web/src/forms/community-page.ts written (${(html.length / 1024).toFixed(0)} KB, ${keys.size} strings x ${SHARED.LANGS.length} languages). Commit both; the website serves the page from its next deploy.`);
