// The booking wizard's words, in English and Arabic exactly as the booking app writes them (its
// LANG en/ar keys named beside each group); every other language translates the English
// (src/i18n/tx). {0} and {1} are filled in by the wizard.
export const T = {
  en: {
    // regProg1-3 regStepOf regStep1Title regStep1Msg(Join) regStep2Title/Msg regStep3Title/Msg
    stepRide: "Ride",
    stepRiders: "Riders",
    stepConfirm: "Confirm",
    stepOf: "Step {0} of {1}",
    rideTitle: "Choose your ride",
    rideMsg: "Pick the day you want to ride.",
    rideMsgJoin: "Pick the day you would like to join.",
    ridersTitle: "Rider details",
    ridersMsg: "Tell us who is riding and their bike preference.",
    reviewTitle: "Review and confirm",
    reviewMsg: "Check everything below, then confirm your booking.",
    // regContinueBtn regBackBtn regReviewBtn regConfirmBtn pickRideFirst
    cont: "Continue",
    back: "Back",
    toReview: "Review booking",
    confirm: "Confirm booking",
    pickFirst: "Choose a ride above to continue.",
    allEvents: "All events",
    // the session card: availLabel waitlistLabel spotsLeft1/N rejCardNote ticketCollectAt priceFrom freeLabel partnerStf
    available: "Available",
    waitlist: "Waitlist",
    left1: "{0} spot left",
    leftN: "{0} spots left",
    rejCard: "Full for this week",
    collectFrom: "Collect bikes from {0}",
    from: "from {0}",
    free: "Free",
    perSeat: "{0} per seat",
    partner: "In partnership with Saudi Triathlon Federation",
    fullNote: "This ride is full. You can still reserve: you’ll join the waitlist, and if a place opens, staff may pick you.",
    noRides: "No rides are open for booking right now.",
    noRidesSub: "New dates go up on our Instagram first.",
    // numBikes groupCapHint jccCapNote qtyDecLabel qtyIncLabel
    numBikes: "Number of bikes",
    capNote: "One account can book up to {0} riders.",
    qtyDec: "Decrease number of bikes",
    qtyInc: "Increase number of bikes",
    // riderLabel riderName riderNamePlaceholder heightLabel heightHint heightPlaceholder cmUnit
    rider: "Rider",
    riderName: "Rider’s full name",
    riderNamePh: "Enter rider's full name",
    height: "Height",
    heightHint: "(sets the frame size)",
    heightPh: "Height in cm",
    cm: "cm",
    // bikeTypePref bikeInfoHint type* typeOwnPref
    typePref: "Bike type preference",
    typeHint: "New to cycling? Hybrid is the easiest choice. Tap the i beside a type to see the bike.",
    types: { Road: "Road", Hybrid: "Hybrid", Mountain: "Mountain", Kids: "Kids", "Road Carbon": "Road Carbon", Own: "I have my own bike", None: "" } as Record<string, string>,
    // the bike sheet: bikeInfo* closeBtn
    bikeAria: "About {0} bikes",
    bikeFleet: "Our Alvas fleet",
    bestFor: "Best for:",
    chooseBike: "Choose this bike",
    close: "Close",
    bikeInfo: {
      Road: { brief: "Drop handlebars, narrow tyres and a light, quick feel: built for speed on the smooth tarmac of the circuit, with a lower, forward riding position.", good: "Fast laps, fitness riding and riders who already feel at home on a road bike.", level: "For confident riders" },
      "Road Carbon": { brief: "Alvas X1 carbon frame and fork with aero tubes and endurance geometry, Shimano 105 gears (2×12), hydraulic disc brakes and 28 mm tyres. Light, stiff and fast, without the stretched-out position of a race bike.", good: "Experienced road riders who want the fastest bike on the circuit.", level: "For experienced riders" },
      Hybrid: { brief: "A light alloy frame, a flat handlebar and an upright position, wide tyres, easy gears and disc brakes. Easy, stable and comfortable.", good: "First-timers, relaxed laps and anyone who prefers comfort over speed.", level: "Beginner friendly · the easiest choice" },
      Mountain: { brief: "An alloy frame, a suspension fork, wide 2.1-inch tyres on 27.5 or 29-inch wheels, one-lever gears and disc brakes. Slower on tarmac, but the most stable and forgiving to handle.", good: "Riders who want a sturdy, confidence-giving bike, or who are used to mountain bikes.", level: "Easy to ride" },
      Kids: { brief: "A light alloy frame, easy gears, disc brakes and kids-sized grips and saddle, in sizes to match your child. Our team fits the right size at the stand.", good: "Young riders from 5 years old, riding with their family.", level: "For young riders" },
    } as Record<string, { brief: string; good: string; level: string }>,
    // the Saturday groups: rgLabel rgBeg rgInt rg*Brief rg*Place rgTurnLbl rgPickBtn rgInfoAria rtKm errPickGroup
    groupLabel: "Ride group",
    groups: { beg: "Beginners’ group", int: "Intermediates’ group" } as Record<string, string>,
    groupBrief: { beg: "From the meeting point to the Jeddah Yacht Club (JYC) and back to the meeting point, at an average speed of about 20 km/h.", int: "From the meeting point to just before the Marine Sciences roundabout, and back to the meeting point." } as Record<string, string>,
    groupPlace: { beg: "Jeddah Yacht Club", int: "Marine Sciences roundabout" } as Record<string, string>,
    turnPoint: "Turning point",
    chooseGroup: "Choose this group",
    groupAria: "About the {0}",
    km: "{0} km",
    kmLap: "{0} km a lap",
    route: "Route",
    // pricePerBike onTheHouseLabel payAtBoothLine payAtBoothFCFS bike
    pricePerBike: "Price per bike",
    onTheHouse: "On the house",
    payAtBooth: "You pay at the booth when you arrive.",
    fcfs: "Your bike type is a preference: bikes go out first come, first served, so come early for the best choice.",
    bike: "Bike",
    // promo*: the button says "Apply code" (TRANSLATING.md: "Apply" is applying to join)
    promo: "Promo code",
    promoApply: "Apply code",
    promoRemove: "Remove",
    discount: "Discount",
    promoMsg: {
      invalid: "Invalid or inactive code",
      expired: "That code has expired.",
      used_up: "That code has been fully used.",
      not_yours: "That code belongs to another account.",
    } as Record<string, string>,
    promoTypeOnly: "This code applies only to {0} bookings.",
    // waiverTitle/Body/Agree swimWaiver* waiverSub tickWaiverFirst waiverRequired
    waiver: {
      bike: { title: "Ride waiver", body: "I acknowledge that cycling is a physical activity that carries risk. I agree to wear a helmet, follow the team’s instructions and the circuit course, and I am responsible for my own safety and for any damage to the rented bike caused by misuse. The bike is returned in the condition it was received.", agree: "I have read the waiver and agree on behalf of every rider on this booking" },
      swim: { title: "Swim waiver", body: "I acknowledge that swimming carries risk. I confirm that I am able to swim unaided, I agree to follow the team’s and the venue’s instructions and to stay within the supervised area, and I am responsible for my own safety and for any medical condition that affects my ability to swim.", agree: "I have read the waiver and agree on behalf of everyone on this booking" },
    },
    waiverSub: "Read this and agree to continue.",
    tickFirst: "Tick the box above to continue.",
    // addonStepTitle addonStepSub addonsLabel nuButton invFree cat*
    addonsTitle: "Add on your booking",
    addonsSub: "Optional extras for this ride.",
    addons: "Add-ons",
    cats: { Helmet: "Helmet", Accessory: "Accessory", ProteinSnacks: "Protein Snacks", ElectrolyteSachets: "Electrolytes", EnergyGels: "Energy Gels", SparePart: "Spare part", Apparel: "Apparel", Other: "Other" } as Record<string, string>,
    // reviewSessionLabel bookedByLabel reviewRidersLabel reviewPartLabel reviewRentalLabel reviewTotalLabel regSummary
    rideLabel: "Ride",
    bookedBy: "Booked by",
    riders: "Riders",
    participants: "Participants",
    rental: "Rental",
    total: "Total",
    summary: "Your booking",
    // errAlreadyBooked myRidesTitle
    already: "You already have a booking for this session.",
    alreadySub: "Change or cancel it from My Bookings.",
    myBookings: "My Bookings",
    // the done step: toastWaitlisted tkReservedTitle tkBookedTitle tk*Sub regBookAnotherBtn errAddonsNotSaved
    doneWl: "Added to the waitlist",
    doneReserved: "Reservation received",
    doneBooked: "You’re booked",
    doneReservedSub: "Staff confirm each rider. Your code appears in My Bookings once your place is confirmed.",
    doneWlSub: "No place is held yet. Keep this code: if one opens, staff check you in with it.",
    doneBookedSub: "Show this code at the booth. It’s in My Bookings too.",
    another: "Book another ride",
    addonsNotSaved: "Your booking is made, but the add-ons were not saved. Add them from My Bookings.",
    ride: "Ride",
    // signing in first
    signTitle: "Sign in to book",
    signSub: "Sign in with your Micromobility account. You’ll come back to this ride.",
    signCreate: "Create an account",
    // commMembersTitle commMembersMsg commApplyBtn
    membersTitle: "Community members only",
    membersMsg: "Our community rides are for our community members. Apply for membership, and our team will review your application.",
    membersApply: "Apply for MicroMobility’s Community Membership",
    // rejTitle rejMsg rejNext rejOk
    rejTitle: "This week is full",
    rejMsg: "Your reservation for this ride wasn’t confirmed. Spots are limited and we try to fit in as many riders as we can.",
    rejNext: "We’d love to see you on the next ride.",
    rejOk: "Got it",
    // corrections staff asked for (FIX_FIRST)
    fixTitle: "Update your details first",
    fixMsg: "Our team asked you to check some details on your account. Update them in the booking app, then come back to book.",
    fixGo: "Update my details",
    fixFields: { name: "Name", email: "Email", phone: "Mobile number", birth_date: "Birth date", gender: "Gender", nationality: "Nationality", country: "Country", city: "City", height: "Height", photo: "Profile photo", password: "Password" } as Record<string, string>,
    // the profile page: pg* birthDateLabel nationalityLabel pgChooseCountry dobDay dobMonth dobYear
    pgKicker: "Before you book",
    pgTitle: "Two details to finish your profile",
    pgSub: "We need these once, then you’re back to the ride.",
    pgCommKicker: "Community members",
    pgCommTitle: "Two details for your community profile",
    pgCommSub: "Community members need these on their account before booking. It only takes a moment.",
    pgNote: "Kept on your account only, for age groups and our records. Other riders never see it.",
    pgSave: "Save and continue",
    pgSaving: "Saving…",
    pgErrBirth: "Enter your birth date to continue.",
    pgErrNat: "Choose your nationality to continue.",
    pgErrNet: "Couldn’t save. Check your connection and try again.",
    birth: "Birth date",
    nationality: "Nationality",
    chooseCountry: "Choose a country",
    day: "Day",
    month: "Month",
    year: "Year",
    // refusals: errSessionClosed errSessionStale errGroupCap errWaitlistFull errSelectTypeGeneric
    // errValidHeightCm errEnterName waiverRequired errPickGroup errSomethingWrong errNoInternet
    err: {
      closed: "That session is no longer open.",
      signin: "You’ve been signed out. Please sign in again.",
      group_cap: "Up to {0} riders per booking on this ride.",
      cap: "One account can book up to {0} riders.",
      waitlist_full: "The waitlist for this session is full.",
      pick_type: "Please select a bike type.",
      height: "Enter a height between 100 and 250 cm.",
      name: "Please enter your full name (first and last name).",
      waiver: "Please accept the waiver to continue.",
      group: "Choose your group",
      one_per_session: "You already have a booking for this session.",
      already: "You already have a booking for this session.",
      not_open: "Booking for this ride hasn’t opened yet.",
      generic: "That didn’t work, and we’ve been sent the details. Please try again.",
      offline: "You look offline. Check your connection and try again.",
    } as Record<string, string>,
  },
  ar: {
    stepRide: "الرحلة",
    stepRiders: "الركّاب",
    stepConfirm: "التأكيد",
    stepOf: "الخطوة {0} من {1}",
    rideTitle: "اختر رحلتك",
    rideMsg: "اختر اليوم الذي تريد الركوب فيه.",
    rideMsgJoin: "اختر اليوم الذي ترغب بالانضمام فيه.",
    ridersTitle: "بيانات الراكب",
    ridersMsg: "أخبرنا من سيركب وتفضيل الدراجة.",
    reviewTitle: "المراجعة والتأكيد",
    reviewMsg: "تحقق من التفاصيل أدناه ثم أكّد حجزك.",
    cont: "متابعة",
    back: "رجوع",
    toReview: "مراجعة الحجز",
    confirm: "تأكيد الحجز",
    pickFirst: "اختر رحلة من الأعلى للمتابعة.",
    allEvents: "كل الفعاليات",
    available: "متاح",
    waitlist: "قائمة الانتظار",
    left1: "{0} مقعد متبقي",
    leftN: "{0} مقاعد متبقية",
    rejCard: "مكتمل هذا الأسبوع",
    collectFrom: "استلام الدراجات من {0}",
    from: "من {0}",
    free: "مجاني",
    perSeat: "{0} للمقعد",
    partner: "بالشراكة مع الاتحاد السعودي للترايثلون",
    fullNote: "هذه الجولة مكتملة. يمكنك الحجز مع ذلك: ستنضم إلى قائمة الانتظار، وإذا توفر مقعد قد يختارك الفريق.",
    noRides: "لا توجد رحلات متاحة للحجز الآن.",
    noRidesSub: "ننشر المواعيد الجديدة على إنستغرام أولاً.",
    numBikes: "عدد الدراجات",
    capNote: "يمكن للحساب الواحد حجز {0} مشاركين كحد أقصى.",
    qtyDec: "إنقاص عدد الدراجات",
    qtyInc: "زيادة عدد الدراجات",
    rider: "الراكب",
    riderName: "الاسم الكامل للراكب",
    riderNamePh: "أدخل الاسم الكامل",
    height: "الطول",
    heightHint: "(لتحديد مقاس الإطار)",
    heightPh: "الطول بالسنتيمتر",
    cm: "سم",
    typePref: "تفضيل نوع الدراجة",
    typeHint: "جديد على ركوب الدراجات؟ الهجين هو الخيار الأسهل. اضغط i بجانب أي نوع لترى الدراجة.",
    types: { Road: "طريق", Hybrid: "هجين", Mountain: "جبلي", Kids: "أطفال", "Road Carbon": "طريق كربون", Own: "لدي دراجتي الخاصة", None: "" } as Record<string, string>,
    bikeAria: "عن دراجات {0}",
    bikeFleet: "أسطولنا من دراجات ألفاس",
    bestFor: "تناسب:",
    chooseBike: "اختر هذه الدراجة",
    close: "إغلاق",
    bikeInfo: {
      Road: { brief: "مقود منحنٍ وإطارات رفيعة وإحساس خفيف وسريع: مصممة للسرعة على أسفلت الحلبة الأملس، بوضعية ركوب منخفضة مائلة إلى الأمام.", good: "اللفات السريعة، ركوب اللياقة، ومن اعتاد دراجات الطريق.", level: "لراكبين واثقين" },
      "Road Carbon": { brief: "هيكل وشوكة من كربون Alvas X1 بأنابيب انسيابية وهندسة تحمّل، تروس شيمانو 105 (2×12)، مكابح قرصية هيدروليكية وإطارات 28 مم. خفيفة وصلبة وسريعة، من دون وضعية سباق ممدودة.", good: "راكبو الطريق ذوو الخبرة الذين يريدون أسرع دراجة على الحلبة.", level: "لراكبين ذوي خبرة" },
      Hybrid: { brief: "هيكل ألمنيوم خفيف، مقود مستقيم ووضعية جلوس منتصبة، إطارات عريضة، تروس سهلة ومكابح قرصية. سهلة وثابتة ومريحة.", good: "المبتدئون، اللفات الهادئة، وكل من يفضّل الراحة على السرعة.", level: "مناسبة للمبتدئين · الخيار الأسهل" },
      Mountain: { brief: "هيكل ألمنيوم، شوكة بنوابض، إطارات عريضة 2.1 بوصة على عجلات 27.5 أو 29 بوصة، تروس بذراع واحدة ومكابح قرصية. أبطأ على الأسفلت، لكنها الأكثر ثباتاً وسهولة في التحكم.", good: "من يريد دراجة متينة تمنح الثقة، أو من اعتاد الدراجات الجبلية.", level: "سهلة القيادة" },
      Kids: { brief: "هيكل ألمنيوم خفيف، تروس سهلة، مكابح قرصية، ومقابض وسرج بمقاس الأطفال، بمقاسات تناسب طفلك. فريقنا يختار المقاس المناسب عند المنصة.", good: "الصغار من عمر 5 سنوات، للركوب مع العائلة.", level: "للراكبين الصغار" },
    } as Record<string, { brief: string; good: string; level: string }>,
    groupLabel: "مجموعة الجولة",
    groups: { beg: "مجموعة المبتدئين", int: "مجموعة المتوسطين" } as Record<string, string>,
    groupBrief: { beg: "من نقطة التجمع إلى نادي جدة لليخوت ثم العودة إلى نقطة التجمع، بمتوسط سرعة يقارب 20 كم/ساعة.", int: "من نقطة التجمع حتى ما قبل دوار علوم البحار ثم العودة إلى نقطة التجمع." } as Record<string, string>,
    groupPlace: { beg: "نادي جدة لليخوت", int: "دوار علوم البحار" } as Record<string, string>,
    turnPoint: "نقطة العودة",
    chooseGroup: "اختر هذه المجموعة",
    groupAria: "عن {0}",
    km: "{0} كم",
    kmLap: "{0} كم للفة",
    route: "المسار",
    pricePerBike: "السعر للدراجة",
    onTheHouse: "على حساب المحل",
    payAtBooth: "تدفع عند الكشك حين تصل.",
    fcfs: "نوع الدراجة تفضيل وليس ضماناً: تُسلَّم الدراجات حسب أسبقية الوصول، فاحضر مبكراً لتحظى بما اخترت.",
    bike: "دراجة",
    promo: "رمز الخصم",
    promoApply: "تطبيق الرمز",
    promoRemove: "إزالة",
    discount: "الخصم",
    promoMsg: {
      invalid: "رمز غير صالح أو غير مفعّل",
      expired: "انتهت صلاحية هذا الرمز.",
      used_up: "تم استخدام هذا الرمز بالكامل.",
      not_yours: "هذا الرمز يخص حسابًا آخر.",
    } as Record<string, string>,
    promoTypeOnly: "هذا الرمز يسري فقط على حجوزات {0}.",
    waiver: {
      bike: { title: "إقرار الركوب", body: "أقرّ بأن ركوب الدراجة نشاط بدني ينطوي على مخاطر، وأتعهد بارتداء الخوذة والالتزام بتعليمات الفريق ومسار الحلبة، وأتحمل مسؤولية سلامتي الشخصية وأي ضرر يلحق بالدراجة المستأجرة نتيجة سوء الاستخدام. تعاد الدراجة بحالتها عند الاستلام.", agree: "قرأت الإقرار وأوافق نيابةً عن كل راكب في هذا الحجز" },
      swim: { title: "إقرار السباحة", body: "أقرّ بأن السباحة تنطوي على مخاطر. وأؤكد قدرتي على السباحة دون مساعدة، وأتعهد بالالتزام بتعليمات الفريق وإدارة الموقع والبقاء ضمن المنطقة الخاضعة للإشراف، وأتحمل مسؤولية سلامتي الشخصية وأي حالة صحية تؤثر على قدرتي على السباحة.", agree: "قرأت الإقرار وأوافق نيابةً عن كل شخص في هذا الحجز" },
    },
    waiverSub: "اقرأ الإقرار ووافق عليه للمتابعة.",
    tickFirst: "ضع علامة في المربع أعلاه للمتابعة.",
    addonsTitle: "أضف إلى حجزك",
    addonsSub: "إضافات اختيارية لهذه الرحلة.",
    addons: "الإضافات",
    cats: { Helmet: "خوذة", Accessory: "إكسسوار", ProteinSnacks: "سناك بروتين", ElectrolyteSachets: "إلكتروليت", EnergyGels: "جل طاقة", SparePart: "قطعة غيار", Apparel: "ملابس", Other: "أخرى" } as Record<string, string>,
    rideLabel: "الرحلة",
    bookedBy: "الحجز باسم",
    riders: "الركّاب",
    participants: "المشاركون",
    rental: "الإيجار",
    total: "الإجمالي",
    summary: "حجزك",
    already: "لديك حجز مسبق في هذه الجلسة.",
    alreadySub: "يمكنك تعديله أو إلغاؤه من حجوزاتي.",
    myBookings: "حجوزاتي",
    doneWl: "تمت إضافتك إلى قائمة الانتظار",
    doneReserved: "استلمنا طلب حجزك",
    doneBooked: "تم حجزك",
    doneReservedSub: "يؤكد الفريق كل مشارك على حدة. يظهر رمزك في حجوزاتي بعد تأكيد مقعدك.",
    doneWlSub: "لم يُحجز لك مقعد بعد. احتفظ بهذا الرمز: إذا توفر مقعد يسجّل الفريق دخولك به.",
    doneBookedSub: "اعرض هذا الرمز عند الكشك. تجده أيضاً في حجوزاتي.",
    another: "حجز رحلة أخرى",
    addonsNotSaved: "تم الحجز، لكن الإضافات لم تُحفظ. أضفها من حجوزاتي.",
    ride: "جولة",
    signTitle: "سجّل الدخول للحجز",
    signSub: "سجّل الدخول بحساب مايكروموبيليتي. ستعود إلى هذه الرحلة نفسها.",
    signCreate: "إنشاء حساب",
    membersTitle: "لأعضاء المجتمع فقط",
    membersMsg: "جولات مجتمعنا مخصّصة لأعضاء المجتمع. قدّم طلب العضوية وسيراجع فريقنا طلبك.",
    membersApply: "قدّم على عضوية مجتمع MicroMobility",
    rejTitle: "هذا الأسبوع مكتمل",
    rejMsg: "لم يتم تأكيد حجزك لهذه الجولة. المقاعد محدودة ونحاول استيعاب أكبر عدد ممكن من الراكبين.",
    rejNext: "يسعدنا أن نراك في الجولة القادمة.",
    rejOk: "حسناً",
    fixTitle: "حدّث بياناتك أولاً",
    fixMsg: "طلب فريقنا منك مراجعة بعض بيانات حسابك. حدّثها في تطبيق الحجز ثم عد للحجز.",
    fixGo: "تحديث بياناتي",
    fixFields: { name: "الاسم", email: "البريد الإلكتروني", phone: "رقم الجوال", birth_date: "تاريخ الميلاد", gender: "الجنس", nationality: "الجنسية", country: "الدولة", city: "المدينة", height: "الطول", photo: "الصورة الشخصية", password: "كلمة المرور" } as Record<string, string>,
    pgKicker: "قبل الحجز",
    pgTitle: "معلومتان لإكمال ملفك الشخصي",
    pgSub: "نحتاجهما مرة واحدة فقط، ثم تعود مباشرة إلى الجولة.",
    pgCommKicker: "أعضاء المجتمع",
    pgCommTitle: "معلومتان لملفك في المجتمع",
    pgCommSub: "يحتاج أعضاء المجتمع إلى هاتين المعلومتين في حساباتهم قبل الحجز. لن يستغرق الأمر سوى لحظة.",
    pgNote: "تُحفظ في حسابك فقط. تُستخدم للفئات العمرية وسجلاتنا، ولا تُعرض أبدًا للمتسابقين الآخرين.",
    pgSave: "حفظ ومتابعة",
    pgSaving: "جارٍ الحفظ…",
    pgErrBirth: "أدخل تاريخ ميلادك للمتابعة.",
    pgErrNat: "اختر جنسيتك للمتابعة.",
    pgErrNet: "لم نتمكن من الحفظ. تحقق من اتصالك بالإنترنت وحاول مرة أخرى.",
    birth: "تاريخ الميلاد",
    nationality: "الجنسية",
    chooseCountry: "اختر الدولة",
    day: "اليوم",
    month: "الشهر",
    year: "السنة",
    err: {
      closed: "هذه الجلسة لم تعد مفتوحة.",
      signin: "انتهت صلاحية جلستك — يرجى تسجيل الدخول من جديد.",
      group_cap: "حتى {0} راكبين لكل حجز في هذه الجولة.",
      cap: "يمكن للحساب الواحد حجز {0} مشاركين كحد أقصى.",
      waitlist_full: "قائمة الانتظار لهذه الجلسة ممتلئة.",
      pick_type: "الرجاء اختيار نوع الدراجة.",
      height: "أدخل طولاً بين 100 و250 سم.",
      name: "الرجاء إدخال اسمك الكامل (الاسم الأول والأخير).",
      waiver: "يرجى الموافقة على الإقرار للمتابعة.",
      group: "اختر مجموعتك",
      one_per_session: "لديك حجز مسبق في هذه الجلسة.",
      already: "لديك حجز مسبق في هذه الجلسة.",
      not_open: "لم يبدأ الحجز لهذه الجولة بعد.",
      generic: "لم تنجح العملية، ووصلتنا تفاصيل الخطأ. حاول مرة أخرى من فضلك.",
      offline: "يبدو أنك غير متصل بالإنترنت — تحقق من الاتصال وحاول مجدداً.",
    } as Record<string, string>,
  },
};
export type BookingText = (typeof T)["en"];
